<?php

/**
 * @file
 * Contains social_kpi_lite_tagged_content.module.
 */

/**
 * Implements hook_social_dashboard_kpi_block_list_alter().
 */
function social_kpi_lite_tagged_content_social_dashboard_kpi_block_list_alter(array &$kpi_blocks) {
  $kpi_blocks[] = 'block_content:36cd5bc8-609a-401f-8076-a8fdcf52c48c';
  $kpi_blocks[] = 'block_content:a2df532f-7ca5-4f17-a1f1-69deeb57ce1a';
  $kpi_blocks[] = 'block_content:0cec2c55-ed6e-4f2c-b047-c2a3b251b6d0';
  $kpi_blocks[] = 'block_content:2ff0d52e-0253-4b0b-aa80-4a1a0700379c';
  $kpi_blocks[] = 'block_content:e16e0f9b-f7e5-416c-b2ef-c5d696521873';
}
