<?php

/**
 * @file
 * The Social Sharing Post module.
 */

/**
 * Implements hook_theme().
 */
function social_sharing_post_theme() {
  return [
    'post_sharing' => [
      'variables' => ['url' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_post__activity().
 */
function social_sharing_post_preprocess_post__activity(&$variables) {
  /** @var \Drupal\social_post\Entity\PostInterface $entity */
  $entity = $variables['elements']['#post'];
  $url = $entity->toUrl('canonical', ['absolute' => TRUE])->toString();

  $variables['share_post'] = [
    '#theme' => 'post_sharing',
    '#url' => $url,
  ];
}

/**
 * Implements hook_preprocess_post__featured().
 */
function social_sharing_post_preprocess_post__featured(&$variables) {
  /** @var \Drupal\social_post\Entity\PostInterface $entity */
  $entity = $variables['elements']['#post'];
  $url = $entity->toUrl('canonical', ['absolute' => TRUE])->toString();

  $variables['share_post'] = [
    '#theme' => 'post_sharing',
    '#url' => $url,
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_sharing_post_preprocess_html(&$variables) {
  $variables['page']['content_top']['snackbar'] = [
    '#type' => 'markup',
    '#markup' => '<div id="snackbar">Link copied to clipboard.</div>',
  ];
}
