field.formatter.settings.file_image_default:
  type: field.formatter.settings.image
  label: 'Image field display format settings'

field.formatter.settings.comment_node:
  type: mapping
  label: 'Comment on node list'
  mapping:
    num_comments:
      type: integer
      label: 'Number of comments'
    always_show_all_comments:
      type: boolean
      label: 'Always show all comments'

field.value.social_external_identifier:
  type: mapping
  label: Default value
  mapping:
    external_id:
      type: string
      label: External ID
    external_owner_target_type:
      type: string
      label: External Owner Target type
    external_owner_id:
      type: integer
      label: External Owner ID

field.storage_settings.social_external_identifier:
  type: mapping
  label: "Social External Identifier field storage settings"
  mapping:
    target_types:
      type: sequence
      label: 'Target entity types'
      sequence:
        type: string
        label: 'Target entity type'

field.widget.settings.social_inline_entity_form_simple_conditional:
  type: mapping
  label: 'Conditional inline entity form widget settings'
  mapping:
    form_mode:
      type: string
      label: "Form mode"
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: label
      label: "Label (singular)"
    label_plural:
      type: label
      label: "Label (plural)"
    collapsible:
      type: boolean
      label: "Collapsible"
    collapsed:
      type: boolean
      label: "Collapsed by default"
    revision:
      type: boolean
      label: "Create new revision"
    required_fields:
      type: sequence
      label: 'Fields required to keep the inline entity'
      sequence:
        type: string
        label: 'Field machine name'
