alternative_frontpage.alternative_frontpage.*:
  type: config_entity
  label: 'alternative_frontpage config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    path:
      type: label
      label: 'Frontpage Path'
    roles_target_id:
      type: string
      label: 'Role TargetId'
