<?php
/**
 * @file
 * Install, update and uninstall functions for the social_comment module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of social_comment.
 */
function social_comment_install() {

  // Set some default permissions.
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, array(
    'access comments',
    'post comments',
    'skip comment approval',
    'edit own comments',
  ));

}
