<?php

/**
 * @file
 * Install, update and uninstall functions for the Social Analytics module.
 */

/**
 * Implements hook_install().
 */
function social_analytics_install(): void {
  user_role_grant_permissions('sitemanager', ['administer social_analytics settings']);
}

/**
 * Install individual metrics platform settings on existing sites.
 */
function social_analytics_update_26000(): void {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'social_analytics');
  user_role_grant_permissions('sitemanager', ['administer social_analytics settings']);
}

/**
 * Implements hook_uninstall().
 */
function social_analytics_uninstall(): void {
  \Drupal::configFactory()->getEditable('social_analytics.settings')->delete();
}
