<?php

/**
 * @file
 * The Social Content Block on Landing pages module.
 */

/**
 * Implements hook_preprocess().
 */
function social_content_block_landing_page_preprocess(&$variables, $hook) {
  if (isset($variables['elements']['#custom_content_list_section'])) {
    $variables['attributes']['class'][] = 'card';
    $variables['attributes']['class'][] = 'teaser';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_content_block_landing_page_preprocess_field(&$variables) {
  if (
    $variables['entity_type'] === 'paragraph' &&
    $variables['element']['#bundle'] === 'custom_content_list' &&
    $variables['field_name'] === 'field_custom_content_list'
  ) {
    $variables['attributes']['class'][] = 'container';
    $variables['items'][0]['content']['social_content_block']['#lazy_builder'][0] = 'social_content_block_landing_page.content_builder:build';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_content_block_landing_page_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->bundle() === 'custom_content_list') {
    $variables['#attached']['library'][] = 'social_featured_content/featured';
    $variables['#attached']['library'][] = 'social_content_block_landing_page/social_content_block_landing_page';
    $variables['attributes']['class'][] = 'paragraph--featured';
  }
}
