<?php

/**
 * @file
 * The Social event invite enroll module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\social_event\EventEnrollmentInterface;

/**
 * Sends email when invitation created for not registered user.
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function social_event_invite_event_enrollment_insert(EventEnrollmentInterface $eventEnrollment) {
  $messenger = \Drupal::messenger();

  $mail = $eventEnrollment->get('field_email')->getString();
  $langcode = 'en';

  $mailManager = \Drupal::service('plugin.manager.mail');
  $from = \Drupal::config('system.site')->get('mail');
  $params = [
    'user' => $from,
    'existing_user' => TRUE,
    'event_enrollment' => $eventEnrollment->id(),
  ];

  // Send a normal mail when the user has no account yet.
  if (empty($eventEnrollment->get('field_account')->getString())) {
    $params['existing_user'] = FALSE;
    $mailManager->mail('social_event_invite', 'invite', $mail, $langcode, $params, NULL, TRUE);
    $messenger->addMessage(t('Invite sent to %mail', ['%mail' => $mail]));
  }
  else {
    $account = \Drupal::entityTypeManager()->getStorage('user')->load($eventEnrollment->get('field_account')->getString());
    $messenger->addMessage(t('Invite sent to %user', ['%user' => $account->getEmail()]));
  }
}

/**
 * Implements hook_mail().
 *
 * This mail is sent when people who do not have an account on the website yet
 * are invited into an event. It is sent in the language the inviter was using
 * the website in.
 *
 */
function social_event_invite_mail($key, &$message, $params) {
  if ($key == 'invite') {
    $token_service = \Drupal::token();
    $language_manager = \Drupal::languageManager();

    $langcode = $message['langcode'];

    $language = $language_manager->getLanguage($langcode);
    $original_language = $language_manager->getConfigOverrideLanguage();
    $language_manager->setConfigOverrideLanguage($language);

    // Load event invite configuration
    $invite_config = \Drupal::service('config.factory')->getEditable('social_event_invite.settings');

    $invitation_subject = $invite_config->get('invite_subject');
    $invitation_body = $invite_config->get('invite_message');

    unset($params['existing_user']);

    $body = $token_service->replace($invitation_body, $params);
    $subject = $token_service->replace($invitation_subject, $params);

    $message['subject'] = $subject;
    $message['body'][] = $body;

    $language_manager->setConfigOverrideLanguage($original_language);

  }
}

/**
 * Implements hook_views_data().
 */
function social_event_invite_views_data() {
  $data['views']['social_event_invite_recipient'] = [
    'group' => t('Event enrollment'),
    'title' => t('Recipient'),
    'help' => t('The recipient of an event invite.'),
    'field' => [
      'id' => 'social_event_invite_recipient',
    ],
  ];
  return $data;
}

/**
 * Implements template_preprocess_views_view().
 */
function social_event_invite_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'event_manage_enrollment_invites') {
    $node_id = \Drupal::routeMatch()->getParameter('node');
    // Implement custom button to go back to the event.
    $variables['more'] = [
      '#title' => t('Back to event'),
      '#type' => 'link',
      '#url' => Url::fromRoute('entity.node.canonical', ['node' => (int) $node_id]),
      '#attributes' => [
        'class' => [
          'btn',
          'btn-default',
          'btn-lg',
          'btn-raised',
          'waves-effect',
        ],
      ],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function social_event_invite_user_insert(EntityInterface $entity) {
  // @todo: implement a better, more specific way to invalidate cache.
  // - config:field.storage.event_enrollment.field_request_or_invite_status.
  // - config:views.view.event_manage_enrollment_invites.
  // - event_enrollment_list.
  // - user_list.
  // - profile_list.
  // - profile_view.
  // - event_enrollment:ID.
  $tags = [
    'config:field.storage.event_enrollment.field_request_or_invite_status',
    'config:views.view.event_manage_enrollment_invites',
  ];
  Cache::invalidateTags($tags);
}
