<?php

/**
 * @file
 * The Social Admin Menu module.
 */

/**
 * Implements hook_toolbar_alter().
 */
function social_admin_menu_toolbar_alter(&$items) {
  $items['administration']['tray']['toolbar_administration'] = [
    '#lazy_builder' => [
      'social_admin_menu.administrator_menu_tree_manipulators:renderForm',
      [],
    ],
  ];
}

/**
 * Implements hook_module_implements_alter().
 */
function social_admin_menu_module_implements_alter(&$implementations, $hook) {
  // Remove the toolbar implementations from gin.
  // we are doing our own pre render in this module, and will add the
  // gin requirements in there.
  if ($hook === 'toolbar') {
    if (isset($implementations['gin_toolbar'])) {
      unset($implementations['gin_toolbar']);
    }
  }
}
