social_node_statistics.node_types:
  type: sequence
  sequence:
    - type: string
    - label: 'Node types views should be tracked for'

social_node_statistics.max_age:
  type: integer
  label: 'Max age in seconds'

social_node_statistics.min_views:
  type: integer
  label: 'Minimum number of views before cache invalidation'
