<?php

/**
 * Added editor advanced link html attributes.
 */
function social_editor_update_8001() {
  /** @var \Drupal\update_helper\Updater $updateHelper */
  $updateHelper = \Drupal::service('update_helper.updater');

  // Execute configuration update definitions with logging of success.
  $updateHelper->executeUpdate('social_editor', 'social_editor_update_8001');

  // Output logged messages to related channel of update execution.
  return $updateHelper->logger()->output();
}
