<?php

/**
 * @file
 * Installation file for Social Comment Upload.
 */

/**
 * Install the module.
 */
function social_comment_upload_install() {
  // Sitemanagers should be able to change the settings.
  user_role_grant_permissions(
    'sitemanager',
    ['administer social_comment_upload settings']
  );
}

/**
 * Implements hook_update_last_removed().
 */
function social_comment_upload_update_last_removed() : int {
  return 8001;
}
