<?php

/**
 * @file
 * The Social Group Flexible Group module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\social_group_flexible_group\Form\GroupAddFlexibilityForm;


/**
 * Provide a method to alter array of group types used in open social.
 *
 * @param array $social_group_types
 *   List of group types used in open social.
 *
 * @ingroup social_group_api
 */
function social_group_flexible_group_social_group_types_alter(array &$social_group_types) {
  $social_group_types[] = 'flexible_group';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_group_flexible_group_form_social_group_add_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Rearrange all the options so flexible is last
  // we will need the space for the configuration.
  $type_options = $form['group_settings']['group_type']['#options'];

  // Seems to be the most performant.
  if (!empty($type_options['flexible_group'])) {
    $flexible = $type_options['flexible_group'];
    unset($form['group_settings']['group_type']['#options']['flexible_group']);
    $form['group_settings']['group_type']['#options']['flexible_group'] = $flexible;

    // Now we can add the configuration.
    GroupAddFlexibilityForm::addFlexibilityOptions($form, $form_state);
  }
}
