<?php

/**
 * @file
 * Update and install hooks for Social Course Basic Request.
 */

use Drupal\social_course\SocialCourseUninstallHelper;

/**
 * Implements hook_uninstall().
 */
function social_course_basic_request_uninstall(): void {
  SocialCourseUninstallHelper::deleteGroupRelationships('social_course_basic_request');
}

/**
 * Implements hook_update_dependencies().
 */
function social_course_basic_request_update_dependencies(): array {
  // Field instances in 13002 depend on field storage from social_group_request.
  $dependencies['social_course_basic_request'][13002] = [
    'social_group_request' => 13011,
  ];

  return $dependencies;
}

/**
 * Update membership request form display.
 */
function social_course_basic_request_update_13001(): string {
  /** @var \Drupal\update_helper\Updater $updater */
  $updater = \Drupal::service('update_helper.updater');

  // Execute configuration update definitions with logging of success.
  $updater->executeUpdate('social_course_basic_request', __FUNCTION__);

  // Output logged messages to related channel of update execution.
  return $updater->logger()->output();
}

/**
 * Add request-to-join form customization fields to course_basic group type.
 */
function social_course_basic_request_update_13002(): string {
  /** @var \Drupal\update_helper\Updater $updater */
  $updater = \Drupal::service('update_helper.updater');
  $updater->executeUpdate('social_course_basic_request', __FUNCTION__);
  return $updater->logger()->output();
}

/**
 * Add enforced dependency to all module config.
 */
function social_course_basic_request_update_13003(): void {
  SocialCourseUninstallHelper::addEnforcedDependency('social_course_basic_request');
}
