<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_form_FORM_ID_alter() on behalf of social_user.module.
 * @see \Drupal\user\RegisterForm method buildForm at /core/lib/Drupal/Core/Entity/EntityForm.php
 */
function social_user_form_user_register_form_alter(&$form, FormStateInterface $form_state) {
  // By default notify the user of the new account.
  if (isset($form['account']['notify']) && $form['account']['notify']['#access'] === TRUE) {
    $form['account']['notify']['#default_value'] = 1;
  }
}

/**
 * Check if an users with the input field for name or mail field is blocked.
 *
 * @param $name_or_mail string username or email adress.
 * @return bool TRUE if blocked FALSE if not blocked
 */
function social_user_is_blocked($name_or_mail) {
  $is_blocked_name = (bool) \Drupal::entityQuery('user')
    ->condition('name', $name_or_mail)
    ->condition('status', 0)
    ->execute();

  $is_blocked_mail = (bool) \Drupal::entityQuery('user')
    ->condition('mail', $name_or_mail)
    ->condition('status', 0)
    ->execute();

  if ($is_blocked_name || $is_blocked_mail) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function social_user_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  // Add the custom Social username constraint.
  if ($entity_type->id() == 'user' && isset($fields['name'])) {
    $fields['name']->addConstraint('SocialUserName');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_user_preprocess_status_messages(&$variables) {
  $routeName = \Drupal::request()->get(Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_NAME);

  // On AN password request, we would like to purge the status messages.
  if ($routeName == 'user.pass') {
    $messages = $variables['message_list'];
    // Remove all the messages that might leak information.
    $message_list = social_user_no_message_leaking($messages);
    $variables['message_list'] = $message_list;
  }
}

/**
 * Helper function with all the statuses and corresponding part of messages
 * where we can strpos on.
 *
 * @return array with all the messages to purge keyed by status type.
 */
function social_get_messages_to_purge() {
  $purge_messages= array();

  $purge_messages['error'][] = 'blocked or has not been activated yet';
  $purge_messages['error'][] = 'not recognized as a username or an email address';
  $purge_messages['status'][] = 'Further instructions have been sent to your email address.';

  return $purge_messages;
}

/**
 * Helper function to remove any messages from the user.pass route
 * so we don't leak any data.
 *
 * @param $messages array with list of messages.
 * @return array with messages.
 */
function social_user_no_message_leaking($messages) {
  // Default value.
  $didwepurge = FALSE;

  if (!empty($messages)) {
    // Check if we have messages that need to be purged for a certain status.
    $purge_messages = social_get_messages_to_purge();

    // Check all the status messages coming from the prepocess_status_message.
    foreach ($messages as $type => $arr_messages) {
      foreach ($arr_messages as $key => $message) {
        // Match it against all the messages we remove per status type.
        foreach ($purge_messages[$type] as $place => $stringtofind) {
          if (strpos($message, $stringtofind)) {
            unset($messages[$type][$key]);
            // If there are no other messages of the type we can unset it and
            // clean the messages type.
            if (empty($messages[$type])) {
              unset($messages[$type]);
            }
            // Make sure we switch boolean so we add our default message.
            $didwepurge = TRUE;
          }
        }
      }
    }
  }

  // Only if we removed one of the status messages we want to do this stuffs.
  if ($didwepurge) {
    $messages['warning'][] = t('Due to privacy concerns, the policy of this web site is not to disclose the existence of registered email addresses.
  Hence, if you entered a valid email address or username, a password reset link is now being sent to it.
  If the email address or username you entered does not exist, you will not get a reset link, and will neither get any confirmation or warning about that here.
  Contact the site administrator if there are any problems.');
  }

  return $messages;
}