<?php
/**
 * @file
 * The Social activity stream module.
 */

use \Drupal\message\Entity\Message;

/**
 * Implements hook_entity_insert().
 */
function social_activity_logger_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  // For every insert we create an activity item

  // @TODO: Remove this.
/*  if ($entity->getEntityTypeId() === 'node') {
    if ($entity->bundle() == 'topic') {
      $message = Message::create(['type' => 'create_topic_community', 'uid' => $entity->getOwner()]);
      $message->set('field_context', 'community');
      $message->set('field_destinations', array(0, 1, 2, 3, 4));
      $message->save();
    }
  }*/
}
