social_embed.settings:
  type: config_object
  label: 'Embedded content settings'
  mapping:
    embed_consent_settings_lu:
      type: boolean
      label: 'Status of embedded content settings for LU'
    embed_consent_settings_an:
      type: boolean
      label: 'Status of embedded content settings for AN'
