activity_send.settings:
  type: config_object
  label: 'Activity send settings'
  mapping:
    activity_send_offline_window:
      type: integer
      label: 'Number of seconds of inactivity after which we assume user is offline'
