core.entity_view_display.group_content.group_content_type_7fcb76fdf61a9.default:
  expected_config:
    hidden:
      field_grequest_message: true
      langcode: true
  update_actions:
    delete:
      hidden:
        field_grequest_message: true
        langcode: true
field.field.group_content.group_content_type_7fcb76fdf61a9.field_grequest_message:
  expected_config:
    description: ''
  update_actions:
    change:
      description: 'You can leave a message in your request. Only when your request is approved, you will receive a notification via email and notification center.'
