__global_actions:
  import_configs:
    - social_group_request.settings
    - field.storage.group.field_grequest_form_required
    - field.storage.group.field_grequest_form_description
    - field.storage.group.field_grequest_form_default
    - field.field.group.flexible_group.field_grequest_form_required
    - field.field.group.flexible_group.field_grequest_form_description
    - field.field.group.flexible_group.field_grequest_form_default
