<?php

/**
 * @file
 * Defines social field types.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_menu().
 */
function social_menu() {
  $items = array();

  $items['admin/config/system/social-comments'] = array(
    'title' => 'Social comments',
    'description' => 'Configure social comments',
    'route_name' => 'social.settings',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function social_theme() {
  return array(
    'social_items' => array(
      'variables' => array(
        'comments' => array(),
        'bundle' => NULL,
        'type' => NULL,
        'view_mode' => NULL,
      ),
      'template' => 'social-items',
    )
  );
}

/**
 * Prepares variables for social-comments-items template.
 */
function template_preprocess_social_items(&$variables) {
  $comments = &$variables['comments'];

  if (is_array($comments)) {
    foreach ($comments as &$comment) {
      $comment['timestamp'] = format_date($comment['timestamp'], 'short');
      $comment['userphoto'] = theme('image', array('uri' => $comment['userphoto']));
    }
  }

  $variables['theme_hook_suggestions'][] = 'social_items__' . $variables['type'];
  $variables['theme_hook_suggestions'][] = 'social_items__' . $variables['bundle'];
  $variables['theme_hook_suggestions'][] = 'social_items__' . $variables['type'] . '__' . $variables['view_mode'];
  $variables['theme_hook_suggestions'][] = 'social_items__' . $variables['type'] . '__' . $variables['bundle'];
  $variables['theme_hook_suggestions'][] = 'social_items__' . $variables['type'] . '__' . $variables['bundle'] . '__' . $variables['view_mode'];
}
