<?php

/**
 * @file
 * Defines social field types.
 */

/**
 * Implements hook_menu().
 */
function social_menu() {
  $items = array();

  $items['admin/config/system/social-comments'] = array(
    'title' => 'Social comments',
    'description' => 'Configure social comments',
    'route_name' => 'social.settings',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function social_theme() {
  return array(
    'social_items' => array(
      'variables' => array(
        'comments' => array(),
        'bundle' => NULL,
        'entity_type' => NULL,
        'type' => NULL,
        'view_mode' => NULL,
      ),
      'template' => 'social-items',
    ),
  );
}

/**
 * Prepares variables for social-items template.
 */
function template_preprocess_social_items(&$variables) {
  $comments = &$variables['comments'];

  if (is_array($comments)) {
    foreach ($comments as &$comment) {
      $comment['date'] = format_date($comment['timestamp'], 'medium');
      $comment['user_photo'] = theme('image', array('uri' => $comment['user_photo']));
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function social_theme_suggestions_social_items(array $variables) {
  $suggestions = array();

  $suggestions[] = 'social_items__' . $variables['entity_type'];
  $suggestions[] = 'social_items__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['bundle'];
  $suggestions[] = 'social_items__' . $variables['bundle'] . '__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['entity_type'] . '__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['entity_type'] . '__' . $variables['bundle'] . '__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['type'];
  $suggestions[] = 'social_items__' . $variables['type'] . '__' . $variables['bundle'];
  $suggestions[] = 'social_items__' . $variables['type'] . '__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['type'] . '__' . $variables['bundle'] . '__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['type'] . '__' . $variables['entity_type'] . '__' . $variables['view_mode'];
  $suggestions[] = 'social_items__' . $variables['type'] . '__' . $variables['entity_type'] . '__' . $variables['bundle'] . '__' . $variables['view_mode'];

  return $suggestions;
}
