views.view.group_members:
  expected_config:
    display:
      default:
        display_options:
          title: 'Group Members'
  update_actions:
    change:
      display:
        default:
          display_options:
            title: 'Filter'
