social_group.settings:
  expected_config: {  }
  update_actions:
    delete:
      disallow_lu_create_groups_secret_group: {  }
      disallow_lu_create_groups_public_group: {  }
      disallow_lu_create_groups_open_group: {  }
      disallow_lu_create_groups_closed_group: {  }

block.block.views_block__group_managers_block_list_managers:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            closed_group: closed_group
            open_group: open_group
            public_group: public_group
    add:
      visibility:
        group_type:
          group_types:
            flexible_group: flexible_group

views.view.group_manage_members:
  expected_config: {  }
  update_actions:
    delete:
      dependencies:
        config: {  }
      display:
        default:
          display_options:
            filters:
              type: {  }
    add:
      dependencies:
        config:
          - core.entity_view_mode.profile.table
          - field.storage.group_content.group_roles
          - field.storage.profile.field_profile_organization

views.view.group_managers:
  expected_config: { }
  update_actions:
    delete:
      dependencies:
        config: {  }
      display:
        default:
          display_options:
            filters:
              group_roles_target_id_2: {  }
              group_roles_target_id_1: {  }
              group_roles_target_id: {  }
    add:
      dependencies:
        config:
          - core.entity_view_mode.profile.compact_teaser
          - group.content_type.flexible_group-group_membership
          - group.type.flexible_group
          - profile.type.profile
      display:
          default:
            display_options:
              filters:
                group_roles_target_id:
                  id: group_roles_target_id
                  table: group_content__group_roles
                  field: group_roles_target_id
                  relationship: group_content
                  group_type: group
                  admin_label: ''
                  operator: '='
                  value: flexible_group-group_manager
                  group: 1
                  exposed: false
                  expose:
                    operator_id: ''
                    label: ''
                    description: ''
                    use_operator: false
                    operator: ''
                    identifier: ''
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                    operator_limit_selection: false
                    operator_list: { }
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
                  plugin_id: string

views.view.group_members:
  expected_config: { }
  update_actions:
    delete:
      dependencies:
        config: {  }
      display:
        default:
          display_options:
            filters:
              type: {  }
            arguments:
              gid:
                validate_options:
                  bundles:
                    open_group: open_group
                    closed_group: closed_group
                    public_group: public_group
                    secret_group: secret_group
    add:
      display:
        default:
          display_options:
            relationships:
              gc__user:
                id: gc__user
                table: group_content_field_data
                field: gc__user
                relationship: none
                group_type: group
                admin_label: 'Group content User'
                entity_type: group_content
                plugin_id: group_content_to_entity
                required: true
                group_content_plugins:
                  group_membership: group_membership
                  group_invitation: '0'
                  group_membership_request: '0'

views.view.group_topics:
  expected_config: { }
  update_actions:
    delete:
      dependencies:
        config: {  }
      display:
        default:
          display_options:
            filters:
              type: {  }
            arguments:
              gid:
                validate_options: {  }
    add:
      dependencies:
        config:
          - core.entity_view_mode.group_content.teaser
          - taxonomy.vocabulary.topic_types
    change:
      display:
        default:
          display_options:
            relationships:
              gc__node:
                required: true

views.view.group_events:
  expected_config: { }
  update_actions:
    delete:
      dependencies:
        config: {  }
      display:
        default:
          display_options:
            filters:
              type: {  }
            arguments:
              gid:
                validate_options: {  }
    add:
      dependencies:
        config:
          - core.entity_view_mode.group_content.teaser
    change:
      display:
        default:
          display_options:
            relationships:
              gc__node:
                required: true

views.view.newest_groups:
  expected_config: { }
  update_actions:
    delete:
      display:
        block_newest_groups:
          cache_metadata:
            contexts: { }
        page_all_groups:
          cache_metadata:
            contexts: { }
    change:
      display:
        page_all_groups:
          display_options:
            defaults:
              filters: false
              filter_groups: false
    add:
      display:
        block_newest_groups:
          cache_metadata:
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - user
              - user.permissions
        page_all_groups:
          cache_metadata:
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - url
              - url.query_args
              - user
              - user.permissions
          display_options:
            filters:
              default_langcode:
                id: default_langcode
                table: groups_field_data
                field: default_langcode
                relationship: none
                group_type: group
                admin_label: ''
                operator: '='
                value: '1'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                entity_type: group
                entity_field: default_langcode
                plugin_id: boolean
              field_group_allowed_join_method_value:
                id: field_group_allowed_join_method_value
                table: group__field_group_allowed_join_method
                field: field_group_allowed_join_method_value
                relationship: none
                group_type: group
                admin_label: ''
                operator: or
                value: { }
                group: 1
                exposed: true
                expose:
                  operator_id: field_group_allowed_join_method_value_op
                  label: 'Join method'
                  description: ''
                  use_operator: false
                  operator: field_group_allowed_join_method_value_op
                  identifier: field_group_allowed_join_method
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: field_group_allowed_join_method
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                plugin_id: list_field
