views.view.group_events:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                group_permission: 'view group_node:event relationship'

views.view.group_members:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                group_permission: 'view group_membership relationship'

views.view.group_topics:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                group_permission: 'view group_node:topic relationship'
