views.view.group_members:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            relationships:
              gc__user:
                table: group_relationship_field_data

views.view.group_managers:
  expected_config: { }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filter_groups:
              groups: {  }
    add:
      display:
        default:
          display_options:
            filter_groups:
              groups:
                1: AND

views.view.group_manage_members:
  expected_config: { }
  update_actions:
    change:
      display:
        default:
          display_options:
            fields:
              operations:
                table: group_relationship
