views.view.group_manage_members:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            fields:
              group_roles:
                delta_limit: null
