views.view.group_per_type:
  expected_config: { }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              type: bef
              options:
                submit_button: Filter
                reset_button: true
                reset_button_label: Clear
                exposed_sorts_label: 'Sort by'
                expose_sort_order: true
                sort_asc_label: Asc
                sort_desc_label: Desc
                text_input_required: 'Select any filter and click on Apply to see results'
                text_input_required_format: basic_html
                bef:
                  general:
                    autosubmit: false
                    autosubmit_exclude_textfield: false
                    autosubmit_textfield_delay: 500
                    autosubmit_textfield_minimum_length: 3
                    autosubmit_hide: false
                    input_required: false
                    allow_secondary: false
                    secondary_label: 'Advanced options'
                    secondary_open: false
                    reset_button_always_show: true
                  filter:
                    label:
                      plugin_id: default
                      advanced:
                        placeholder_text: ''
                        collapsible: false
                        collapsible_disable_automatic_open: false
                        is_secondary: false
                        hide_label: false
                    status:
                      plugin_id: default
                      advanced:
                        sort_options: false
                        rewrite:
                          filter_rewrite_values: ''
                          filter_rewrite_values_key: false
                        collapsible: false
                        collapsible_disable_automatic_open: false
                        is_secondary: false
                        hide_label: false
            empty:
              area_text_custom:
                id: area_text_custom
                table: views
                field: area_text_custom
                relationship: none
                group_type: group
                admin_label: ''
                plugin_id: text_custom
                empty: true
                content: 'No content available.'
                tokenize: false
            style:
              options:
                empty_table: true
