views.view.groups:
  expected_config: { }
  update_actions:
    add:
      display:
        page_user_groups:
          display_options:
            display_extenders:
              views_ef_fieldset:
                views_ef_fieldset:
                  enabled: false
                  options:
                    sort:
                      root:
                        container_type: details
                        depth: '0'
                        description: ''
                        id: root
                        open: true
                        pid: ''
                        title: Filters
                        type: container
                        weight: '0'
                      flagged:
                        depth: '1'
                        id: flagged
                        pid: root
                        type: filter
                        weight: '-8'
                      sort_by:
                        depth: '1'
                        id: sort_by
                        pid: root
                        type: sort
                        weight: '-8'
                      submit:
                        depth: '1'
                        id: submit
                        pid: root
                        type: buttons
                        weight: '-7'
                      reset:
                        depth: '1'
                        id: reset
                        pid: root
                        type: buttons
                        weight: '-6'
            defaults:
              sorts: false
            exposed_form:

              options:
                exposed_sorts_label: 'Sort by:'
                bef:
                  sort:
                    plugin_id: bef_sort_page_top
                    advanced:
                      combine: false
                      combine_rewrite: ''
                      reset: false
                      reset_label: ''
                      collapsible: false
                      collapsible_label: 'Sort options'
                      is_secondary: false
            sorts:
              created:
                id: created
                table: groups_field_data
                field: created
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: created
                plugin_id: date
                order: DESC
                expose:
                  label: Created
                  field_identifier: created
                exposed: true
                granularity: second
              label:
                id: label
                table: groups_field_data
                field: label
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: label
                plugin_id: standard
                order: ASC
                expose:
                  label: Name
                  field_identifier: label
                exposed: true
          cache_metadata:
            contexts:
              - 'url.query_args:sort_by'
              - 'url.query_args:sort_order'
    change:
      display:
        default:
          display_options:
            pager:
              type: full
              options:
                offset: 0
                pagination_heading_level: h4
                items_per_page: 6
                total_pages: null
                id: 0
                tags:
                  next: ››
                  previous: ‹‹
                  first: '« First'
                  last: 'Last »'
                expose:
                  items_per_page: false
                  items_per_page_label: 'Items per page'
                  items_per_page_options: '5, 10, 25, 50'
                  items_per_page_options_all: false
                  items_per_page_options_all_label: '- All -'
                  offset: false
                  offset_label: Offset
                quantity: 9
        page_user_groups:
          display_options:
            exposed_form:
              options:
                bef:
                  general:
                    autosubmit: true
            use_ajax: true
