views.view.groups:
  expected_config: {  }
  update_actions:
    add:
      display:
        page_user_groups:
          display_options:
            exposed_form:
              options:
                bef:
                  filter:
                    flagged:
                      advanced:
                        collapsible: false
                        is_secondary: false
                        rewrite:
                          filter_rewrite_values: "- Any -|- Any -\r\nTrue|My muted groups\r\nFalse|My unmuted groups"
                        sort_options: false
                      plugin_id: default
                  general:
                    autosubmit_textfield_delay: 500
                    input_required: false
                    secondary_open: false
