views.view.group_members:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              status:
                id: status
                table: users_field_data
                field: status
                relationship: gc__user
                group_type: group
                admin_label: ''
                entity_type: user
                entity_field: status
                plugin_id: boolean
                operator: '='
                value: '1'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }

views.view.group_manage_members:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              status:
                id: status
                table: users_field_data
                field: status
                relationship: gc__user
                group_type: group
                admin_label: ''
                entity_type: user
                entity_field: status
                plugin_id: boolean
                operator: '='
                value: '1'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
