views.view.group_events:
  expected_config: {  }
  update_actions:
    add:
      display:
        page_group_events:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
