views.view.groups:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            query:
              options:
                distinct: TRUE
    add:
      display:
        block_user_groups:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        page_user_groups:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
views.view.newest_groups:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            query:
              options:
                distinct: TRUE
    add:
      display:
        block_newest_groups:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        page_all_groups:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
