views.view.group_members:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            relationships:
              gc__user:
                table: group_relationship_field_data
