views.view.groups:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              label:
                id: label
                table: groups_field_data
                field: label
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: label
                plugin_id: standard
                order: ASC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
views.view.newest_groups:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              label:
                id: label
                table: groups_field_data
                field: label
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: label
                plugin_id: standard
                order: ASC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
