views.view.group_events:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              nid: {  }
views.view.group_topics:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              nid: {  }
