views.view.groups:
  expected_config: { }
  update_actions:
    change:
      display:
        page_user_groups:
          display_options:
            exposed_form:
              options:
                bef:
                  general:
                    autosubmit_hide: true
                    reset_button_always_show: true
