views.view.group_managers:
  expected_config: {}
  update_actions:
    change:
      display:
        default:
          display_options:
            filter_groups:
              groups:
                1: AND
