field.field.node.event.field_event_an_enroll:
  expected_config:
    description: ''
    label: 'Allow users to enroll to this event without creating an account'
  update_actions:
    change:
      description: 'To allow users to enroll in this event without an account, this event must be visible to the public and open for all users.'
      label: 'Allow users to enroll to this event without an account'
