<?php

/**
 * @file
 * The Social Content Block module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_block().
 */
function social_content_block_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] === 'block_content' &&
    isset($variables['content']['#block_content']) &&
    $variables['content']['#block_content']->bundle() === 'custom_content_list'
  ) {
    $variables['card'] = TRUE;
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function social_content_block_entity_extra_field_info() {
  return [
    'block_content' => [
      'custom_content_list' => [
        'display' => [
          'entities' => [
            'label' => t('Entities'),
            'weight' => 0,
          ],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function social_content_block_block_content_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() === 'custom_content_list' && $display->getComponent('entities')) {
    $build['social_content_block'] = [
      '#lazy_builder' => [
        'social_content_block.content_builder:build',
        [
          $entity->getEntityTypeId(),
          $entity->id(),
        ],
      ],
      '#create_placeholder' => TRUE,
    ];
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function social_content_block_form_block_content_custom_content_list_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add general description above first field to explain what the filters do.
  $form['field_topic_type'] += [
    '#prefix' => t('To make the list of topics more specific you can additionally configure more filters such as topic types, content tags and groups.'),
  ];

  // Add description per field explaining what to fill in.
  $form['field_topic_type'] += [
    '#suffix' => t('Autocomplete field with items from taxonomy list topic types.'),
  ];
  $form['field_content_tags'] += [
    '#suffix' => t('Autocomplete field with items from taxonomy list content tags.'),
  ];
  $form['field_group'] += [
    '#suffix' => t('Autocomplete field with group names.'),
  ];

  // Add submit handler to clear cache.
  foreach (array_keys($form['actions']) as $action) {
    if ($action !== 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'custom_content_block_form_submit';
    }
  }
}

/**
 * Custom submit handler.
 */
function custom_content_block_form_submit($form, FormStateInterface $form_state) {
  // Clear plugin cache.
  \Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();
}

/**
 * Implements hook_theme().
 */
function social_content_block_theme($existing, $type, $theme, $path) {
  return [
    'social_content_block' => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'topics' => [],
        'link' => NULL,
      ],
    ],
  ];
}
