<?php

/**
 * @file
 * The Social Content Block module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_block().
 */
function social_content_block_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] === 'block_content' &&
    isset($variables['content']['#block_content']) &&
    $variables['content']['#block_content']->bundle() === 'custom_content_list'
  ) {
    $variables['card'] = TRUE;
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function social_content_block_entity_extra_field_info() {
  return [
    'block_content' => [
      'custom_content_list' => [
        'display' => [
          'entities' => [
            'label' => t('Entities'),
            'weight' => 0,
          ],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function social_content_block_block_content_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() === 'custom_content_list' && $display->getComponent('entities')) {
    $build['social_content_block'] = [
      '#lazy_builder' => [
        'social_content_block.content_builder:build',
        [
          $entity->getEntityTypeId(),
          $entity->id(),
        ],
      ],
      '#create_placeholder' => TRUE,
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function social_content_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_ids = [
    'block_content_custom_content_list_form',
    'block_content_custom_content_list_edit_form',
  ];

  if (!in_array($form_id, $form_ids)) {
    return;
  }

  /** @var \Drupal\social_content_block\ContentBlockManagerInterface $content_block_manager */
  $content_block_manager = \Drupal::service('plugin.manager.content_block');

  foreach ($content_block_manager->getDefinitions() as $plugin_id => $plugin_definition) {
    $fields = &$form['field_plugin_field']['widget'][0][$plugin_id]['#options'];

    foreach ($fields as $field_name => $field_title) {
      // When the filter field was absent during executing the code of the field
      // widget plugin for the filters list field then process this field
      // repeatedly.
      // @see \Drupal\social_content_block\Plugin\Field\FieldWidget\ContentBlockPluginFieldWidget::formElement()
      if ($field_name === $field_title) {
        $fields[$field_name] = $form[$field_name]['widget']['target_id']['#title'];

        $form[$field_name]['#states'] = [
          'visible' => [
            ':input[name="field_plugin_id[0][value]"]' => [
              'value' => $plugin_id,
            ],
            ':input[name="field_plugin_field[0][' . $plugin_id . ']"]' => [
              ['value' => 'all'],
              ['value' => $field_name],
            ],
          ],
        ];
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function social_content_block_form_block_content_custom_content_list_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add submit handler to clear cache.
  foreach (array_keys($form['actions']) as $action) {
    if ($action !== 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'custom_content_block_form_submit';
    }
  }
}

/**
 * Custom submit handler.
 */
function custom_content_block_form_submit($form, FormStateInterface $form_state) {
  // Clear plugin cache.
  \Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();
}
