<?php
/**
 * @file
 * Install, update and uninstall functions for the social_user module.
 */

/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of social_user.
 */
function social_user_install() {

  // Set some default permissions.
  _social_user_set_permissions();
}

/**
 * Function to set permissions.
 */
function _social_user_set_permissions() {
  $roles = \Drupal\user\Entity\Role::loadMultiple();

  /** @var \Drupal\user\Entity\Role $role */
  foreach ($roles as $role) {
    if ($role->id() === 'administrator') {
      continue;
    }

    $permissions = _social_user_get_permissions($role->id());
    user_role_grant_permissions($role->id(), $permissions);
  }
}

/**
 * @param $role
 * @return array
 */
function _social_user_get_permissions($role) {
  // Anonymous.
  $permissions['anonymous'] = array(

  );

  // Authenticated.
  $permissions['authenticated'] = array_merge($permissions['anonymous'], array(
    'access user profiles',
    'cancel account',
    'change own username',
    'select account cancellation method',
  ));

  // Content manager.
  $permissions['contentmanager'] = array_merge($permissions['authenticated'], array(

  ));

  // Site manager.
  $permissions['sitemanager'] = array_merge($permissions['contentmanager'], array(

  ));

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
  return [];
}
