# Schema for the configuration files of the Social Event Max Enroll module.
social_event_max_enroll.settings:
  type: config_object
  label: 'Social Event Max Enroll settings'
  mapping:
    max_enroll:
      type: boolean
      label: 'Whether the maximum number of event enrollments feature is enabled'
    max_enroll_required:
      type: boolean
      label: 'Whether the maximum event enrollments field is required'
