social_group.settings:
  type: config_object
  label: 'Social Group Settings'
  mapping:
    allow_group_selection_in_node:
      type: boolean
      label: 'Allow logged-in users to change or remove a group when editing content.'
