views.view.search_groups:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              search_api_language:
                id: search_api_language
                table: search_api_index_social_groups
                field: search_api_language
                relationship: none
                group_type: group
                admin_label: ''
                operator: in
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                plugin_id: search_api_language
views.view.search_all:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              search_api_language:
                id: search_api_language
                table: search_api_index_social_all
                field: search_api_language
                relationship: none
                group_type: group
                admin_label: ''
                operator: in
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                plugin_id: search_api_language
views.view.search_content:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              search_api_language:
                id: search_api_language
                table: search_api_index_social_content
                field: search_api_language
                relationship: none
                group_type: group
                admin_label: ''
                operator: in
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
                plugin_id: search_api_language
