search_api.index.social_all:
  expected_config: {}
  update_actions:
    delete: {}
    add:
      processor_settings:
        verified_users:
          weights:
            preprocess_query: 30
    change: {}
search_api.index.social_users:
  expected_config: {}
  update_actions:
    delete: {}
    add:
      processor_settings:
        verified_users:
          weights:
            preprocess_query: 30
    change: {}
