search_api.index.social_all:
  expected_config: {  }
  update_actions:
    add:
      processor_settings:
        social_search_tagging_query:
          weights:
            preprocess_query: -100
search_api.index.social_content:
  expected_config: {  }
  update_actions:
    add:
      processor_settings:
        social_search_tagging_query:
          weights:
            preprocess_query: -100
