search_api.index.social_all:
  expected_config: {  }
  update_actions:
    delete:
      field_settings:
        rendered_item:
          configuration:
            view_mode:
              entity:group:
                closed_group: {  }
                open_group: {  }
                public_group: {  }
                secret_group: {  }

search_api.index.social_groups:
  expected_config: {  }
  update_actions:
    delete:
      field_settings:
        rendered_item:
          configuration:
            view_mode:
              entity:group:
                closed_group: {  }
                open_group: {  }
                public_group: {  }
                secret_group: {  }

views.view.search_all:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            row:
              options:
                view_modes:
                  entity:group:
                    closed_group: {  }
                    open_group: {  }
                    public_group: {  }
                    secret_group: {  }

views.view.search_groups:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            row:
              options:
                view_modes:
                  entity:group:
                    closed_group: {  }
                    open_group: {  }
                    public_group: {  }
                    secret_group: {  }
