views.view.search_users:
  expected_config:
    display:
      default:
        display_options:
          access:
            options:
              perm: 'access users search'
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                perm: 'list user'
