views.view.search_groups:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              type:
                value:
                  min:
                  max:
                  value:
                expose:
    change:
      display:
        default:
          display_options:
            filters:
              type:
                operator: or
                plugin_id: search_api_options
                exposed: true
                expose:
                  operator_id: type_op
                  label: Type
                  description: ''
                  use_operator: false
                  operator: type_op
                  identifier: type
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                    anonymous: '0'
                    administrator: '0'
                    contentmanager: '0'
                    sitemanager: '0'
                  reduce: false
          cache_metadata:
            tags:
              - 'config:search_api.index.social_groups'
        page:
          cache_metadata:
            tags:
              - 'config:search_api.index.social_groups'
        page_no_value:
          cache_metadata:
            tags:
              - 'config:search_api.index.social_groups'