# This ensures that regardless of the selected sort option by a user, if
# there are ties in the sort there is a predictable and consistent
# tiebreaker.
search_api.index.social_all:
  expected_config: { }
  update_actions:
    add:
      field_settings:
        created:
          label: Created
          property_path: aggregated_field
          type: date
          configuration:
            type: union
            fields:
              - entity:group/created
              - entity:node/created
              - entity:profile/uid:entity:created
        label:
          label: Label
          property_path: aggregated_field
          type: text
          boost: !!float 21
          configuration:
            type: union
            fields:
              - entity:group/label
              - entity:node/title
      processor_settings:
        aggregated_field:
          weights:
            add_properties: 20
views.view.search_all:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              fallback_created:
                id: fallback_created
                table: search_api_index_social_all
                field: created
                relationship: none
                group_type: group
                admin_label: Fallback sort (Created Date)
                plugin_id: search_api
                order: DESC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
              fallback_label:
                id: fallback_label
                table: search_api_index_social_all
                field: label
                relationship: none
                group_type: group
                admin_label: Fallback sort (Label)
                plugin_id: search_api
                order: ASC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
views.view.search_content:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              fallback_created:
                id: fallback_created
                table: search_api_index_social_all
                field: node_created
                relationship: none
                group_type: group
                admin_label: Fallback sort (Created Date)
                plugin_id: search_api
                order: DESC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
              fallback_title:
                id: fallback_title
                table: search_api_index_social_all
                field: node_title
                relationship: none
                group_type: group
                admin_label: Fallback sort (Title)
                plugin_id: search_api
                order: ASC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
views.view.search_groups:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              fallback_created:
                id: fallback_created
                table: search_api_index_social_all
                field: group_created
                relationship: none
                group_type: group
                admin_label: Fallback sort (Created Date)
                plugin_id: search_api
                order: DESC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
              fallback_label:
                id: fallback_label
                table: search_api_index_social_all
                field: group_label
                relationship: none
                group_type: group
                admin_label: Fallback sort (Label)
                plugin_id: search_api
                order: ASC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false

views.view.search_users:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              fallback_created:
                id: fallback_created
                table: search_api_index_social_all
                field: profile_owner_created
                relationship: none
                group_type: group
                admin_label: 'Fallback sort (Owner » User » Created)'
                plugin_id: search_api
                order: DESC
                expose:
                  label: ''
                  field_identifier: ''
                exposed: false
