views.view.search_all:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              search_api_language:
                value:
                  und: und
