search_api.index.social_all:
  expected_config: {  }
  update_actions:
    add:
      processor_settings:
        entity_access_by_field:
          weights:
            preprocess_query: -30
search_api.index.social_content:
  expected_config: {  }
  update_actions:
    add:
      processor_settings:
        entity_access_by_field:
          weights:
            preprocess_query: -30
