views.view.comment:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            relationships:
              gid:
                table: group_relationship_field_data
