views.view.comment:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        module:
          - profile
      display:
        default:
          display_options:
            fields:
              field_profile_first_name:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                exclude: true
                field: field_profile_first_name
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: field_profile_first_name
                label: 'First name'
                multi_type: separator
                plugin_id: field
                relationship: profile
                separator: ', '
                settings:
                  link_to_entity: false
                table: profile__field_profile_first_name
                type: string
              field_profile_last_name:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                exclude: true
                field: field_profile_last_name
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: field_profile_last_name
                label: 'Last name'
                multi_type: separator
                plugin_id: field
                relationship: profile
                separator: ', '
                settings:
                  link_to_entity: false
                table: profile__field_profile_last_name
                type: string
            filters:
              combine:
                fields:
                  field_profile_first_name: field_profile_first_name
                  field_profile_last_name: field_profile_last_name
            relationships:
              profile:
                admin_label: Profile
                entity_type: user
                field: profile
                group_type: group
                id: profile
                plugin_id: standard
                relationship: uid
                required: false
                table: users_field_data
            sorts:
              changed:
                expose:
                  field_identifier: changed
        page_unapproved:
          display_options:
            fields:
              field_profile_first_name:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                exclude: true
                field: field_profile_first_name
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: field_profile_first_name
                label: 'First name'
                multi_type: separator
                plugin_id: field
                relationship: profile
                separator: ', '
                settings:
                  link_to_entity: false
                table: profile__field_profile_first_name
                type: string
              field_profile_last_name:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                exclude: true
                field: field_profile_last_name
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: field_profile_last_name
                label: 'Last name'
                multi_type: separator
                plugin_id: field
                relationship: profile
                separator: ', '
                settings:
                  link_to_entity: false
                table: profile__field_profile_last_name
                type: string
            filters:
              combine:
                fields:
                  field_profile_first_name: field_profile_first_name
                  field_profile_last_name: field_profile_last_name
    change:
      display:
        default:
          cache_metadata:
            tags:
              - 'config:field.storage.profile.field_profile_first_name'
              - 'config:field.storage.profile.field_profile_last_name'
          display_options:
            filters:
              combine:
                operator: allwords
        page_published:
          cache_metadata:
            tags:
              - 'config:field.storage.profile.field_profile_first_name'
              - 'config:field.storage.profile.field_profile_last_name'
        page_unapproved:
          cache_metadata:
            tags:
              - 'config:field.storage.profile.field_profile_first_name'
              - 'config:field.storage.profile.field_profile_last_name'
          display_options:
            filters:
              combine:
                operator: allwords
