signed_file_upload.settings:
  type: config_object
  label: 'Signed File Upload settings'
  mapping:
    expiry_time:
      type: string
      label: 'Expiry time'
      description: 'The length of time that an upload URL is valid. Should be a valid DateInterval string.'
