<?php

function install_example_install(): void {
  illegal_call();
}

function illegal_call(): string {
  $updateHelper = \Drupal::service('update_helper.updater');

  // Execute configuration update definitions with logging of success.
  $updateHelper->executeUpdate('install_example', 'install_example_update_8802');

  // Output logged messages to related channel of update execution.
  return $updateHelper->logger()->output();
}

function install_example_update_12000(): string {
  $updateHelper = \Drupal::service('update_helper.updater');

  // Execute configuration update definitions with logging of success.
  $updateHelper->executeUpdate('install_example', __FUNCTION__);

  // Output logged messages to related channel of update execution.
  return $updateHelper->logger()->output();
}
