dependencies:
  module:
    - contextual
items:
  user.role.contentmanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'access contextual links'
  user.role.sitemanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'access contextual links'
