<?php

/**
 * @file
 * Contains social_gdpr.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function social_gdpr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_gdpr module.
    case 'help.page.social_gdpr':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrate GDPR Inform and Consent module.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_gdpr_form_data_policy_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (\Drupal::routeMatch()->getRouteName() == 'social_gdpr.data_policy.add') {
    $form['actions']['submit']['#submit'][] = '_social_gdpr_data_policy_submit';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_gdpr_form_gdpr_consent_data_policy_agreement_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['fields'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['card', 'card__body', 'card__block'],
    ],
  ];

  $keys = ['data_policy'];

  if (isset($form['not_agree'])) {
    $form['not_agree']['#tag'] = 'small';
    $keys[] = 'not_agree';
  }

  foreach ($keys as $key) {
    $form['fields'][$key] = $form[$key];
    unset($form[$key]);
  }
}

/**
 * Implements hook_social_user_account_header_links().
 */
function social_gdpr_social_user_account_header_links() {
  $items = [];

  if (\Drupal::service('gdpr_consent.manager')->needConsent()) {
    $items['data_policy_agreement'] = [
      'title' => t('Data policy agreement'),
      'url' => Url::fromRoute('gdpr_consent.data_policy.agreement'),
      'after' => 'edit_profile',
    ];
  }

  return $items;
}

/**
 * Form submit redirect for data policy.
 *
 * @param array $form
 *   Data policy form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state interface.
 */
function _social_gdpr_data_policy_submit(array $form, FormStateInterface $form_state) {
  $form_state->setRedirect('social_gdpr.data_policy.revisions');
}
