social_analytics.settings:
  type: config_object
  label: 'Social Analytics settings'
  mapping:
    individual_metrics_preference_visibility_enabled:
      type: boolean
      label: 'Show individual metrics preference toggle in user account settings'
    individual_metrics_show_by_default:
      type: boolean
      label: 'Show user names in individual metrics by default'
