core.entity_view_display.node.landing_page.default:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.landing_page.featured:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.landing_page.teaser:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }
