core.entity_view_display.profile.profile.featured:
  expected_config:
    content:
      field_profile_image:
        settings:
          image_style: social_large
    hidden:
      field_profile_function: true
      field_profile_organization: true
  update_actions:
    add:
      content:
        field_profile_function:
          label: hidden
          region: content
          settings:
            link_to_entity: false
          third_party_settings: {  }
          type: string
          weight: 3
        field_profile_organization:
          label: hidden
          region: content
          settings:
            link_to_entity: false
          third_party_settings: {  }
          type: string
          weight: 4
      hidden:
        field_profile_bio: true
        field_profile_birth_year: true
        field_profile_education: true
        field_profile_present_location: true
        field_profile_projects: true
        field_profile_sdg_expertise: true
        field_profile_skype: true
        field_profile_social_networks: true
        field_profile_undp_expertise: true
        search_api_excerpt: true
    change:
      content:
        field_profile_image:
          settings:
            image_style: social_x_large
      hidden:
        field_profile_gender: true
        field_profile_languages: true
        field_profile_name: true
        field_profile_organisation: true
        field_profile_other_expertise: true
    delete:
      hidden:
        field_profile_function: true
        field_profile_organization: true
