field.field.paragraph.block.field_block_reference:
  expected_config: { }
  update_actions:
    change:
      settings:
        selection: blocks
        selection_settings:
          plugin_ids:
            'views_block:activity_stream-block_stream_homepage': 'views_block:activity_stream-block_stream_homepage'
            'views_block:activity_stream-block_stream_homepage_without_post': 'views_block:activity_stream-block_stream_homepage_without_post'
            'views_block:community_activities-block_stream_landing_with_post': 'views_block:community_activities-block_stream_landing_with_post'
            'views_block:community_activities-block_stream_landing': 'views_block:community_activities-block_stream_landing'
field.field.paragraph.block.field_block_reference_secondary:
  expected_config: { }
  update_actions:
    change:
      settings:
        selection: blocks
        selection_settings:
          plugin_ids:
            'views_block:upcoming_events-block_community_events': 'views_block:upcoming_events-block_community_events'
            'views_block:latest_topics-block_latest_topics': 'views_block:latest_topics-block_latest_topics'
            'views_block:newest_groups-block_newest_groups': 'views_block:newest_groups-block_newest_groups'
            'views_block:newest_users-block_newest_users': 'views_block:newest_users-block_newest_users'
            activity_overview_block: activity_overview_block
