field.field.paragraph.block.field_block_title:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.block.field_block_link:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.button.field_button_link_an:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.button.field_button_link_lu:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.hero.field_hero_image:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.hero.field_hero_subtitle:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.hero.field_hero_title:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.hero_small.field_hero_small_image:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.hero_small.field_hero_small_subtitle:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.hero_small.field_hero_small_title:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.introduction.field_introduction_text:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.introduction.field_introduction_title:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.introduction.field_introduction_link_an:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.introduction.field_introduction_link_lu:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.accordion.field_accord_title:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.accordion.field_accord_description:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.accordion_item.field_accord_item_title:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.accordion_item.field_accord_item_description:
  expected_config:
    translatable: FALSE
  update_actions:
    change:
      translatable: TRUE
