core.entity_form_display.node.landing_page.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_content:
            format_settings:
              label: Title
            label: Title
          group_sections:
            format_settings:
              label: Sections
            label: Sections
          group_settings:
            label: Settings
