views.view.albums:
  expected_config: {  }
  update_actions:
    change:
      display:
        page_group_albums_overview:
          display_options:
            access:
              options:
                group_permission: 'view group_node:album relationship'
