views.view.albums:
  expected_config: {  }
  update_actions:
    change:
      display:
        embed_album_overview:
          display_options:
            pager:
              options:
                id: 0
