core.entity_form_display.node.album.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_album_visibility:
            label: 'Access permissions'
          group_title:
            label: 'Basic information'
          group_album_settings:
            label: 'Additional information'
          group_settings:
            label: Settings
