views.view.albums:
  expected_config: {  }
  update_actions:
    change:
      display:
        page_group_albums_overview:
          display_options:
            arguments:
              gid:
                table: group_relationship_field_data
