social_topic.settings:
  type: config_object
  label: 'Social Topic Settings'
  mapping:
    social_topic_type_select_changer:
      type: integer
      label: 'The number of terms at which point to topic type chooser will switch from radio buttons to dropdown.'
