core.entity_form_display.profile.profile.default:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - field.field.profile.profile.field_profile_alt_contact
          - field.field.profile.profile.field_profile_end_date_ooo
          - field.field.profile.profile.field_profile_message_ooo
          - field.field.profile.profile.field_profile_start_date_ooo
      third_part_settings:
        field_group:
          group_out_of_office:
            children:
              - field_profile_start_date_ooo
              - field_profile_end_date_ooo
              - field_profile_message_ooo
              - field_profile_alt_contact
            parent_name: ''
            weight: 20
            format_type: fieldset
            region: hidden
            format_settings:
              show_empty_fields: false
              id: ''
              classes: ''
              description: ''
              required_fields: true
            label: 'Out of office'
      content:
        field_profile_alt_contact:
          weight: 29
          settings:
            match_operator: CONTAINS
            match_limit: 10
            size: 60
            placeholder: ''
          third_party_settings: { }
          type: entity_reference_autocomplete
          region: content
        field_profile_end_date_ooo:
          weight: 27
          settings: { }
          third_party_settings: { }
          type: datetime_default
          region: content
        field_profile_message_ooo:
          weight: 28
          settings:
            rows: 9
            summary_rows: 3
            placeholder: ''
            show_summary: false
          third_party_settings: { }
          type: text_textarea_with_summary
          region: content
        field_profile_start_date_ooo:
          weight: 26
          settings: { }
          third_party_settings: { }
          type: datetime_default
          region: content
