core.entity_form_display.group.secret_group.default:
  expected_config: {  }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_content:
            label: 'Basic information'
          group_settings:
            children:
              - path
            format_type: details
            format_settings:
              classes: social-collapsible-fieldset
              open: false
            weight: 10
