core.entity_view_display.group.secret_group.small_teaser:
  expected_config:
    content:
      label:
        weight: -5
    hidden:
      field_group_image: true
  update_actions:
    add:
      content:
        field_group_image:
          label: hidden
          region: content
          settings:
            image_link: content
            image_style: social_medium
          third_party_settings: {  }
          type: image
          weight: 0
    change:
      content:
        label:
          weight: 1
    delete:
      hidden:
        field_group_image: true
