core.entity_form_display.node.page.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_page_content:
            label: 'Basic information'
          group_attachments:
            label: 'Additional information'
          group_page_visibility:
            label: 'Access permissions'
          group_settings:
            label: Settings
