node.type.page:
  expected_config:
    name: 'Basic page'
    description: 'Use basic pages for your static content, such as an ''About us'' page.'
  update_actions:
    change:
      name: 'Page'
      description: 'Use pages for your static content, such as an ''About us'' page.'