core.entity_view_display.node.page.activity:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.activity_comment:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.default:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.hero:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.search_index:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.small_teaser:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.teaser:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }
