core.entity_view_display.node.page.hero:
  expected_config:
    content:
      field_page_image:
        label: above
  update_actions:
    change:
      content:
        field_page_image:
          label: hidden
