views.view.courses_overview:
  expected_config:
    display:
      default:
        display_options:
          access:
            options:
              perm: 'use courses feature'
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                perm: 'access course overview'
