views.view.courses_user:
  expected_config:
    display:
      default:
        display_options:
          access:
            options:
              perm: 'use courses feature'
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                perm: 'access user profiles'
