"""
A type of content on Open Social which allows users to organize, discuss topics, and join activities.
"""
type Event implements Node & Commentable & ContentTaggable {
  """
  The unique identifier for the event.
  """
  id: ID!
  """
  The display title of the event.
  """
  title: String!
  """
  The author of the event.
  """
  author: Actor
  """
  A hero image for the event.
  """
  heroImage: Image
  """
  The content tags this event is tagged with grouped by the categories they belong in.
  Each event is classified with content tags to make it clear what this event is about.
  """
  contentTagCategories: [ContentTaggableSelectedTagCategories!]!
  """
  The message of the event as rendered HTML.
  """
  bodyHtml: Html!
  """
  The formatted start date of the event.
  """
  startDate: DateTime!
  """
  The formatted end date of the event.

  When a event is not limited to a specific time period the end date may be NULL.
  """
  endDate: DateTime
  """
  The location of the event as plain text.
  """
  location: String
  """
  The type of the event.
  """
  eventType: EventType
  """
  List of event managers.

  Managers are people who have the rights to edit the event itself.
  """
  managers(
    """Returns the elements that come after the specified cursor."""
    after: Cursor
    """Returns the elements that come before the specified cursor."""
    before: Cursor
    """Returns up to the first `n` elements from the list."""
    first: Int
    """Returns up to the last `n` elements from the list."""
    last: Int
    """Reverse the order of the underlying list."""
    reverse: Boolean = false
  ): EventManagerConnection!
  """
  List of event comments.
  """
  comments(
    """Returns the elements that come after the specified cursor."""
    after: Cursor
    """Returns the elements that come before the specified cursor."""
    before: Cursor
    """Returns up to the first `n` elements from the list."""
    first: Int
    """Returns up to the last `n` elements from the list."""
    last: Int
    """Reverse the order of the underlying list."""
    reverse: Boolean = false
    """Sort the underlying list by the given key."""
    sortKey: CommentSortKeys = CREATED_AT
  ): CommentConnection!
  """
  The url to the event.
  """
  url: Url!
  """
  When the event was created.
  """
  created: DateTime!
}

type EventEdge implements Edge {
  cursor: Cursor!
  node: Event!
}

type EventConnection implements Connection {
  edges: [EventEdge!]!
  nodes: [Event!]!
  pageInfo: PageInfo!
}

"""
The set of valid sort keys for the event query.
"""
enum EventSortKeys {
  """Sort by event creation date"""
  CREATED_AT
}

type EventManagerEdge implements Edge {
  cursor: Cursor!
  node: User!
}

"""
Pagination info for moderators of a discussion.
"""
type EventManagerConnection implements Connection {
  edges: [EventManagerEdge!]!
  nodes: [User!]!
  pageInfo: PageInfo!
}

"""
The type of an event.
Each event is tagged with an event type to make it clear what this event is about.
An event is assigned an event type defined by site managers.
"""
type EventType implements Node {
  """
  The unique identifier for the event type.
  """
  id: ID!
  """
  The human-readable name of the event type.
  """
  label: String
}

"""
Input for creating a new event.
"""
input CreateEventInput {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: UUIDv4
  """
  The type of the event.
  The ID of the event type as provided by Query.eventTypes.
  If omitted, the event has no event type.
  """
  type: ID
  """
  The display title of the event.
  """
  title: String!
  """
  The visibility of the event determines what users can view this event.
  """
  visibility: ContentVisibility!
  """
  The body of the event in Open Social Rich Text JSON Exchange format.
  """
  body: RichTextJSON!
  """
  The unix timestamp start date of the event.
  """
  startDate: Timestamp!
  """
  The unix timestamp end date of the event.
  """
  endDate: Timestamp!
  """
  The location of the event as plain text.
  """
  location: String
  """
  The address of the event.
  """
  address: AddressInput
}

"""
Payload returned after creating an event.
"""
type CreateEventPayload {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: UUIDv4
  """
  Errors that were encountered while performing the mutation.
  NULL or an array of violations.
  """
  errors: [Violation!]
  """
  The created event.
  """
  event: Event
}

input UpdateEventInput {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: UUIDv4
  """
  The event being edited.
  """
  id: ID!
  """
  The type of the event.
  The ID of the event type as provided by Query.eventTypes.
  If omitted, the type remains unchanged. If null, the event type is cleared.
  """
  type: ID
  """
  The display title of the event.
  If omitted, the title remains unchanged.
  """
  title: String
  """
  The visibility of the event determines what users can view this event.
  If omitted, visibility remains unchanged.
  """
  visibility: ContentVisibility
  """
  The body of the event in Open Social Rich Text JSON Exchange format.
  If omitted, the body remains unchanged.
  """
  body: RichTextJSON
  """
  The unix timestamp start date of the event.
  If omitted, start date remains unchanged.
  """
  startDate: Timestamp
  """
  The unix timestamp end date of the event.
  If omitted, end date remains unchanged.
  """
  endDate: Timestamp
  """
  The location of the event as plain text, this is not the address field, see "address".
  If omitted, event location remains unchanged. If null, the location is cleared.
  """
  location: String
}

type UpdateEventPayload {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: UUIDv4
  """
  Errors that were encountered while performing the mutation.
  NULL or an array of violations.
  """
  errors: [Violation!]

  """
  The updated event.
  """
  event: Event
}

"""
Input for deleting an existing event.
"""
input DeleteEventInput {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: UUIDv4
  """
  The event being deleted.
  """
  id: ID!
}

"""
Payload returned after deleting an event.
"""
type DeleteEventPayload {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: UUIDv4
  """
  Errors that were encountered while performing the mutation.
  NULL or an array of violations.
  """
  errors: [Violation!]
}
