<?php

/**
 * @file
 * Contains dropdown.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html as HtmlUtility;

/**
 * Implements hook_help().
 */
function dropdown_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dropdown module.
    case 'help.page.dropdown':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dropdown field.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dropdown_theme() {
  $items = [
    'dropdown' => [
      'render element' => 'element',
    ],
  ];
  return $items;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dropdown_theme_suggestions_dropdown_alter(array &$suggestions, array $variables) {
  // Field name consists of field_machine_name[0] with a potential array added.
  // we want to split this.
  if (!empty($variables['element']['#name'])) {
    $name_parts = explode('[', $variables['element']['#name']);
    $field_name = $name_parts[0];

    $suggestions[] = 'dropdown__' . $field_name;
  }
  // Add a new suggestion for those who use the slick option.
  if ($variables['element']['#use_slick']) {
    $suggestions[] = 'dropdown__slick';
    if (!empty($field_name)) {
      $suggestions[] = 'dropdown__' . $field_name . '__slick';
    }
  }
}

/**
 * Prepares variables for dropdown templates.
 *
 * Default template: dropdown.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #title, #value, #options, #description, #required,
 *     #attributes, #children.
 */
function template_preprocess_dropdown(array &$variables) {
  $element = $variables['element'];
  $variables['attributes'] = [];
  if (isset($element['#id'])) {
    $variables['attributes']['id'] = $element['#id'];
  }
  if (isset($element['#attributes']['title'])) {
    $variables['attributes']['title'] = $element['#attributes']['title'];
  }
  if (!empty($variables['element']['#name'])) {
    $name_parts = explode('[', $variables['element']['#name']);
    $field_name = $name_parts[0];
    $variables['attributes']['class'] = $field_name;
  }

  $items = [];
  foreach ($element as $key => $el) {
    if (is_numeric($key) && isset($el['#type']) && $el['#type'] === 'radio') {
      $items[$key] = $el;
      if ($el['#return_value'] === $el['#value']) {
        // @TODO Do we need to check for default_value also
        $selected = HtmlUtility::escape($el['#title']);
        $active = $key;
      }
    }
    if (is_array($el) && isset($el['#type']) && $el['#type'] === 'radio') {
      $items[$key] = $el;
      // Set public as default.
      if ($el['#return_value'] === $el['#value']) {
        $selected = HtmlUtility::escape($el['#title']);
        $active = $key;
      }
    }
  }

  if (isset($element['#edit_mode'])) {
    $variables['edit_mode'] = $element['#edit_mode'];
  }
  $variables['items'] = $items;
  $variables['label'] = HtmlUtility::escape($element['#title']);
  $variables['selected'] = isset($selected) ? $selected : $variables['label'];
  $variables['active'] = isset($active) ? $active : '';
  $variables['children'] = $element['#children'];
}

/**
 * Implements template_preprocess_form_element().
 */
function dropdown_preprocess_form_element(&$variables) {
  // If we have added the is_dropdown tag to our radio form element,
  // also pass it along to our label so our label can also render correctly
  // #is_dropdown is rendered as part of processDropdown, so we know for sure it
  // is our custom element.
  if ($variables['element']['#type'] === 'radio' &&
    $variables['element']['#is_dropdown'] &&
    !empty($variables['label'])) {
    $variables['label']['#is_dropdown'] = TRUE;
  }
}
