social_tagging.settings:
  type: config_object
  label: 'Social Tagging Settings'
  mapping:
    enable_content_tagging:
      type: boolean
      label: 'Determines whether content tagging is enabled for users.'
    allow_category_split:
      type: boolean
      label: 'Determines whether the top level taxonomy items are considered categories for tagging.'
    use_category_parent:
      type: boolean
      label: 'Determine if the parent of categories will be used with children tags.'
    tag_node_type_book:
      type: boolean
      label: 'Determines whether the book node type has tagging enabled.'
    tag_node_type_event:
      type: boolean
      label: 'Determines whether the event node type has tagging enabled.'
    tag_node_type_landing_page:
      type: boolean
      label: 'Determines whether the landing page node type has tagging enabled.'
    tag_node_type_page:
      type: boolean
      label: 'Determines whether the page node type has tagging enabled.'
    tag_node_type_topic:
      type: boolean
      label: 'Determines whether the topic node type has tagging enabled.'
