dependencies:
  modules:
    - metatag_open_graph
items:
  metatag.settings:
    expected_config:
      entity_type_groups: { }
    update_actions:
      add:
        entity_type_groups:
          node:
            topic:
              open_graph: open_graph
