dependencies:
  module:
    - social_profile
items:
  views.view.topics:
    expected_config: {  }
    update_actions:
      delete:
        display:
          default:
            display_options:
              access: { }
      add:
        display:
          default:
            display_options:
              access:
                type: social_profile_pages_access
                options: { }
