dependencies:
  module:
    - taxonomy_access_fix
  config:
    - user.role.sitemanager
items:
  user.role.sitemanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view terms in topic_types'
          - 'view term names in topic_types'
          - 'select terms in topic_types'
