social_magic_login.settings:
  type: config_object
  label: 'Social Magic Login Settings'
  mapping:
    show_used_message:
      type: boolean
      label: "Whether to show a message to the user when they've used a magic login link."
