<?php

/**
 * @file
 * Default route for groups.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group\Entity\GroupType;
use Symfony\Component\Routing\Exception\RouteNotFoundException;

/**
 * Implements hook_form_alter().
 */
function social_group_default_route_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms = [];
  foreach (_social_group_default_route_group_types() as $type) {
    $forms[] = 'group_' . $type . '_edit_form';
    $forms[] = 'group_' . $type . '_add_form';
  }

  // Check if this group type is supported.
  if (in_array($form_id, $forms, TRUE)) {
    /** @var \Drupal\social_group_default_route\SocialGroupDefaultRouteRedirectService $redirect_service */
    $redirect_service = \Drupal::service('social_group_default_route.redirect_service');

    // Get the form entity.
    $group = $form_state->getFormObject()->getEntity();
    // Fetch the rotes for member and non-member.
    $member_routes = $redirect_service->getMemberRoutes($group);
    $non_member_routes = $redirect_service->getNonMemberRoutes($group);

    // Add a (hidden) card for the tabs.
    $form['tab_settings'] = [
      '#type' => 'details',
      '#title' => t('Tab Management'),
      '#group' => 'group_settings',
      '#weight' => '3',
    ];

    // Define options for member.
    $member_options = _social_group_default_route_groups_get_options($member_routes);
    // Define options for non-member.
    $non_member_options = _social_group_default_route_groups_get_options($non_member_routes);
    // Define a default route for members.
    $default_route = $group ? $redirect_service->getDefaultMemberRoute($group) : '';
    // Define a default route for non-members.
    $default_route_an = $group ? $redirect_service->getDefaultNonMemberRoute($group) : '';
    // The default route field.
    $form['tab_settings']['default_route'] = [
      '#type' => 'select',
      '#title' => t('Group members landing tab'),
      '#default_value' => $default_route,
      '#options' => $member_options,
    ];

    // The default route field.
    $form['tab_settings']['default_route_an'] = [
      '#type' => 'select',
      '#title' => t('Non members landing tab'),
      '#default_value' => $default_route_an,
      '#options' => $non_member_options,
    ];
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function social_group_default_route_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Check if we're dealing with the group entity.
  if ($entity_type->id() === 'group') {

    // Add a default_route field.
    $fields['default_route'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Landing tab for members'))
      ->setDescription(t('The route (tab) a member lands on when going to a group.'))
      ->setRequired(FALSE)
      ->setTranslatable(FALSE)
      ->setSettings([
        'default_value' => '',
        'max_length' => 255,
      ]);

    // Add a default_route field.
    $fields['default_route_an'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Landing tab for non-members'))
      ->setDescription(t('The route (tab) a non-member lands on when going to a group.'))
      ->setRequired(FALSE)
      ->setTranslatable(FALSE)
      ->setSettings([
        'default_value' => '',
        'max_length' => 255,
      ]);
  }

  return $fields;
}

/**
 * Fetch all available group types.
 *
 * @return array
 *   The group types.
 */
function _social_group_default_route_group_types() {
  $types = &drupal_static(__FUNCTION__);

  if (!isset($types)) {
    $types = [];
    /** @var \Drupal\group\Entity\GroupType $group_type */
    foreach (GroupType::loadMultiple() as $group_type) {
      // Add to the array.
      $types[] = $group_type->id();
    }
    // Allow other modules to change the group types.
    Drupal::moduleHandler()->alter('social_group_default_route_types', $types);
  }

  return $types;
}

/**
 * Get tab options.
 *
 * @param array $routes
 *   The routes.
 *
 * @return array
 *   The options.
 */
function _social_group_default_route_groups_get_options(array $routes): array {
  /** @var \Drupal\Core\Routing\RouteProviderInterface $route_provider */
  $route_provider = \Drupal::service('router.route_provider');
  // Define options for member.
  $options = [];
  // Load the members tabs.
  foreach ($routes as $route => $title) {
    try {
      $route_object = $route_provider->getRouteByName($route);
      $options[$route] = $title;
    }
    catch (RouteNotFoundException $e) {
      // Skip if route isn't exist.
      continue;
    }
  }

  return $options;
}
