social_tagging.settings:
  type: config_object
  label: 'Social Tagging Settings'
  mapping:
    enable_content_tagging:
      type: boolean
      label: 'Determines whether content tagging is enabled for users.'
# @todo: Add use_and_condition
