message.template.member_added_by_event_organiser:
  expected_config: {  }
  update_actions:
    change:
      label: 'An organizer added me to an event'
      description: 'An organizer added me to an event'
