views.view.event_manage_enrollments:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              langcode: {  }
