views.view.event_manage_enrollments:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
views.view.managers:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
