dependencies:
  config:
    - group.type.course_advanced
    - group.type.course_basic
  module:
    - social_group
items:
  views.view.groups:
    expected_config: { }
    update_actions:
      add:
        display:
          default:
            display_options:
              filters:
                type:
                  id: type
                  table: groups_field_data
                  field: type
                  relationship: none
                  group_type: group
                  admin_label: ''
                  entity_type: group
                  entity_field: type
                  plugin_id: bundle
                  operator: 'not in'
                  value:
                    course_advanced: course_advanced
                    course_basic: course_basic
                  group: 1
                  exposed: false
                  expose:
                    operator_id: ''
                    label: ''
                    description: ''
                    use_operator: false
                    operator: ''
                    operator_limit_selection: false
                    operator_list: { }
                    identifier: ''
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                    reduce: false
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
          page_user_groups:
            display_options:
              filters:
                type:
                  id: type
                  table: groups_field_data
                  field: type
                  relationship: none
                  group_type: group
                  admin_label: ''
                  entity_type: group
                  entity_field: type
                  plugin_id: bundle
                  operator: 'not in'
                  value:
                    course_advanced: course_advanced
                    course_basic: course_basic
                  group: 1
                  exposed: false
                  expose:
                    operator_id: ''
                    label: ''
                    description: ''
                    use_operator: false
                    operator: ''
                    operator_limit_selection: false
                    operator_list: { }
                    identifier: ''
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                    reduce: false
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
  views.view.newest_groups:
    expected_config: { }
    update_actions:
      add:
        display:
          default:
            display_options:
              filters:
                type:
                  id: type
                  table: groups_field_data
                  field: type
                  relationship: none
                  group_type: group
                  admin_label: ''
                  entity_type: group
                  entity_field: type
                  plugin_id: bundle
                  operator: 'not in'
                  value:
                    course_advanced: course_advanced
                    course_basic: course_basic
                  group: 1
                  exposed: false
                  expose:
                    operator_id: ''
                    label: ''
                    description: ''
                    use_operator: false
                    operator: ''
                    operator_limit_selection: false
                    operator_list: { }
                    identifier: ''
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                    reduce: false
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
          page_all_groups:
            display_options:
              filters:
                type:
                  id: type
                  table: groups_field_data
                  field: type
                  relationship: none
                  group_type: group
                  admin_label: ''
                  entity_type: group
                  entity_field: type
                  plugin_id: bundle
                  operator: 'not in'
                  value:
                    course_advanced: course_advanced
                    course_basic: course_basic
                  group: 1
                  exposed: false
                  expose:
                    operator_id: ''
                    label: ''
                    description: ''
                    use_operator: false
                    operator: ''
                    operator_limit_selection: false
                    operator_list: { }
                    identifier: ''
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                    reduce: false
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
