<?php

/**
 * @file
 * Contains ginvite.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Url;
use Drupal\ginvite\Plugin\GroupContentEnabler\GroupInvitation;
use Drupal\group\Entity\GroupContentInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for group_content_form.
 */
function ginvite_form_group_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\ContentEntityFormInterface $formObject */
  $formObject = $form_state->getFormObject();
  /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
  $group_content = $formObject->getEntity();
  $content_plugin = $group_content->getContentPlugin();
  if ($content_plugin->getPluginId() === 'group_invitation') {
    $form += [
      // Reference to Anonymous user by default.
      'entity_id' => [
        '#type' => 'value',
        '#value' => 0,
      ],
    ];
  }
}

/**
 * Sends email when invitation created for not registered user.
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function ginvite_group_content_insert(GroupContentInterface $group_content) {
  $type = $group_content->getContentPlugin()->getPluginId();
  $messenger = \Drupal::messenger();

  if ($type == 'group_invitation') {
    $mail = $group_content->get('invitee_mail')->getString();

    $mailManager = \Drupal::service('plugin.manager.mail');
    $from = $group_content->get('uid')->first()->get('entity')->getTarget()->getValue();
    $group = $group_content->get('gid')->first()->get('entity')->getTarget()->getValue();
    $params = [
      'user' => $from,
      'group' => $group,
      'group_content' => $group_content,
      'existing_user' => FALSE,
    ];
    $langcode = $from->getPreferredLangcode();

    // Load plugin configuration.
    $group_plugin_collection = \Drupal::service('plugin.manager.group_content_enabler')->getInstalled($group->getGroupType());
    $group_invite_config = $group_plugin_collection->getConfiguration()['group_invitation'];

    if ($invitee = user_load_by_mail($mail)) {
      $group_content->set('entity_id', $invitee);

      // Check if we should send a email to existing user.
      if ($group_invite_config['send_email_existing_users']) {
        $params['existing_user'] = TRUE;
        $mailManager->mail('ginvite', 'invite', $mail, $langcode, $params, NULL, TRUE);
        $messenger->addMessage(t('Invite sent to %invitee', ['%invitee' => $invitee->getDisplayName()]));
      }
      else {
        $messenger->addMessage(t('Invitation has been created.'));
      }
    }
    else {
      $mailManager->mail('ginvite', 'invite', $mail, $langcode, $params, NULL, TRUE);
      $messenger->addMessage(t('Invite sent to %mail', ['%mail' => $mail]));
    }

    $group_content->set('invitation_status', GroupInvitation::INVITATION_PENDING);
    $group_content->save();
  }
  // If new membership is created, check related invitation exists.
  elseif ($type == 'group_membership') {
    $properties = [
      'entity_id' => $group_content->getEntity()->id(),
      'gid' => $group_content->getGroup()->id(),
      'invitation_status' => GroupInvitation::INVITATION_PENDING,
    ];

    $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);
    if (!empty($invitations)) {
      foreach ($invitations as $invitation) {
        // Mark invitation as accepted.
        $invitation->getGroupContent()->set('invitation_status', GroupInvitation::INVITATION_ACCEPTED)->save();
      }

      $messenger->addMessage(t('You have accepted the invitation.'));
    }
  }
}

/**
 * Implements hook_mail().
 *
 * This mail is sent when people who do not have an account on the website yet
 * are invited into a group. It is sent in the language the inviter was using
 * the website in.
 *
 * @see ginvite_group_content_insert()
 */
function ginvite_mail($key, &$message, $params) {
  if ($key == 'invite') {

    $token_service = \Drupal::token();
    $language_manager = \Drupal::languageManager();

    // Get email from GroupInvitation.
    $group = $params['group'];
    $langcode = $message['langcode'];

    $language = $language_manager->getLanguage($langcode);
    $original_language = $language_manager->getConfigOverrideLanguage();
    $language_manager->setConfigOverrideLanguage($language);

    // Load plugin configuration.
    $group_plugin_collection = \Drupal::service('plugin.manager.group_content_enabler')->getInstalled($group->getGroupType());
    $group_invite_config = $group_plugin_collection->getConfiguration()['group_invitation'];

    $invitation_subject = (!$params['existing_user']) ? $group_invite_config["invitation_subject"] : $group_invite_config["existing_user_invitation_subject"];
    $invitation_body = (!$params['existing_user']) ? $group_invite_config["invitation_body"] : $group_invite_config["existing_user_invitation_body"];

    unset($params['existing_user']);

    $body = $token_service->replace($invitation_body, $params);
    $subject = $token_service->replace($invitation_subject, $params);

    $message['subject'] = $subject;
    $message['body'][] = $body;

    $language_manager->setConfigOverrideLanguage($original_language);

  }
}

/**
 * Set referenced entity to Invitation when invited user registered.
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function ginvite_user_insert(UserInterface $user) {
  $properties = [
    'invitee_mail' => $user->getEmail(),
    'invitation_status' => GroupInvitation::INVITATION_PENDING,
  ];

  $invitations = \Drupal::service('ginvite.invitation_loader')->loadByProperties($properties);

  foreach ($invitations as $invitation) {
    $group_content = $invitation->getGroupContent();
    $group_content->set('entity_id', $user);
    $group_content->save();
  }
}

/**
 * Add Constraint to prevent duplicated invitations.
 *
 * Implements hook_entity_type_alter().
 */
function ginvite_entity_type_alter(array &$entity_types) {
  $group_content = $entity_types['group_content'];
  $group_content->addConstraint('PreventDuplicated', []);
}

/**
 * Add token to register url.
 *
 * Implements hook_token_info().
 */
function ginvite_token_info() {
  $tokens['register_link'] = [
    'name' => t('Register Link'),
    'description' => t('Url to register page with prefilled email address.'),
  ];
  $tokens['my_invitations_link'] = [
    'name' => t('My Invitations Link'),
    'description' => t('Url to user list of invitations.'),
  ];

  return [
    'tokens' => ['group_content' => $tokens],
  ];
}

/**
 * Implements hook_tokens().
 */
function ginvite_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'group_content' && !empty($data[$type])) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group_content = $data['group_content'];

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'register_link':
          $mail = $group_content->get('invitee_mail')->getString();
          $mail_encoded = str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($mail));
          $register_link = Url::fromRoute('user.register', ['invitee_mail' => $mail_encoded], ['absolute' => TRUE])->toString();
          $replacements[$original] = $register_link;
          break;

        case 'my_invitations_link':
          $user = user_load_by_mail($group_content->get('invitee_mail')->getString());
          $my_invitations_link = Url::fromRoute('view.my_invitations.page_1', ['user' => $user->id()], ['absolute' => TRUE])->toString();
          $replacements[$original] = $my_invitations_link;
      }
    }
  }
  return $replacements;
}

/**
 * Prefill email address when user comes from ginvite registrarion url.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function ginvite_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($_GET["invitee_mail"])) {
    $invitee_mail = $_GET["invitee_mail"];
    $invitee_mail = base64_decode(str_replace(['-', '_'], ['+', '/'], $invitee_mail));
    if (\Drupal::service('email.validator')->isValid($invitee_mail)) {
      $form["account"]["mail"]["#default_value"] = $invitee_mail;
      $form["account"]["mail"]["#disabled"] = TRUE;
    }
  }
}
