<?php
/**
 * @file
 * Install, update and uninstall functions for the social_search module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of social_search.
 */
function social_search_install() {

  // Set some default permissions.
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, array(
    'access content search',
    'access users search',
  ));

}
