<?php
/**
 * @file
 * Install, update and uninstall functions for the activity_basics module.
 */

/**
 * Install token module.
 */
function activity_basics_update_8101(&$sandbox) {

  $modules = array(
    'token',
  );
  \Drupal::service('module_installer')->install($modules);

}

/**
 * Install activity_send_email module.
 */
function social_group_update_8102() {

  $modules = array(
    'activity_send_email',
  );
  \Drupal::service('module_installer')->install($modules);

}
