social_profile_fields.settings:
  type: config_object
  label: 'Social Profile Fields settings'
  mapping:
    profile_profile_field_profile_nick_name:
      type: boolean
      label: 'Show nickname field'
    profile_profile_field_profile_address:
      type: boolean
      label: 'Show address field'
    profile_profile_field_profile_banner_image:
      type: boolean
      label: 'Show banner image field'
    profile_profile_field_profile_expertise:
      type: boolean
      label: 'Show expertise field'
    profile_profile_field_profile_first_name:
      type: boolean
      label: 'Show first name field'
    profile_profile_field_profile_image:
      type: boolean
      label: 'Show profile image field'
    profile_profile_field_profile_interests:
      type: boolean
      label: 'Show interests field'
    profile_profile_field_profile_last_name:
      type: boolean
      label: 'Show last name field'
    profile_profile_field_profile_nationality:
      type: boolean
      label: 'Show nationality field'
    profile_profile_field_profile_organization_tag:
      type: boolean
      label: 'Show organization tag field'
    profile_profile_field_profile_phone_number:
      type: boolean
      label: 'Show phone number field'
    profile_profile_field_profile_profile_tag:
      type: boolean
      label: 'Show profile tag field'
    profile_profile_field_profile_self_introduction:
      type: boolean
      label: 'Show self introduction field'
    profile_profile_field_profile_show_email:
      type: ignore
      label: 'Show email field'
    profile_profile_field_profile_summary:
      type: boolean
      label: 'Show summary field'
    profile_address_field_city:
      type: boolean
      label: 'Show city address field'
    profile_address_field_address:
      type: boolean
      label: 'Show address field'
    profile_address_field_postalcode:
      type: boolean
      label: 'Show postal code address field'
    profile_address_field_administrative_area:
      type: boolean
      label: 'Show administrative area address field'
    profile_profile_field_group_affiliation:
      type: boolean
      label: 'Show group affiliation field'
    profile_profile_field_other_affiliations:
      type: boolean
      label: 'Show other affiliations field'
    nickname_unique_validation:
      type: boolean
      label: 'Enforce unique nickname validation'
