editor.editor.basic_html:
  expected_config:
    editor: ckeditor5
    settings:
      plugins:
        ckeditor5_heading:
          enabled_headings:
            - heading2
            - heading3
            - heading4
            - heading5
            - heading6
        ckeditor5_imageResize:
          allow_resize: true
        ckeditor5_list:
          reversed: false
          startIndex: true
        ckeditor5_sourceEditing:
          allowed_tags:
            - '<cite>'
            - '<dl>'
            - '<dt>'
            - '<dd>'
            - '<span>'
            - '<mention id>'
            - '<a hreflang target>'
            - '<blockquote cite>'
            - '<ul type>'
            - '<ol type>'
            - '<h2 id>'
            - '<h3 id>'
            - '<h4 id>'
            - '<h5 id>'
            - '<h6 id>'
            - '<table cellspacing cellpadding border>'
            - '<th scope>'
        editor_advanced_link_link:
          enabled_attributes:
            - class
            - id
            - rel
            - target
            - title
      toolbar:
        items:
          - bold
          - italic
          - '|'
          - link
          - '|'
          - bulletedList
          - numberedList
          - '|'
          - blockQuote
          - drupalInsertImage
          - '|'
          - heading
          - '|'
          - sourceEditing
          - '|'
          - insertTable
          - '|'
          - code
  update_actions:
    delete:
      settings:
        plugins:
          ckeditor5_heading:
            enabled_headings:
              - heading2
              - heading3
              - heading4
              - heading5
              - heading6
          ckeditor5_imageResize:
            allow_resize: true
          ckeditor5_list:
            reversed: false
            startIndex: true
          ckeditor5_sourceEditing:
            allowed_tags:
              - '<cite>'
              - '<dl>'
              - '<dt>'
              - '<dd>'
              - '<span>'
              - '<mention id>'
              - '<a hreflang target>'
              - '<blockquote cite>'
              - '<ul type>'
              - '<ol type>'
              - '<h2 id>'
              - '<h3 id>'
              - '<h4 id>'
              - '<h5 id>'
              - '<h6 id>'
              - '<table cellspacing cellpadding border>'
              - '<th scope>'
          editor_advanced_link_link:
            enabled_attributes:
              - class
              - id
              - rel
              - target
              - title
        toolbar:
          items:
            - bold
            - italic
            - '|'
            - link
            - '|'
            - bulletedList
            - numberedList
            - '|'
            - blockQuote
            - drupalInsertImage
            - '|'
            - heading
            - '|'
            - sourceEditing
            - '|'
            - insertTable
            - '|'
            - code
    change:
      editor: ckeditor
      settings:
        plugins:
          stylescombo:
            styles: ''
        toolbar:
          rows:
            -
              -
                items:
                  - Bold
                  - Italic
                name: Formatting
              -
                items:
                  - DrupalLink
                  - DrupalUnlink
                name: Linking
              -
                items:
                  - BulletedList
                  - NumberedList
                name: Lists
              -
                items:
                  - Blockquote
                  - DrupalImage
                name: Media
              -
                items:
                  - Format
                name: 'Block Formatting'
              -
                items:
                  - Source
                  - Maximize
                name: Tools
              -
                items:
                  - Table
                name: Tables
editor.editor.full_html:
  expected_config:
    editor: ckeditor5
    image_upload:
      max_dimensions:
        height: 0
        width: 0
    settings:
      plugins:
        ckeditor5_alignment:
          enabled_alignments:
            - left
            - center
            - right
            - justify
        ckeditor5_heading:
          enabled_headings:
            - heading2
            - heading3
            - heading4
            - heading5
            - heading6
        ckeditor5_imageResize:
          allow_resize: true
        ckeditor5_list:
          reversed: true
          startIndex: true
        ckeditor5_sourceEditing:
          allowed_tags: {  }
        ckeditor5_style:
          styles:
            -
              element: '<a class="btn btn-default">'
              label: 'Default link'
            -
              element: '<a class="btn btn-primary">'
              label: 'Primary link'
            -
              element: '<a class="btn btn-accent">'
              label: 'Accent link'
            -
              element: '<span class="badge badge-primary">'
              label: 'Primary badge'
            -
              element: '<span class="badge badge-secondary">'
              label: 'Secondary badge'
            -
              element: '<span class="badge badge--pill badge-default">'
              label: 'Pill badge'
        editor_advanced_link_link:
          enabled_attributes:
            - aria-label
            - class
            - id
            - rel
            - target
            - title
      toolbar:
        items:
          - bold
          - italic
          - strikethrough
          - superscript
          - subscript
          - removeFormat
          - '|'
          - alignment
          - '|'
          - link
          - '|'
          - bulletedList
          - numberedList
          - '|'
          - blockQuote
          - drupalInsertImage
          - insertTable
          - horizontalLine
          - '|'
          - heading
          - codeBlock
          - style
          - '|'
          - sourceEditing
  update_actions:
    delete:
      settings:
        plugins:
          ckeditor5_alignment:
            enabled_alignments:
              - left
              - center
              - right
              - justify
          ckeditor5_heading:
            enabled_headings:
              - heading2
              - heading3
              - heading4
              - heading5
              - heading6
          ckeditor5_imageResize:
            allow_resize: true
          ckeditor5_list:
            reversed: true
            startIndex: true
          ckeditor5_sourceEditing:
            allowed_tags: {  }
          ckeditor5_style:
            styles:
              -
                element: '<a class="btn btn-default">'
                label: 'Default link'
              -
                element: '<a class="btn btn-primary">'
                label: 'Primary link'
              -
                element: '<a class="btn btn-accent">'
                label: 'Accent link'
              -
                element: '<span class="badge badge-primary">'
                label: 'Primary badge'
              -
                element: '<span class="badge badge-secondary">'
                label: 'Secondary badge'
              -
                element: '<span class="badge badge--pill badge-default">'
                label: 'Pill badge'
          editor_advanced_link_link:
            enabled_attributes:
              - aria-label
              - class
              - id
              - rel
              - target
              - title
        toolbar:
          items:
            - bold
            - italic
            - strikethrough
            - superscript
            - subscript
            - removeFormat
            - '|'
            - alignment
            - '|'
            - link
            - '|'
            - bulletedList
            - numberedList
            - '|'
            - blockQuote
            - drupalInsertImage
            - insertTable
            - horizontalLine
            - '|'
            - heading
            - codeBlock
            - style
            - '|'
            - sourceEditing
    change:
      editor: ckeditor
      image_upload:
        max_dimensions:
          height: null
          width: null
      settings:
        plugins:
          language:
            language_list: un
          stylescombo:
            styles: "a.btn.btn-default|Default link\r\na.btn.btn-primary|Primary link\r\na.btn.btn-accent|Accent link\r\nspan.badge.badge-primary|Primary badge\r\nspan.badge.badge-secondary|Secondary badge\r\nspan.badge.badge--pill.badge-default|Pill badge"
        toolbar:
          rows:
            -
              -
                items:
                  - Bold
                  - Italic
                  - Strike
                  - Superscript
                  - Subscript
                  - '-'
                  - RemoveFormat
                name: Formatting
              -
                items:
                  - JustifyLeft
                  - JustifyCenter
                  - JustifyRight
                  - JustifyBlock
                name: Alignment
              -
                items:
                  - DrupalLink
                  - DrupalUnlink
                name: Linking
              -
                items:
                  - BulletedList
                  - NumberedList
                name: Lists
              -
                items:
                  - Blockquote
                  - DrupalImage
                  - Table
                  - HorizontalRule
                name: Media
              -
                items:
                  - Format
                  - Styles
                name: 'Block Formatting'
              -
                items:
                  - ShowBlocks
                  - Source
                  - Maximize
                name: Tools
editor.editor.mail_html:
  expected_config:
    editor: ckeditor5
    settings:
      plugins:
        ckeditor5_alignment:
          enabled_alignments:
            - left
            - center
            - right
            - justify
        editor_advanced_link_link:
          enabled_attributes:
            - class
            - id
            - rel
            - target
            - title
      toolbar:
        items:
          - bold
          - italic
          - underline
          - '|'
          - link
          - '|'
          - alignment
          - '|'
  update_actions:
    delete:
      settings:
        plugins:
          ckeditor5_alignment:
            enabled_alignments:
              - left
              - center
              - right
              - justify
          editor_advanced_link_link:
            enabled_attributes:
              - class
              - id
              - rel
              - target
              - title
        toolbar:
          items:
            - bold
            - italic
            - underline
            - '|'
            - link
            - '|'
            - alignment
            - '|'
    change:
      editor: ckeditor
      settings:
        plugins:
          language:
            language_list: un
          stylescombo:
            styles: ''
        toolbar:
          rows:
            -
              -
                items:
                  - Bold
                  - Italic
                  - Underline
                name: Formatting
              -
                items:
                  - DrupalLink
                  - DrupalUnlink
                name: Links
              -
                items:
                  - JustifyBlock
                  - JustifyLeft
                  - JustifyCenter
                  - JustifyRight
                name: Alignment
