filter.format.basic_html:
  expected_config: {  }
  update_actions:
    change:
      filters:
        filter_responsive_table:
          id: filter_responsive_table
          provider: responsive_table_filter
          status: true
          weight: 0
          settings:
            wrapper_element: figure
            wrapper_classes: responsive-figure-table

filter.format.full_html:
  expected_config: { }
  update_actions:
    change:
      filters:
        filter_responsive_table:
          id: filter_responsive_table
          provider: responsive_table_filter
          status: true
          weight: 0
          settings:
            wrapper_element: figure
            wrapper_classes: responsive-figure-table
