editor.editor.basic_html:
  expected_config: { }
  update_actions:
    add:
      settings:
        toolbar:
          items:
            - '|'
            - fullScreen

editor.editor.full_html:
  expected_config: { }
  update_actions:
    add:
      settings:
        toolbar:
          items:
            - '|'
            - fullScreen

editor.editor.mail_html:
  expected_config: { }
  update_actions:
    add:
      settings:
        toolbar:
          items:
            - fullScreen

