editor.editor.basic_html:
  expected_config: { }
  update_actions:
    add:
      settings:
        plugins:
          ckeditor5_heading:
            enabled_headings:
              - heading1

editor.editor.full_html:
  expected_config: { }
  update_actions:
    add:
      settings:
        plugins:
          ckeditor5_heading:
            enabled_headings:
              - heading1
