<?php

/**
 * @file
 * Install, update functions for the social_kpi_lite_tag_followers module.
 */


/**
 * @file
 * Install, update functions for the social_kpi_lite_tag_followers module.
 */

/**
 * Implements hook_install().
 */
function social_kpi_lite_tag_followers_install() {
  // Add KPI Blocks.
  $blocks = _social_kpi_lite_tag_followers_get_blocks_list();
  _social_kpi_lite_tag_followers_create_blocks($blocks);
}

/**
 * Implements hook_uninstall().
 */
function social_kpi_lite_tag_followers_uninstall() {
  $blocks = _social_kpi_lite_tag_followers_get_blocks_list();
  _social_kpi_lite_tag_followers_delete_blocks($blocks);
}

/**
 * For getting blocks list.
 */
function _social_kpi_lite_tag_followers_get_blocks_list(): array {
  return [
    'social_kpi_lite_tag_followers',
  ];
}

/**
 * Create block content.
 *
 * @param array $blocks
 *   List of blocks.
 */
function _social_kpi_lite_tag_followers_create_blocks(array $blocks) {
  $path = \Drupal::service('extension.list.module')->getPath('social_kpi_lite_tag_followers');
  $block_content_path = "{$path}/content/block_content";
  /** @var \Drupal\kpi_analytics\BlockContentCreator $block_content_creator */
  $block_content_creator = \Drupal::service('kpi_analytics.block_content_creator');

  foreach ($blocks as $block_id) {
    $block_content_creator->setSource($block_content_path, $block_id);
    $block_content_creator->create();
  }
}

/**
 * Delete block content.
 *
 * @param array $blocks
 *   List of blocks to delete.
 */
function _social_kpi_lite_tag_followers_delete_blocks(array $blocks) {
  $path = \Drupal::service('extension.list.module')->getPath('social_kpi_lite_tag_followers');
  $block_content_path = "{$path}/content/block_content";
  /** @var \Drupal\kpi_analytics\BlockContentCreator $block_content_creator */
  $block_content_creator = \Drupal::service('kpi_analytics.block_content_creator');

  foreach ($blocks as $block_id) {
    $block_content_creator->setSource($block_content_path, $block_id);
    $block_content_creator->delete();
  }
}
