<?php

/**
 * @file
 * Contains social_scroll.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\social_scroll\SocialScrollManagerInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_scroll_form_view_edit_form_alter(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\social_scroll\SocialScrollManagerInterface $social_scroll_manager */
  $social_scroll_manager = \Drupal::service('social_scroll.manager');
  $display_id = $form_state->get('display_id');

  /** @var \Drupal\views_ui\ViewUI $view */
  $view = $form_state->get('view');
  /** @var \Drupal\views\Entity\View $view_storage */
  $view_storage = $form_state->get('view')->get('storage');
  $display_plugin = $view_storage->get('display')[$display_id]['display_plugin'] ?? 'block';

  if ($display_plugin !== 'block' && in_array($view->id(), $social_scroll_manager->getEnabledViewIds(), TRUE)) {
    // Hide the pager block if this view is overridden by this module.
    $form['displays']['settings']['settings_content']['tab_content']['details']['columns']['second']['pager']['#access'] = FALSE;
    /** @var \Drupal\views_ui\ViewEditForm $form_object */
    $form_object = $form_state->getFormObject();
    $module_name = \Drupal::moduleHandler()->getName(SocialScrollManagerInterface::MODULE_NAME);

    $form_object->messenger()
      ->addWarning(t('Pager options are overridden by the "@module_name" module, so pager settings configured in this view will not work while that view is selected in @these options.', [
        '@module_name' => $module_name,
        '@these' => Link::createFromRoute(t('these'), 'social_scroll.settings')
          ->toString(),
      ]));
  }
}
