<?php

/**
 * @file
 * Install, update and uninstall functions for the social_path_manager module.
 */

/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of social_path_manager.
 */
function social_path_manager_install() {
  // Grant the default permissions for this feature.
  user_role_grant_permissions(
    'sitemanager',
    [
      'administer url aliases',
      'administer pathauto',
      'notify of path changes',
    ]
  );
}
