<?php

/**
 * @file
 * Contains activity_logger.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\message\MessageTypeInterface;

/**
 * Implements hook_help().
 */
function activity_logger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the activity_logger module.
    case 'help.page.activity_logger':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Used to log activities based on the message module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for message_type_form().
 */
function activity_logger_form_message_type_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\contact\ContactFormInterface $contact_form */
  $message_type = $form_state->getFormObject()->getEntity();
  $form['activity_context'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#title' => t('The activity context for this message'),
    '#description' => t('Select a context where to display this message.'),
    '#default_value' => $message_type->getThirdPartySetting('activity_context', 'activity_context', NULL),
    '#options' => array(
      '1' => t('Community'),
      '2' => t('Profile'),
      '3' => t('Group'),
    ),
  );
  $form['activity_destinations'] = array(
    '#type' => 'select',
    '#title' => t('The activity context for this message'),
    '#multiple' => TRUE,
    '#required' => TRUE,
    '#description' => t('Select a context where to display this message.'),
    '#default_value' => $message_type->getThirdPartySetting('activity_context', 'activity_context', NULL),
    '#options' => array(
      '1' => t('Explore stream'),
      '2' => t('Home stream'),
      '3' => t('Group stream'),
      '4' => t('Profile stream'),
      '5' => t('Notifications'),
    ),
  );
  $form['#entity_builders'][] = 'activity_logger_form_message_type_form_builder';
}

/**
 * Entity builder for the message type edit form with third party options.
 *
 * @see activity_logger_form_message_type_form_alter()
 */
function activity_logger_form_message_type_form_builder($entity_type, MessageTypeInterface $message_type, &$form, FormStateInterface $form_state) {
  $message_type->setThirdPartySetting('activity_logger', 'activity_context', $form_state->getValue('activity_context'));
  $message_type->setThirdPartySetting('activity_logger', 'activity_destinations', $form_state->getValue('activity_destinations'));
}
