<?php

/**
 * @file
 * Contains main module functionality.
 */

use Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem;
use Drupal\dynamic_entity_reference\Plugin\Field\FieldType\DynamicEntityReferenceItem;
use Drupal\field\FieldConfigInterface;

/**
 * Implements hook_ENTITY_TYPE_presave() for 'field_config'.
 *
 * @todo Clean this up once field_field_config_save is more accommodating.
 */
function dynamic_entity_reference_field_config_presave(FieldConfigInterface $field) {
  // Don't change anything during a configuration sync.
  if ($field->isSyncing()) {
    return;
  }

  $field_type_manager = \Drupal::service('plugin.manager.field.field_type');
  $er_item_class = EntityReferenceItem::class;
  $class = $field_type_manager->getPluginClass($field->getType());
  if ($class !== $er_item_class && !is_subclass_of($class, $er_item_class)) {
    return;
  }
  $der_item_class = DynamicEntityReferenceItem::class;
  if ($class === $der_item_class || is_subclass_of($class, $der_item_class)) {
    // DER needs to be handled differently.
    return;
  }

  // Just a normal ER item, do the things field_field_config_presave() would
  // have done before we removed it in
  // dynamic_entity_reference_module_implements_alter().
  $selection_manager = \Drupal::service('plugin.manager.entity_reference_selection');
  $target_type = $field->getFieldStorageDefinition()->getSetting('target_type');
  list($current_handler) = explode(':', $field->getSetting('handler'), 2);
  $field->setSetting('handler', $selection_manager->getPluginId($target_type, $current_handler));
}

/**
 * Implements hook_module_implements_alter().
 */
function dynamic_entity_reference_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'field_config_presave') {
    // We have to go after field_field_config_presave().
    $group = $implementations['dynamic_entity_reference'];
    unset($implementations['dynamic_entity_reference']);
    // Remove the field implementation, we have a fallback in our hook.
    unset($implementations['field']);
    $implementations['dynamic_entity_reference'] = $group;
  }
}
