<?php

/**
 * @file
 * Contains activity_logger.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\message\MessageTemplateInterface;
use Drupal\Core\Entity\ContentEntityTypeInterface;

/**
 * Implements hook_help().
 */
function activity_logger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the activity_logger module.
    case 'help.page.activity_logger':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Used to log activities based on the message module') . '</p>';
      return $output;

    default:
  }
}

function _activitiy_logger_get_content_entities( ) {
  $entitity_type_manager = \Drupal::service('entity_type.manager');
  $options = array();
  foreach ($entitity_type_manager->getDefinitions() as $entity_id => $entity_type) {
    if ( $entity_type instanceof ContentEntityTypeInterface
      && $entity_id !== 'activity'
      && $entity_id !== 'message'
      && $entity_id !== 'message_template') {
      $entity_type_bundle_info = \Drupal::service('entity_type.bundle.info');
      $config_entity_bundles = $entity_type_bundle_info->getBundleInfo($entity_type->id());
      foreach ($config_entity_bundles as $key => $value) {
        $options[$entity_id . '.' . $key] = $entity_type->getLabel() . ': ' . $value['label'];
      }
    }
  }
  return $options;
}

/**
 * Implements hook_form_FORM_ID_alter() for message_template_form().
 */
function activity_logger_form_message_template_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\contact\ContactFormInterface $contact_form */
  $message_template = $form_state->getFormObject()->getEntity();

  $config_entity_bundles = _activitiy_logger_get_content_entities();
  $form['activity_bundle_entity'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#title' => t('The entities that are affected for this message'),
    '#description' => t('Select a entity bundle type to for this message.'),
    '#default_value' => $message_template->getThirdPartySetting('activity_logger', 'activity_bundle_entity', NULL),
    '#options' => $config_entity_bundles,
  );


  $activity_actions = \Drupal::service('plugin.manager.activity_action.processor');
  $activity_actions = $activity_actions->getOptionsList();

  $form['activity_action'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#title' => t('The activity actions for this message'),
    '#description' => t('Select a action for when to display this message.'),
    '#default_value' => $message_template->getThirdPartySetting('activity_logger', 'activity_action', NULL),
    '#options' => $activity_actions,
  );

  $activity_recipient_manager = \Drupal::service('plugin.manager.activity_context.processor');
  $context_options = $activity_recipient_manager->getOptionsList();

  $form['activity_context'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#title' => t('The activity context for this message'),
    '#description' => t('Select a context where to display this message.'),
    '#default_value' => $message_template->getThirdPartySetting('activity_logger', 'activity_context', NULL),
    '#options' => $context_options,
  );

  $activity_recipient_manager = \Drupal::service('plugin.manager.activity_destination.processor');
  $destination_options = $activity_recipient_manager->getOptionsList();

  $form['activity_destinations'] = array(
    '#type' => 'select',
    '#title' => t('The activity destinations for this message'),
    '#multiple' => TRUE,
    '#required' => TRUE,
    '#description' => t('Select destinations where to display this message.'),
    '#default_value' => $message_template->getThirdPartySetting('activity_logger', 'activity_destinations', NULL),
    // @TODO activity_creator allowed_values function overlap (should be plugin)
    '#options' => $destination_options,
  );

  $form['activity_create_direct'] = array(
    '#type' => 'checkbox',
    '#required' => FALSE,
    '#title' => t('Create activity items direct instead of in Queue'),
    '#description' => t('Select if items should be created directly instead of in the queue. Warning: performance implications!'),
    '#default_value' => $message_template->getThirdPartySetting('activity_logger', 'activity_create_direct', NULL),
  );

  $form['#entity_builders'][] = 'activity_logger_form_message_template_form_builder';
}

/**
 * Entity builder for the message type edit form with third party options.
 *
 * @see activity_logger_form_message_template_form_alter()
 */
function activity_logger_form_message_template_form_builder($entity_type, MessageTemplateInterface $message_template, &$form, FormStateInterface $form_state) {
  $message_template->setThirdPartySetting('activity_logger', 'activity_bundle_entity', $form_state->getValue('activity_bundle_entity'));
  $message_template->setThirdPartySetting('activity_logger', 'activity_action', $form_state->getValue('activity_action'));
  $message_template->setThirdPartySetting('activity_logger', 'activity_context', $form_state->getValue('activity_context'));
  $message_template->setThirdPartySetting('activity_logger', 'activity_destinations', $form_state->getValue('activity_destinations'));
  $message_template->setThirdPartySetting('activity_logger', 'activity_create_direct', $form_state->getValue('activity_create_direct'));
}

