core.entity_view_display.comment.post_comment.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        like_and_dislike:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 2
core.entity_view_display.post.post.activity:
  expected_config: {  }
  update_actions:
    change:
      content:
        like_and_dislike:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 3
core.entity_view_display.post.post.activity_comment:
  expected_config: {  }
  update_actions:
    add:
      content:
        like_and_dislike:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 2
core.entity_view_display.post.post.default:
  expected_config: {  }
  update_actions:
    change:
      content:
        like_and_dislike:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 3
