social_user_export.settings:
  type: config_object
  label: 'Social User Export Settings'
  mapping:
    plugins:
      type: sequence
      label: 'Export plugins that can be used by normal users.'
      sequence:
        type: string

# Schema for action configuration.
action.configuration.social_user_export_user_action:
  type: mapping
  label: 'Export the selected users to CSV configuration'
