core.entity_view_display.node.book.activity:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.book.activity_comment:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.book.default:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.book.featured:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.book.hero:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.book.search_index:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.book.small_teaser:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.book.teaser:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
