core.entity_form_display.node.book.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_visibility:
            label: 'Access permissions'
          group_description:
            label: Description
          group_title:
            label: 'Basic information'
          group_attachments:
            label: 'Additional information'
          group_settings:
            label: Settings
