core.entity_view_display.node.book.activity:
  expected_config: { }
  update_actions:
    change:
      content:
        field_book_comments: { label: hidden }
        field_book_image: { label: hidden }
core.entity_view_display.node.book.activity_comment:
  expected_config: { }
  update_actions:
    change:
      content:
        field_book_image: { label: hidden }
