<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function social_auth_google_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'user') {
    $fields['google_id'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Google user ID'))
      ->setTranslatable(FALSE);

    return $fields;
  }
}
