<?php

/**
 * @file
 * Contains Social Management Overview module file.
 */

/**
 * Implements hook_menu_links_discovered_alter().
 */
function social_management_overview_menu_links_discovered_alter(array &$links): void {
  // Update theme settings link.
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  $links['social_management_overview.overview_page.theme_settings']['route_parameters']['theme'] = $theme;

  // Update homepage edit link.
  $query = \Drupal::database()->select('block_content', 'bc');
  $query->addField('bc', 'id');
  $query->condition('bc.type', 'hero_call_to_action_block');
  $query->range(0, 1);
  $execute = $query->execute();
  if (!is_null($execute)) {
    $block_id = $execute->fetchField();
    if ($block_id) {
      $links['social_management_overview.overview_page.home_page_settings']['route_parameters']['block_content'] = $block_id;
    }
  }
}
