<?php

/**
 * @file
 * The social node module alterations.
 */

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\node\NodeInterface;
use Drupal\social_node\Entity\Node;
use Drupal\social_node\QueryAccess\NodeEntityQueryAlter;
use Drupal\social_node\SocialNodeForm;
use Drupal\social_node\NodeViewBuilder;

/**
 * Implements hook_entity_type_alter().
 */
function social_node_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['node'])) {
    $entity_types['node']->setClass(Node::class);
    $entity_types['node']->setViewBuilderClass(NodeViewBuilder::class);

    foreach (['default', 'edit'] as $operation) {
      $entity_types['node']->setFormClass($operation, SocialNodeForm::class);
    }
  }
}

/**
 * Implements hook_social_core_title().
 */
function social_node_social_core_title(): array {
  return [
    'node' => [
      'route_name' => 'node.add',
    ],
  ];
}

/**
 * Implements hook_social_tagging_type().
 */
function social_node_social_tagging_type(): string {
  return 'node';
}

/**
 * Implements hook_node_access_records_alter().
 */
function social_node_node_access_records_alter(array &$grants, NodeInterface $node): void {
  if (
    !$node->hasField('field_content_visibility') ||
    $node->get('field_content_visibility')->isEmpty()
  ) {
    return;
  }

  $visibility = $node->get('field_content_visibility')->getString();

  if ($visibility !== 'public') {
    // Remove "view" realm for all visibility options except "public".
    foreach ($grants as &$grant) {
      if ($grant['realm'] === 'gnode_anonymous') {
        $grant['grant_view'] = 0;
      }
    }
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function social_node_query_entity_query_alter(AlterableInterface $query): void {
  if (!$query instanceof SelectInterface) {
    return;
  }

  $entity_type_id = $query->getMetaData('entity_type');
  if ($entity_type_id !== 'node' && !$query->hasTag('node_access')) {
    return;
  }

  $plugin_ids = \Drupal::service('group_relation_type.manager')->getPluginIdsByEntityTypeAccess('node');
  if (empty($plugin_ids)) {
    // If no group relationship plugins for "node" entity type is enabled.
    return;
  }

  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(NodeEntityQueryAlter::class)
    ->alterQuery($query);
}

/**
 * Implements hook_query_TAG_alter().
 */
function social_node_query_views_entity_query_alter(AlterableInterface $query): void {
  if (!$query instanceof SelectInterface) {
    return;
  }

  if ($query->getMetaData('entity_type') !== 'node') {
    return;
  }

  if (!$query->hasTag('node_access')) {
    $query->addTag('node_access');
  }

  social_node_query_entity_query_alter($query);
}

