<?php

/**
 * @file
 * Provides "Featured Content" paragraphs type for landing pages.
 */

/**
 * Implements hook_theme().
 */
function social_featured_content_theme() {
  return [
    'paragraph__featured__default' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_featured_content_preprocess_node(&$variables) {
  if ($variables['view_mode'] === 'featured') {
    $variables['label'] = render($variables['label']);
  }
}
