<?php

/**
 * @file
 * The Social core module.
 */
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function social_core_theme() {
  return array(
    'page_hero_data' => array(
      'variables' => array(
        'title' => NULL,
        'author_name' => NULL,
        'created_date' => NULL,
        'created_date_formatted' => NULL,
        'topic_type' => NULL,
        'group_link' => NULL,
        'hero_node' => NULL,
        'section_class' => NULL,
        'event_enrollment' => NULL,
      ),
    ),
  );
}

/**
 * Prepares variables for the social page hero data.
 *
 * Default template: page-hero-data.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - title: Page title as a string
 *   - author_name: Author as a string
 *   - created_date: Timestamp
 *   - created_date_formatted: Formatted date as a string
 *   - topic_type: List of topic types as an array or NULL
 *   - hero_node: Rendered hero display of the current active node or NULL
 */
function template_preprocess_page_hero_data(&$variables) {
  // @todo create $variables['author_formatted']?
  // @todo Pass in all the page_title variables?
  if (isset($variables['created_date']) && !isset($variables['created_date_formatted'])) {
    $variables['created_date_formatted'] = \Drupal::service('date.formatter')->format($variables['created_date']);
  }
  if (isset($variables['topic_type'])) {
    $topic_type_entities = $variables['topic_type']->referencedEntities();
    if (count($topic_type_entities) === 1) {
      foreach($topic_type_entities as $topic) {
        $variables['topic_type'] = $topic->link();
      }
    }
    else {
      $variables['topic_type'] = NULL;
    }
  }
  if (empty($variables['event_enrollment'])) {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node->getType() == 'event') {
      $form = \Drupal::formBuilder()->getForm('Drupal\social_event\Form\EnrollActionForm');

      $render_array = array(
        'enroll_action_form' => $form
      );

      $variables['event_enrollment'] = $render_array;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For Site information Site details form.
 */
function social_core_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Hide site slogan field and make it disabled as well whenever the user
  // is able to fill out the textfield.
  if (!empty($form['site_information']['site_slogan'])) {
    $form['site_information']['site_slogan']['#type'] = 'hidden';
    $form['site_information']['site_slogan']['#disabled'] = TRUE;
  }
}

/**
 * Implements hook_node_links_alter().
 */
function social_core_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  // Remove the comment links.
  unset($links['comment__field_topic_comments']);
  unset($links['comment__field_event_comments']);
}
