<?php

/**
 * @file
 * The Social Event Max Enroll install file.
 */

/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of social_event_max_enroll.
 */
function social_event_max_enroll_install() {
  // Set higher weight.
  module_set_weight('social_event_max_enroll', 10);
}

/**
 * Implements hook_update_last_removed().
 */
function social_event_max_enroll_update_last_removed() : int {
  return 11001;
}
