<?php

/**
 * @file
 * The Social core module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\flag\Entity\Flagging;

/**
 * Implements hook_ENTIT_YTYPE_insert().
 */
function social_follow_content_event_enrollment_insert(EntityInterface $entity) {
  social_follow_content_event_enrollment_follow($entity);
}

/**
 * Implements hook_ENTIT_YTYPE_update().
 */
function social_follow_content_event_enrollment_update(EntityInterface $entity) {
  social_follow_content_event_enrollment_follow($entity);
}

/**
 * Automatically follow content when user enrolls the event.
 */
function social_follow_content_event_enrollment_follow(EntityInterface $entity) {
  if ($entity->field_enrollment_status->value) {
    // Check if user already follow this content.
    // Only logged in users can follow content.
    $account = \Drupal::currentUser();
    if (!$account->isAuthenticated()) {
      return;
    }

    $properties = [
      'uid' => $account->id(),
      'entity_type' => 'node',
      'entity_id' => $entity->field_event->target_id,
      'flag_id' => 'follow_content',
    ];
    $flaggings = \Drupal::entityTypeManager()
      ->getStorage('flagging')
      ->loadByProperties($properties);
    $flagging = reset($flaggings);

    if (empty($flagging)) {
      $flagging = Flagging::create($properties);
      if ($flagging) {
        $flagging->save();
        $message = t('You have successfully enrolled to this event. Also you are now following the event, which means you will receive notifications when a new comment is placed.');
        drupal_set_message($message);
      }
    }
  }
}

/**
 * Implements hook_social_user_account_header_account_links().
 *
 * Adds the "Following" link to the user menu.
 */
function social_follow_content_social_user_account_header_account_links(array $context) {
  return [
    'my_content' => [
      '#type' => 'link',
      '#attributes' => [
        'title' => new TranslatableMarkup("View content I'm following"),
      ],
      '#url' => Url::fromRoute('view.following.following'),
      '#title' => new TranslatableMarkup('Following'),
      '#weight' => 1000,
    ],
  ];
}
