"""
Input to set the groups of a piece of content.
"""
input ContentInGroupInput {
  """
  The group that owns the content.
  """
  group: ID!
  """
  That field only be used if the crossposted feature is enable at flexible_group configuration.
  The other groups that may view the content. Must not include the group that owns the content. Only applicable when the crossposted feature is enabled for HUBs.
  Should not list the group that owns the content.
  """
  crosspostedGroups: [ID!]!
}

"""
Provides a way to differentiate between "field should not be changed" and "field should be empty".
In objects where a group is optional this value can be provided with a NULL value to empty the group selection, or with
a new set of groups to update the value.
"""
input UpdateContentInGroupInput {
  """
  If set to NULL, will remove the content from any group.
  """
  value: ContentInGroupInput
}
