views.view.activity_stream:
  expected_config: { }
  update_actions:
    add:
      display:
        block_stream_explore:
          display_options:
            filters:
              activity_explore_visibility_access_filter:
                admin_label: ''
                entity_type: activity
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: activity_explore_visibility_access_filter
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: activity_explore_visibility_access_filter
                is_grouped: false
                operator: '='
                plugin_id: activity_explore_visibility_access
                relationship: none
                table: activity
                value: ''
        page_explore:
          display_options:
            filters:
              activity_explore_visibility_access_filter:
                admin_label: ''
                entity_type: activity
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: activity_explore_visibility_access_filter
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: activity_explore_visibility_access_filter
                is_grouped: false
                operator: '='
                plugin_id: activity_explore_visibility_access
                relationship: none
                table: activity
                value: ''
