views.view.activity_stream_notifications:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              activity_notification_visibility_access_filter:
                id: activity_notification_visibility_access_filter
                table: activity
                field: activity_notification_visibility_access_filter
                relationship: none
                group_type: group
                admin_label: ''
                operator: '='
                value: ''
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
                entity_type: activity
                plugin_id: activity_notification_visibility_access
