views.view.activity_stream:
  expected_config:
    display:
      block_stream_homepage:
        display_title: 'Homepage stream block'
  update_actions:
    change:
      display:
        block_stream_homepage:
          display_title: 'Homepage stream (with post form)'
views.view.community_activities:
  expected_config:
    display:
      block_stream_landing_with_post:
        display_title: 'Community activities block'
  update_actions:
    change:
      display:
        block_stream_landing_with_post:
          display_title: 'Community activities block (with post form)'
