dependencies:
  module:
    - taxonomy_access_fix
items:
  user.role.sitemanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view terms in profile_organization_tag'
          - 'view term names in profile_organization_tag'
          - 'select terms in profile_organization_tag'
  user.role.verified:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view terms in profile_organization_tag'
          - 'view term names in profile_organization_tag'
          - 'select terms in profile_organization_tag'
  user.role.contentmanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view terms in profile_organization_tag'
          - 'view term names in profile_organization_tag'
          - 'select terms in profile_organization_tag'
