items:
  message.template.create_post_group:
    expected_config:
        settings:
          'token options':
            clear: false
    update_actions:
      change:
        settings:
          'token options':
            clear: true
