__global_actions:
  import_configs:
    - field.storage.profile.affiliation_owned_count
    - field.storage.profile.user_removed_affiliations
    - field.field.profile.profile.affiliation_owned_count
    - field.field.profile.profile.user_removed_affiliations
