core.entity_view_display.profile.profile.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        groups_affiliation_list:
          settings: { }
          third_party_settings: { }
          weight: 6
          region: content
