core.entity_view_display.profile.profile.medium_teaser:
  expected_config:
    content:
      field_profile_image:
        third_party_settings:
          lazy:
            lazy_image: 0
  update_actions:
    delete:
      content:
        field_profile_image:
          third_party_settings:
            lazy:
              lazy_image: 0
    change:
      content:
        field_profile_image:
          third_party_settings: {  }
