views.view.user_information:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              type: profile_pages_access
              options: {  }
