core.entity_form_display.profile.profile.default:
  expected_config: { }
  update_actions:
    change:
      content:
        field_profile_banner_image:
          weight: 10
        field_profile_expertise:
          weight: 13
        field_profile_first_name:
          weight: 8
        field_profile_function:
          weight: 16
        field_profile_image:
          weight: 11
        field_profile_interests:
          weight: 14
        field_profile_last_name:
          weight: 9
        field_profile_organization:
          weight: 17
        field_profile_profile_tag:
          weight: 15
        field_profile_self_introduction:
          weight: 12
