field.field.paragraph.other_affiliations.field_affiliation_org_function:
  expected_config:
    label: 'Function in affiliated organisation'
  update_actions:
    change:
      label: 'Function in affiliated organization'

field.field.paragraph.other_affiliations.field_affiliation_org_name:
  expected_config:
    label: 'Name of the affiliated organisation'
  update_actions:
    change:
      label: 'Name of the affiliated organization'
