core.entity_form_display.profile.profile.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_profile_names_image:
            label: 'Names and profile image'
            format_settings:
              label: 'Names and profile image'
          group_profile_funct_organization:
            label: 'Function and organization'
            format_settings:
              label: 'Function and organization'
          group_profile_self_intro:
            label: 'Self introduction, expertise and interests'
            format_settings:
              label: 'Self introduction, expertise and interests'
          group_profile_contact_info:
            label: 'Phone number and location'
            format_settings:
              label: 'Phone number and location'
