views.view.newest_users:
  expected_config: {}
  update_actions:
    delete: {}
    add:
      display:
        default:
          display_options:
            filters:
              roles_target_id:
                admin_label: ''
                entity_field: roles
                entity_type: user
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: roles_target_id
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: roles_target_id
                is_grouped: false
                operator: 'not empty'
                plugin_id: user_roles
                reduce_duplicates: false
                relationship: uid
                table: user__roles
                value: {  }
