views.view.newest_users:
  expected_config: {  }
  update_actions:
    change:
      display:
        page_newest_users:
          display_options:
            defaults:
              filters: false
              filter_groups: false
