core.entity_view_display.profile.profile.default:
  expected_config:
    content:
      field_profile_profile_tag:
        label: visually_hidden
  update_actions:
    change:
      content:
        field_profile_profile_tag:
          label: inline
