views.view.newest_users:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
views.view.user_information:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
