field.field.node.event.body:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.node.event.field_event_location:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.node.event.field_event_address:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.node.event.field_files:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.node.event.field_event_image:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
views.view.upcoming_events:
  expected_config: {  }
  update_actions:
    add:
      display:
        block_community_events:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        block_my_upcoming_events:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        page_community_events:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        upcoming_events_group:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
views.view.events:
  expected_config: {  }
  update_actions:
    add:
      display:
        events_overview:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        block_events_on_profile:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
views.view.group_events:
  expected_config: {  }
  update_actions:
    add:
      display:
        page_group_events:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
views.view.event_enrollments:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              langcode:
                id: langcode
                table: node_field_data
                field: langcode
                relationship: field_event
                group_type: group
                admin_label: ''
                operator: in
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                entity_type: node
                entity_field: langcode
                plugin_id: language
views.view.event_manage_enrollment_requests:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              langcode:
                id: langcode
                table: node_field_data
                field: langcode
                relationship: field_event
                group_type: group
                admin_label: ''
                operator: in
                value:
                  '***LANGUAGE_language_interface***': '***LANGUAGE_language_interface***'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                entity_type: node
                entity_field: langcode
                plugin_id: language
