core.entity_view_display.node.event.small_teaser:
  expected_config:
    content:
      field_event_date: { }
    hidden:
      field_event_image: true
  update_actions:
    add:
      content:
        field_event_image:
          label: hidden
          region: content
          settings:
            image_link: content
            image_style: social_medium
          third_party_settings: {  }
          type: image
          weight: 0
    change:
      content:
        field_event_date:
          weight: 1
    delete:
      hidden:
        field_event_image: true
