views.view.event_enrollments:
  expected_config: {}
  update_actions:
    change:
      display:
        default:
          display_options:
            header:
              area_text_custom:
                admin_label: ''
                content: '[social_event:enrolled_users_count]'
                empty: true
                field: area_text_custom
                group_type: group
                id: area_text_custom
                plugin_id: text_custom
                relationship: none
                table: views
                tokenize: false
    delete:
      display:
        default:
          display_options:
            header:
              result:
