message.template.user_was_enrolled_to_event:
  expected_config: { }
  update_actions:
    delete:
      text: ~
    add:
      text:
        -
          value: "<p>Congratulations! You are now enrolled in the event <em>[social_event:event_iam_organizing]</em>. [social_event:is-online-addition]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
          format: full_html
