views.view.event_enrollments:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              langcode: {  }
views.view.event_manage_enrollment_requests:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              langcode: { }
