core.entity_form_display.node.event.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_event_schedule:
            weight: 1
          group_location:
            weight: 2
          group_event_visibility:
            weight: 3
          group_attachments:
            weight: 5
          group_settings:
            weight: 30
