views.view.upcoming_events:
  expected_config: { }
  update_actions:
    delete:
      display:
        page_community_events:
          display_options:
            filters:
              field_event_date_value: { }
            sorts:
              event_passed_upcoming_sort: { }
    add:
      display:
        page_community_events:
          display_options:
            filters:
              event_date:
                admin_label: ''
                expose:
                  description: null
                  identifier: field_event_date_value
                  label: 'Event date'
                  multiple: false
                  operator: event_date_op
                  operator_id: event_date_op
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: true
                field: event_date
                group: 1
                group_info:
                  default_group: '1'
                  default_group_multiple: {  }
                  description: ''
                  group_items:
                    1:
                      operator: in
                      title: 'Ongoing and upcoming events'
                      value: '1'
                    2:
                      operator: in
                      title: 'Past events'
                      value: '2'
                    3:
                      operator: in
                      title: ''
                      value: {  }
                  identifier: field_event_date_value
                  label: ''
                  multiple: false
                  optional: false
                  remember: false
                  widget: radios
                group_type: group
                id: event_date
                is_grouped: true
                operator: in
                plugin_id: social_event_date_filter
                relationship: none
                table: node__field_event_date
                value: {  }
            sorts:
              event_date:
                admin_label: ''
                expose:
                  label: ''
                exposed: false
                field: event_date
                granularity: minute
                group_type: group
                id: event_date
                order: ASC
                plugin_id: social_event_date_sort
                relationship: none
                table: node__field_event_date
