core.entity_view_display.node.event.small_teaser:
  expected_config:
    content:
      field_event_date:
        weight: 0
      flag_follow_content:
        region: content
        weight: 10
    hidden:
      field_event_image: true
  update_actions:
    add:
      hidden:
        flag_follow_content: true
        social_tagging: true
    change:
      content:
        field_event_date:
          weight: 1
        field_event_image:
          label: hidden
          region: content
          settings:
            image_link: content
            image_style: social_medium
          third_party_settings: {  }
          type: image
          weight: 0
    delete:
      content:
        flag_follow_content: {  }
      hidden:
        field_event_image: true
        groups_type_public_group: true
