core.entity_form_display.node.event.default:
  expected_config: { }
  update_actions:
    change:
      third_party_settings:
        field_group:
          group_title_image:
            label: 'Basic information'
          group_date_time:
            label: 'Date & time'
          group_location:
            label: Location
          group_event_visibility:
            label: 'Access permissions'
          group_attachments:
            label: 'Additional information'
          group_enrollment:
            label: Enrollment
          group_enrollment_methods:
            label: 'Enrollment options fieldset'
          group_settings:
            label: Settings
