core.entity_view_display.node.event.activity:
  expected_config:
    content:
      field_event_comments:
        settings:
          always_show_all_comments: '1'
  update_actions:
    change:
      content:
        field_event_comments:
          settings:
            always_show_all_comments: true
field.field.node.event.field_content_visibility:
  expected_config:
    default_value: null
  update_actions:
    change:
      default_value: {  }
views.view.events:
  expected_config:
    display:
      events_overview:
        display_options:
          filters:
            event_date:
              group_info:
                group_items:
                  3:
                    value: {  }
              value: {  }
  update_actions:
    change:
      display:
        events_overview:
          display_options:
            filters:
              event_date:
                group_info:
                  group_items:
                    3:
                      value: null
                value: null
views.view.upcoming_events:
  expected_config:
    display:
      page_community_events:
        display_options:
          filters:
            event_date:
              group_info:
                group_items:
                  3:
                    value: {  }
              value: {  }
  update_actions:
    change:
      display:
        page_community_events:
          display_options:
            filters:
              event_date:
                group_info:
                  group_items:
                    3:
                      value: null
                value: null
