__global_actions:
  import_configs:
    - core.entity_view_mode.media.event
    - core.entity_form_mode.media.event
    - core.entity_form_display.media.video_recording_link.event
    - core.entity_view_display.media.video_recording_link.event
