core.entity_form_display.node.event.default:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_enrollment_methods:
            format_settings:
              open: true
              classes: enrollment-methods
              description: ''
              id: ''
              required_fields: false
    change:
      third_party_settings:
        field_group:
          group_enrollment_methods:
            format_type: details
      content:
        field_event_enroll:
          weight: 19

field.field.node.event.field_event_enroll:
  expected_config: { }
  update_actions:
    change:
      label: 'Enable event enrollment'
