core.entity_view_display.node.event.activity:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_public_group: {  }
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.event.activity_comment:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_public_group: {  }
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.event.default:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_public_group: {  }
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.event.hero:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.event.search_index:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_public_group: { }
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.event.small_teaser:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_public_group: { }
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

core.entity_view_display.node.event.teaser:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_public_group: { }
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }

block.block.socialblue_views_block__upcoming_events_upcoming_events_group:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            open_group: {  }
            closed_group: {  }
            public_group: {  }
            secret_group: {  }
