core.entity_form_display.node.event.default:
  expected_config: { }
  update_actions:
    change:
      content:
        field_event_enroll:
          weight: 19

field.field.node.event.field_event_enroll:
  expected_config: { }
  update_actions:
    change:
      label: 'Enable event enrollment'
