views.view.upcoming_events:
  expected_config: {  }
  update_actions:
    change:
      display:
        upcoming_events_group:
          display_options:
            arguments:
              gid:
                table: group_relationship_field_data
