block.block.socialblue_views_block__event_enrollments_event_enrollments_socialbase:
  expected_config:
    visibility:
      request_path:
        pages: "/node/*/edit\r\n/node/*/delete"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/node/*/edit\r\n/node/*/delete\r\n/node/*/translations*"
