views.view.upcoming_events:
  expected_config: {  }
  update_actions:
    add:
      display:
        page_community_events:
          display_options:
            filters:
              field_enroll_method_value:
                admin_label: ''
                expose:
                  description: ''
                  identifier: field_enroll_method_value
                  label: 'Enroll Method'
                  multiple: false
                  operator: field_enroll_method_value_op
                  operator_id: field_enroll_method_value_op
                  operator_limit_selection: false
                  operator_list: {  }
                  reduce: false
                  remember: false
                  remember_roles:
                    administrator: '0'
                    anonymous: '0'
                    authenticated: authenticated
                    contentmanager: '0'
                    sitemanager: '0'
                  required: false
                  use_operator: false
                exposed: true
                field: field_enroll_method_value
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: field_enroll_method_value
                is_grouped: false
                operator: or
                plugin_id: list_field
                reduce_duplicates: false
                relationship: none
                table: node__field_enroll_method
                value: {  }
