views.view.events:
  expected_config: {  }
  update_actions:
    delete:
      display:
        block_events_on_profile:
          display_options:
            filters:
              nid: {  }
        events_overview:
          display_options:
            filters:
              nid: {  }
views.view.upcoming_events:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              nid: {  }
        block_my_upcoming_events:
          display_options:
            filters:
              nid: {  }
        page_community_events:
          display_options:
            filters:
              nid: {  }
        upcoming_events_group:
          display_options:
            filters:
              nid: {  }
