views.view.event_enrollments:
  expected_config:
    display:
      event_enrollments:
        display_plugin: block
        id: event_enrollments
        display_title: Block
        position: 2
        display_options:
          display_extenders: {  }
          block_description: 'Enrollments Block'
          footer:
            area:
              id: area
              table: views
              field: area
              relationship: none
              group_type: group
              admin_label: ''
              empty: false
              tokenize: true
              content:
                value: '<a href="/node/{{ raw_arguments.nid }}/enrollments">See all enrollments</a>'
                format: basic_html
              plugin_id: text
          defaults:
            footer: false
            style: false
            row: false
            pager: false
            arguments: false
            link_display: false
            link_url: false
            use_more: false
            use_more_always: false
            use_more_text: false
          style:
            type: default
            options: {  }
          row:
            type: 'entity:profile'
            options:
              relationship: none
              view_mode: compact
          pager:
            type: some
            options:
              items_per_page: 12
              offset: 0
          arguments:
            nid:
              id: nid
              table: node_field_data
              field: nid
              relationship: field_event
              group_type: group
              admin_label: ''
              default_action: default
              exception:
                value: all
                title_enable: false
                title: All
              title_enable: false
              title: ''
              default_argument_type: node
              default_argument_options: {  }
              summary_options:
                base_path: ''
                count: true
                items_per_page: 25
                override: false
              summary:
                sort_order: asc
                number_of_records: 0
                format: default_summary
              specify_validation: false
              validate:
                type: none
                fail: 'not found'
              validate_options: {  }
              break_phrase: false
              not: false
              entity_type: node
              entity_field: nid
              plugin_id: node_nid
          link_display: view_enrollments
          link_url: ''
          use_more: true
          use_more_always: true
          use_more_text: 'All enrollments'
  update_actions:
    change:
      display:
        event_enrollments:
          display_options:
            display_extenders: {  }
            block_description: 'Enrollments Block'
            footer: {  }
            defaults:
              footer: false
              style: false
              row: false
              pager: false
              arguments: false
              link_display: false
              link_url: false
              use_more: false
              use_more_always: false
              use_more_text: false
            style:
              type: default
              options: {  }
            row:
              type: 'entity:profile'
              options:
                relationship: none
                view_mode: compact
            pager:
              type: some
              options:
                items_per_page: 12
                offset: 0
            arguments:
              nid:
                id: nid
                table: node_field_data
                field: nid
                relationship: field_event
                group_type: group
                admin_label: ''
                default_action: default
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: node
                default_argument_options: {  }
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  items_per_page: 25
                  override: false
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: false
                validate:
                  type: none
                  fail: 'not found'
                validate_options: {  }
                break_phrase: false
                not: false
                entity_type: node
                entity_field: nid
                plugin_id: node_nid
            link_display: custom_url
            link_url: '/node/{{ raw_arguments.nid }}/enrollments'
            use_more: true
            use_more_always: true
            use_more_text: 'All enrollments'
    delete:
      display:
        event_enrollments:
          display_options:
            footer: {  }
