field.field.paragraph.featured.field_featured_description:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured.field_featured_link:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured.field_featured_title:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
