core.entity_view_display.node.event.featured:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.page.featured:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.topic.featured:
  expected_config: {  }
  update_actions:
    delete:
      content:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }
