<?php

use Drupal\social_user\Plugin\Action\SocialSendEmail;
use Drupal\social_advanced_queue\Plugin\Action\SocialSendEmailAdvancedQueue;

/**
 * @file
 * Module file for  Social Advanced Queue.
 */

function social_advanced_queue_action_info_alter(&$definitions) {
  // The Send Email Action needs a new Queue Worker.
  // So we can extend it.
  foreach ($definitions as &$definition) {
    if ($definition['id'] === 'social_user_send_email' && $definition['class'] === SocialSendEmail::class) {
      $definition['class'] = SocialSendEmailAdvancedQueue::class;
    }
  }
}