social_queue_storage.queue_storage_entity_type.*:
  type: config_entity
  label: 'Queue storage entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
