items:
  metatag.settings:
    expected_config:
      entity_type_groups: { }
    update_actions:
      add:
        entity_type_groups:
          profile:
            profile:
              basic: basic
