<?php

/**
 * @file
 * The Social post album module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\social_post\Entity\PostInterface;

/**
 * Implements hook_theme().
 */
function social_post_album_theme($existing, $type, $theme, $path) {
  return [
    'image_popup_details' => [
      'variables' => [
        'url_popup' => NULL,
        'pid' => NULL,
      ],
      'path' => $path . '/templates',
      'template' => 'image-popup-formatter',
    ],
    'field__post__type__image__album' => [
      'base hook' => 'field',
      'render element' => 'element',
      'path' => $path . '/templates',
      'template' => 'field--post--type--image--album',
    ],
  ];
}

/**
 * @param $variables
 */
function social_post_album_preprocess_field__post__type__image__album(&$variables) {
  $post = $variables['element']['#object'];

  if ($post instanceof PostInterface && $post->hasField('field_post')) {
    $fids = [];
    $items = $variables['items'];
    foreach ($items as $item) {
      $fids[] = $item['content']['#item']->entity->fid->value;
    }

    $variables['fids'] = implode($fids, ',');
    $variables['pid'] = $post->id();
  }
}

/**
 * @param $variables
 */
function social_post_album_preprocess_image_popup_details(&$variables) {
  $post = \Drupal::entityTypeManager()->getStorage('post')->load($variables['pid']);;

  $variables['post'] = [
    '#lazy_builder' => ['social_post_album.lazy_renderer:getPost', [
      $post->getEntityTypeId(),
      $post->id(),
      'album',
    ]],
    '#create_placeholder' => TRUE,
  ];
}

/**
 * Implements hook_preprocess().
 */
function social_post_album_preprocess_activity(&$variables, $hook) {
  $variables['extra_stream_class'] = 'social-post-album--post';
}

/**
 * Implements hook_preprocess().
 */
function social_post_album_preprocess_block__social_post(&$variables, $hook) {
  $variables['extra_stream_class'] = 'social-post-album--form';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function social_post_album_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  $element = $variables['element'];

  if ($element['#field_name'] === 'field_post_image') {
    $suggestions[] = 'field__' . $element['#entity_type'] . '__type__' . $element['#field_type'] . '__album';
  }

  return $suggestions;
}

/**
 * Implements hook_form_alter().
 */
function social_post_album_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['social_post_entity_form'])) {
    $form['#attached']['library'][] = 'social_post_album/social-post-album--form';
  }
}
