<?php

/**
 * @file
 * Hooks that integrate the recaptcha module with Open Social specific changes.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_captcha_form_user_register_form_alter(&$form, FormStateInterface $form_state) {
  // Move the captcha check into the account card container.
  if (isset($form['captcha']) && isset($form['account'])) {
    $form['account']['captcha'] = $form['captcha'];
    unset($form['captcha']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Removes the "CAPTCHA" title from the captcha details pane.
 */
function social_captcha_preprocess_captcha(array &$variables) {
  // The captcha is not always in a details panel.
  if (isset($variables['details'])) {
    /** @var \Drupal\Core\StringTranslation\TranslatableMarkup $title */
    $title = $variables['details']['#title'];

    // We only remove the title if it's not purposefully changed elsewhere.
    if ($title->getUntranslatedString() === 'CAPTCHA') {
      unset($variables['details']['#title']);
    }
  }
}
