<?php

/**
 * @file
 * Drupal hook implementations for the Social Search Autocomplete module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_search_autocomplete_form_search_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // We require a search input field.
  if (isset($form['search_input_content'])) {
    // Ensure the search input field has a unique id to target in js.
    if (empty($form['search_input_content']['#id'])) {
      $form['search_input_content']['#id'] = Html::getUniqueId('search_input_content');
    }

    $form['search_suggestions'] = [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => [
        'class' => ['social-search-suggestions'],
        'data-search-suggestions-for' => $form['search_input_content']['#id'],
      ],
      '#weight' => '20',
      '#attached' => [
        'library' => ['social_search_autocomplete/search_autocomplete'],
      ],
    ];

    $form['#attributes']['class'][] = 'search--with-suggestions';
  }
}
