<?php

/**
 * @file
 * Install, update and uninstall functions for the social_graphql module.
 */

/**
 * Implements hook_install().
 */
function social_graphql_install() {
  // Ensure users can use GraphQL powered applications with our default server.
  // We rely on normal access rules for authorization.
  user_role_grant_permissions('anonymous', ['execute open_social_graphql arbitrary graphql requests']);
  user_role_grant_permissions('authenticated', ['execute open_social_graphql arbitrary graphql requests']);
}

/**
 * Implements hook_update_last_removed().
 */
function social_graphql_update_last_removed() : int {
  return 10101;
}

/**
 * Enable the graphql_oauth module.
 */
function social_graphql_update_25001(): void {
  \Drupal::service('module_installer')->install(['graphql_oauth']);
}

/**
 * Disable GraphQL introspection on the Open Social GraphQL server (PROD-34935).
 */
function social_graphql_update_25002(): string {
  /** @var \Drupal\update_helper\Updater $updater */
  $updater = \Drupal::service('update_helper.updater');

  $updater->executeUpdate('social_graphql', __FUNCTION__);

  return $updater->logger()->output();
}
