social_event_invite.settings:
  expected_config: {  }
  update_actions:
    delete:
      social_group_quickjoin_open_group: {  }
      social_group_quickjoin_public_group: {  }
      social_group_quickjoin_closed_group: {  }
      social_group_quickjoin_secret_group: {  }
