<?php

/**
 * @file
 * Contains social_kpi_lite.module.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\block\Entity\Block;

/**
 * Implements hook_help().
 */
function social_kpi_lite_help($route_name) {
  if ($route_name === 'help.page.social_kpi_lite') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Implements KPI Analytics for Open Social distribution.') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_block_access().
 */
function social_kpi_lite_block_access(Block $block, $operation, AccountInterface $account) {
  if (strpos($block->id(), 'social_kpi_lite') !== FALSE) {
    // Only grant access to users with the access to analytics reports page.
    return AccessResult::forbiddenIf(!$account->hasPermission('access kpi analytics reports'))->addCacheContexts(['user.permissions']);
  }
  return AccessResult::neutral();
}
