field.field.block_content.basic.field_text_block:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.block_content.basic.field_basic_link:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.block_content.hero_call_to_action_block.field_call_to_action_link:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.block_content.hero_call_to_action_block.field_hero_image:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.block_content.hero_call_to_action_block.field_text_block:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.block_content.platform_intro.field_text_block:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
