block.block.socialblue_pagetitleblock_content:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        request_path:
          'entity_bundle:node': {  }
          group_type: {  }
