socialblue.settings:
  expected_config: {  }
  update_actions:
    add:
      popover_enabled: 1
      popover_animation: 1
      popover_auto_close: 1
      popover_container: body
      popover_placement: right
      popover_trigger: hover

