image.style.social_medium:
  expected_config:
    effects:
      151b526b-cb42-4553-a9ab-9c2407ee4134:
        uuid: 151b526b-cb42-4553-a9ab-9c2407ee4134
        id: crop_crop
        weight: 1
        data:
          crop_type: profile_medium
          automatic_crop_provider: null
  update_actions:
    change:
      effects:
        151b526b-cb42-4553-a9ab-9c2407ee4134:
          uuid: 151b526b-cb42-4553-a9ab-9c2407ee4134
          id: crop_crop
          weight: 1
          data:
            crop_type: teaser
            automatic_crop_provider: null
