core.entity_view_display.paragraph.featured_item.default:
  expected_config: { }
  update_actions:
    change:
      content:
        field_featured_item_link:
          settings:
            class: 'card__link btn btn-default'
            rel: 0
            target: 0
            trim_length: '80'
          type: link_with_class
