field.field.paragraph.featured_item.field_featured_item_description:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured_item.field_featured_item_image:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured_item.field_featured_item_link:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured_item.field_featured_item_title:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured_items.field_featured_items_description:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.paragraph.featured_items.field_featured_items_title:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
