dependencies:
  config:
    - field.field.group.flexible_group.field_group_type
items:
  views.view.newest_groups:
    expected_config: { }
    update_actions:
      add:
        display:
          page_all_groups:
            display_options:
              filters:
                field_group_type_target_id:
                  id: field_group_type_target_id
                  table: group__field_group_type
                  field: field_group_type_target_id
                  relationship: none
                  group_type: group
                  admin_label: ''
                  plugin_id: taxonomy_index_tid
                  operator: or
                  value: { }
                  group: 1
                  exposed: true
                  expose:
                    operator_id: field_group_type_target_id_op
                    label: 'Type'
                    description: ''
                    use_operator: false
                    operator: field_group_type_target_id_op
                    operator_limit_selection: false
                    operator_list: { }
                    identifier: field_group_type_target_id
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                      anonymous: '0'
                      administrator: '0'
                      contentmanager: '0'
                      verified: '0'
                      sitemanager: '0'
                    reduce: false
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
                  reduce_duplicates: false
                  vid: group_type
                  type: select
                  hierarchy: false
                  limit: true
                  error_message: true
