dependencies:
  module:
    - taxonomy_access_fix
items:
  user.role.authenticated:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view terms in group_type'
          - 'view term names in group_type'
          - 'select terms in group_type'
