<?php
/**
 * @file
 * The Social post module.
 */
use Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_post_form_post_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['field_recipient_user']['#attributes']['class'][] = 'browser-default';
  $form['field_visibility']['#attributes']['class'][] = 'browser-default';
}