core.entity_view_display.post.photo.featured:
  expected_config: { }
  update_actions:
    delete:
      content:
        field_album:
          type: social_album_entity_reference_label
          weight: 4
          region: content
          label: hidden
          settings:
            link: true
          third_party_settings: { }
