core.entity_form_display.post.photo.default:
  expected_config:
    content:
      field_post:
        settings:
          placeholder: 'Say something about this photo'
  update_actions:
    change:
      content:
        field_post:
          settings:
            placeholder: 'Say something about these image(s)'
core.entity_form_display.post.photo.group:
  expected_config:
    content:
      field_post:
        settings:
          placeholder: 'Say something about this photo '
  update_actions:
    change:
      content:
        field_post:
          settings:
            placeholder: 'Say something about these image(s)'
core.entity_form_display.post.photo.profile:
  expected_config:
    content:
      field_post:
        settings:
          placeholder: 'Say something about this photo '
  update_actions:
    change:
      content:
        field_post:
          settings:
            placeholder: 'Say something about these image(s)'
