field.field.activity.activity.field_activity_entity:
  expected_config:
    settings: {  }
  update_actions:
    change:
      settings: {  }
field.storage.activity.field_activity_entity:
  expected_config:
    settings:
      entity_type_ids: { }
  update_actions:
    change:
      settings:
        entity_type_ids: {  }
