<?php

/**
 * @file
 * Contains template_mapper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function template_mapper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the template_mapper module.
    case 'help.page.template_mapper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Maps existing theme hook suggestions to your template files') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function template_mapper_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function template_mapper_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  $template_mapper_service = \Drupal::service('template_mapper');
  $suggestions = $template_mapper_service->performMapping($suggestions, $hook);
}
