# Schema for the configuration files of the Social Blue theme.
socialblue.settings:
  type: theme_settings
  label: 'socialblue settings'
  mapping:
    font_primary:
      type: string
      label: 'Font primary'
    card_radius:
      type: string
      label: 'Card radius'
    hero_gradient_opacity:
      type: integer
      label: 'Hero gradient opacity'
    form_control_radius:
      type: string
      label: 'Form control radius'
    button_radius:
      type: string
      label: 'Button radius'
    color_primary:
      type: string
      label: 'Color primary'
    color_secondary:
      type: string
      label: 'Color secondary'
    color_accent:
      type: string
      label: 'Color accent'
    color_accent_text:
      type: string
      label: 'Color accent text'
    color_link:
      type: string
      label: 'Color link'
    color_navbar_bg:
      type: string
      label: 'Color navbar background'
    color_navbar_text:
      type: string
      label: 'Color navbar text'
    color_navbar_active_bg':
      type: string
      label: 'Color navbar active background'
    color_navbar_active_text':
      type: string
      label: 'Color navbar active text'
    color_navbar_sec_bg':
      type: string
      label: 'Color navbar secondary background'
    color_navbar_sec_text':
      type: string
      label: 'Color navbar secondary text'
    second_line_navbar_bg:
      type: string
      label: 'Second line navigation background'
    second_line_navbar_text:
      type: string
      label: 'Second line navigation text'
    second_line_navbar_active_bg:
      type: string
      label: 'Second line navigation active item background'
    second_line_navbar_active_text:
      type: string
      label: 'Second line navigation active item text'
    content_entity_form_style:
      type: string
      label: 'Content entity form style'
