<?php

/**
 * @file
 * The Social Content Report module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function social_content_report_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get all 'report_' flags.
  $report_types = \Drupal::service('social_content_report.content_report_service')->getReportFlagTypes();

  // Add each report type form.
  $report_forms = [];
  foreach ($report_types as $report_type) {
    $report_forms[] = 'flagging_' . $report_type . '_add_form';
    $report_forms[] = 'flagging_' . $report_type . '_edit_form';
  }

  if (in_array($form_id, $report_forms, FALSE)) {
    $terms = \Drupal::service('config.factory')->get('social_content_report.settings')
      ->get('reasons_with_text');

    foreach ($terms as $term_id => $enabled) {
      if ($enabled) {
        // Only show the reason input field if it is enabled for the reason.
        $form['field_other_reason']['#states']['visible'][] = [
          ':input[name="field_reason"]' => [
            'value' => $term_id,
          ],
        ];
      }
    }

    // Add some validation if the reason field is mandatory.
    if (\Drupal::config('social_content_report.settings')->get('mandatory_reason')) {
      $form['#validate'][] = 'social_content_report_mandatory_reason_validate';
    }
  }
}

/**
 * Validation so the reason description field has content when it is mandatory.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form State with the submitted values.
 */
function social_content_report_mandatory_reason_validate(array $form, FormStateInterface $form_state) {
  $terms = \Drupal::service('config.factory')->get('social_content_report.settings')
    ->get('reasons_with_text');

  foreach ($terms as $term_id => $enabled) {
    if ($enabled && (int) $form_state->getValue('field_reason')[0]['target_id'] === $term_id
    && empty($form_state->getValue('field_other_reason')[0]['value'])) {
      $form_state->setErrorByName('field_other_reason', t('A description of your report is mandatory.'));
    }
  }
}
