views.view.user_admin_people:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - flag.flag.follow_term
        module:
          - social_follow_taxonomy
      display:
        default:
          display_options:
            exposed_form:
              options:
                bef:
                  filter:
                    social_follow_taxonomy_follow_filter:
                      plugin_id: bef_select2
                      advanced:
                        sort_options: false
                        placeholder_text: Select...
                        rewrite:
                          filter_rewrite_values: ''
                        collapsible: false
                        is_secondary: false
          cache_metadata:
            tags:
              - 'flagging_list:follow_term'
        page_1:
          display_options:
            display_extenders:
              views_ef_fieldset:
                views_ef_fieldset:
                  options:
                    sort:
                      social_follow_taxonomy_follow_filter:
                        depth: '3'
                        id: social_follow_taxonomy_follow_filter
                        pid: container-5
                        type: filter
                        weight: '-76'
          cache_metadata:
            tags:
              - 'flagging_list:follow_term'
    change:
      display:
        default:
          display_options:
            filters:
              social_follow_taxonomy_follow_filter:
                expose:
                  label: Category
        page_1:
          display_options:
            display_extenders:
              views_ef_fieldset:
                views_ef_fieldset:
                  options:
                    sort:
                      container-5:
                        title: 'Content tags'
