<?php

/**
 * @file
 * The Social Album module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function social_album_entity_extra_field_info() {
  return [
    'node' => [
      'album' => [
        'display' => [
          'social_album_images' => [
            'label' => t('Images'),
            'visible' => FALSE,
          ],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_view().
 */
function social_album_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('social_album_images')) {
    $build['social_album_images'] = views_embed_view('albums', 'embed_album_overview');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_album_preprocess_node(&$variables) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];

  if (
    $node->bundle() === 'album' &&
    $variables['view_mode'] === 'teaser' &&
    views_get_view_result('albums', 'embed_album_cover', $node->id())
  ) {
    $variables['node_image'] = views_embed_view('albums', 'embed_album_cover', $node->id());
    $variables['no_image'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_album_preprocess_views_view(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];

  if (
    $view->id() === 'albums' &&
    $view->current_display === 'page_albums_overview'
  ) {
    $variables['#attached']['library'][] = 'social_album/social_album_teaser';
  }
}
