field.storage.block_content.field_sorting:
  expected_config: {  }
  update_actions:
    add:
      settings:
        allowed_values:
          -
            label: 'Event date'
            value: event_date
