items:
  views.view.search_groups:
    expected_config:
      display:
        default:
          display_options: { }
    update_actions:
      add:
        display:
          default:
            display_options:
              filters:
                group_type:
                  value:
                    secret_group: secret_group
              row:
                options:
                  view_modes:
                    'entity:group':
                      secret_group: teaser
