<?php

/**
 * @file
 * Contains social_content_translation.module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_form_alter().
 */
function social_content_translation_form_alter(array &$form, FormStateInterface $form_state): void {
  // We need to set correct default value for "langcode" as users can
  // create content in different from default language.
  if (method_exists($form_state->getFormObject(), 'getEntity')) {
    /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
    $form_object = $form_state->getFormObject();
    $entity = $form_object->getEntity();

    if (!$entity instanceof ContentEntityInterface) {
      return;
    }

    if (!$entity->isNew()) {
      return;
    }

    if (empty($form['langcode']) || Element::isVisibleElement($form['langcode'])) {
      return;
    }

    if (!isset($form['langcode']['widget'][0]['value']['#default_value'])) {
      return;
    }

    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $form['langcode']['widget'][0]['value']['#default_value'] = $language;

  }
}
