dependencies:
  module:
    - social_profile
items:
  views.view.user_event_invites:
    expected_config: { }
    update_actions:
      delete:
        display:
          default:
            display_options:
              access: { }
      change:
        display:
          default:
            display_options:
              access:
                type: social_profile_pages_access
                options: { }
