metatag.settings:
  expected_config: {  }
  update_actions:
    delete:
      entity_type_groups:
        group:
          closed_group: { }
          open_group: { }
          public_group: { }
        group_content:
          closed_group-group_node-event: { }
          closed_group-group_node-topic: { }
          open_group-group_node-event: { }
          open_group-group_node-topic: { }
          public_group-group_node-event: { }
          public_group-group_node-topic: { }
