<?php

/**
 * @file
 * The social profile manager notes module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter().
 */
function social_profile_manager_notes_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $profile_forms = [
    'comment_manager_note_form',
  ];

  if (in_array($form_id, $profile_forms)) {
    if (!\Drupal::currentUser()->hasPermission('edit field manager notes')) {
      $form['comment_body']['#access'] = FALSE;
      unset($form["actions"]);
    }
    else {
      unset($form['actions']['preview']);
      // Originally it is a TranslatableMarkup
      $form['actions']['submit']['#value'] = "Leave remark";
      $form['#attached']['library'][] = 'social_profile_manager_notes/manager_notes';
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function social_profile_manager_notes_comment_view_alter(array &$build, EntityInterface $entity, EntityViewDisplay $display) {

}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function social_profile_manager_notes_profile_view_alter(array &$build, EntityInterface $entity, EntityViewDisplay $display) {

  $user = \Drupal::currentUser();

  if (!\Drupal::currentUser()->hasPermission('view field manager notes')) {
    unset($build["field_manager_notes"]);
  }

}
