<?php

/**
 * @file
 * The social profile manager notes install file.
 */

use Drupal\search_api\Entity\Index;
use Drupal\user\Entity\User;

/**
 * Implements hook_install().
 */
function social_profile_manager_notes_install() {

  $roles = [
    'sitemanager',
  ];
  $permissions = [
    'edit field manager notes',
    'view field manager notes',
  ];
  foreach ($roles as $role) {
    user_role_grant_permissions($role, $permissions);
  }

}
