core.entity_form_display.taxonomy_term.social_tagging.default:
  expected_config: {  }
  update_actions:
    change:
      content:
        field_category_usage:
          type: social_tagging_usage
          weight: 1
          region: content
          settings: { }
          third_party_settings: { }
    add:
      dependencies:
        config:
          - field.field.taxonomy_term.social_tagging.field_category_usage
      hidden:
        description: true
        path: true
    delete:
      content:
        description: {}
        path: {}
core.entity_view_display.taxonomy_term.social_tagging.default:
  expected_config: {  }
  update_actions:
    change:
      content:
        field_category_usage:
          type: social_tagging_usage_formatter
          label: above
          settings: { }
          third_party_settings: { }
          weight: 0
          region: content
    add:
      dependencies:
        config:
          - field.field.taxonomy_term.social_tagging.field_category_usage
