views.view.social_group_invitations:
  expected_config: {  }
  update_actions:
    change:
      base_table: group_relationship_field_data
      display:
        default:
          display_options:
            fields:
              created:
                table: group_relationship_field_data
            relationships:
              gc__user:
                table: group_relationship_field_data
            arguments:
              gid:
                table: group_relationship_field_data

views.view.social_group_user_invitations:
  expected_config: {  }
  update_actions:
    change:
      base_table: group_relationship_field_data
      display:
        default:
          display_options:
            fields:
              gid:
                table: group_relationship_field_data
              uid:
                table: group_relationship_field_data
              created:
                table: group_relationship_field_data
              id:
                table: group_relationship_field_data
            relationships:
              gc__user:
                table: group_relationship_field_data
            arguments:
              entity_id:
                table: group_relationship_field_data
