views.view.social_group_user_invitations:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            fields:
              group_membership_count:
                relationship: none
                table: group_relationship
