block.block.membershipinvitenotification:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            closed_group: closed_group
            open_group: open_group
            public_group: public_group
    add:
      visibility:
        group_type:
          group_types:
            flexible_group: flexible_group

block.block.membershipinvitenotification_2:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            closed_group: closed_group
            open_group: open_group
            public_group: public_group
    add:
      visibility:
        group_type:
          group_types:
            flexible_group: flexible_group

block.block.membershiprequestsnotification:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            closed_group: closed_group
            open_group: open_group
            public_group: public_group
    add:
      visibility:
        group_type:
          group_types:
            flexible_group: flexible_group

block.block.membershiprequestsnotification_2:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            closed_group: closed_group
            open_group: open_group
            public_group: public_group
    add:
      visibility:
        group_type:
          group_types:
            flexible_group: flexible_group

message.template.invited_to_join_group:
  expected_config: {  }
  update_actions:
    delete:
      third_party_settings:
        activity_logger:
          activity_bundle_entities:
            group_content-closed_group-group_invitation: {  }
            group_content-open_group-group_invitation: {  }
            group_content-public_group-group_invitation: {  }
    add:
      third_party_settings:
        activity_logger:
          activity_bundle_entities:
            group_content-flexible_group-group_invitation: group_content-flexible_group-group_invitation
