<?php

/**
 * @file
 * The social_like module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 */
function social_like_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($display->getComponent('like_and_dislike')) {
    // Check if the current user has permission
    // if not, hide the like and dislike.
    if (!\Drupal::currentUser()->hasPermission('view like widget')) {
      unset($build['like_and_dislike']);
    }
  }
}
