<?php

/**
 * @file
 * Contains social_out_of_office.module.
 */

use Drupal\comment\CommentInterface;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\profile\Entity\ProfileInterface;
use Drupal\social_out_of_office\SocialOutOfOfficeHelperInterface;
use Drupal\social_post\Entity\PostInterface;

/**
 * @file
 * The Social Out of office module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function social_out_of_office_preprocess_profile(array &$variables): void {
  if ($variables['elements']['#view_mode'] === 'statistic') {
    /** @var \Drupal\profile\Entity\Profile $profile */
    $profile = $variables['profile'];

    /** @var \Drupal\social_out_of_office\SocialOutOfOfficeHelperInterface $ooo_helper */
    $ooo_helper = \Drupal::service('social_out_of_office.helper');

    // Check if user is out of office.
    if ($ooo_helper->isUserOutOfOffice($profile)) {
      // Set status message.
      $variables['profile_ooo_status'] = t('Currently out of office');

      // Retrieve, prepare and set a message from user profile.
      $message = $profile->get('field_profile_ooo_message')->getValue();
      $variables['profile_message_ooo'] = ['#markup' => $message[0]['value'] ?? ''];

      // If there is an alternative person we should show them out.
      if (!$profile->get('field_profile_ooo_alt_contact')->isEmpty()) {
        // Retrieve and show an alternative person, if filled.
        $alt_contact_person_user = $profile->get('field_profile_ooo_alt_contact')->referencedEntities()[0];

        /** @var \Drupal\profile\ProfileStorageInterface $profile_storage */
        $profile_storage = \Drupal::entityTypeManager()->getStorage('profile');

        /** @var \Drupal\profile\Entity\ProfileInterface $profile */
        $alt_contact_person = $profile_storage->loadByUser($alt_contact_person_user, SocialOutOfOfficeHelperInterface::PROFILE_TYPE);

        if ($alt_contact_person instanceof ProfileInterface) {
          /** @var \Drupal\social_profile\SocialProfileNameService $profile_name_service */
          $profile_name_service = \Drupal::service('social_profile.name_service');

          // Get generated profile name.
          $alt_contact_person_name = $profile_name_service->getProfileName($alt_contact_person);
          // Prepare contact person URL.
          $alt_contact_person_url = Url::fromRoute('social_user.stream', ['user' => $alt_contact_person->id()]);

          // Add extra variables with necessary data.
          $variables['profile_alt_contact_person_name'] = $alt_contact_person_name;
          $variables['profile_alt_contact_person_url'] = $alt_contact_person_url;
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_user().
 */
function social_out_of_office_preprocess_user(array &$variables): void {
  // Show status in private messaging thread if someone is out of office.
  if ($variables['elements']['#view_mode'] === 'private_message_author') {
    $current_user = \Drupal::currentUser()->getAccount();
    $user = $variables['elements']['#user'];

    if ($current_user->id() !== $user->id()) {
      /** @var \Drupal\profile\ProfileStorageInterface $profile_storage */
      $profile_storage = \Drupal::entityTypeManager()->getStorage('profile');

      /** @var \Drupal\profile\Entity\Profile $profile */
      $profile = $profile_storage->loadByUser($user, SocialOutOfOfficeHelperInterface::PROFILE_TYPE);

      if ($profile instanceof ProfileInterface) {
        /** @var \Drupal\social_out_of_office\SocialOutOfOfficeHelperInterface $ooo_helper */
        $ooo_helper = \Drupal::service('social_out_of_office.helper');

        // Check if user is out of office.
        if ($ooo_helper->isUserOutOfOffice($profile)) {
          // Retrieve out of office dates.
          $dates = $ooo_helper->getOutOfOfficeDates($profile);

          $suffix = ' ' . t('is out of office from @start_date to @end_date', [
            '@start_date' => $dates['start'],
            '@end_date' => $dates['end'],
          ]);
          $suffix .= $variables['content']['linked_username']['#suffix'];
          $variables['content']['linked_username']['#suffix'] = $suffix;
        }
      }

      // Add OoO cache tag.
      $variables['#cache']['tags'][] = 'ooo_dates:uid:' . $user->id();
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function social_out_of_office_entity_presave(EntityInterface $entity): void {
  // Show message about users that out of office if someone mentioned them in
  // post or comment.
  if (
    !($entity instanceof PostInterface) &&
    !($entity instanceof CommentInterface)
  ) {
    return;
  }

  $post_comment_related_users = [];

  // Comment entity type.
  if ($entity instanceof CommentInterface) {
    $body_value = $entity->get('field_comment_body')->getValue();

    // If commented entity author is OoO we should show message about that.
    /** @var \Drupal\social_post\Entity\PostInterface $commented_entity */
    /** @var \Drupal\node\NodeInterface $commented_entity */
    $commented_entity = $entity->getCommentedEntity();
    if ($commented_entity !== NULL) {
      $post_comment_related_users[] = $commented_entity->getOwnerId();
    }

    // If parent comment author is OoO we should show message about that.
    $parent_comment = $entity->getParentComment();
    if ($parent_comment) {
      $post_comment_related_users[] = $parent_comment->getOwnerId();
    }
  }
  // Post entity type.
  else {
    $body_value = $entity->get('field_post')->getValue();
  }

  /** @var \Drupal\social_out_of_office\SocialOutOfOfficeHelperInterface $ooo_helper */
  $ooo_helper = \Drupal::service('social_out_of_office.helper');

  // Make sure that the module social_mentions is enabled before use it's
  // service.
  if (\Drupal::moduleHandler()->moduleExists('social_mentions')) {
    /** @var \Drupal\social_mentions\SocialMentionsHelperInterface $social_mentions_helper */
    $social_mentions_helper = \Drupal::service('social_mentions.helper');

    // Prepare body value.
    $body_value = $body_value[0]['value'] ?? '';

    // Retrieve mentions from body.
    $mentions = $social_mentions_helper->getMentions($body_value);
    if (!empty($mentions)) {
      // Show OoO messages for mentioned users.
      $ooo_helper->showOutOfOfficeStatusMessages($mentions, TRUE);
    }
  }

  // Show OoO messages for related users.
  $ooo_helper->showOutOfOfficeStatusMessages($post_comment_related_users);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function social_out_of_office_form_private_message_add_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // Make sure that we add custom submit handler exactly for create new chat
  // with user since we already add message about out of office for existing
  // chats.
  // @see social_out_of_office_preprocess_user()
  if (\Drupal::routeMatch()->getRouteName() === 'private_message.private_message_create') {
    $form['actions']['submit']['#submit'][] = 'social_out_of_office_add_notice_about_users_ooo';
  }
}

/**
 * Submit function for 'form_private_message_add' form.
 */
function social_out_of_office_add_notice_about_users_ooo(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\social_out_of_office\SocialOutOfOfficeHelperInterface $ooo_helper */
  $ooo_helper = \Drupal::service('social_out_of_office.helper');

  // Check if any of members is out of office and add status message if yes.
  $members_uids = array_column($form_state->getValue('members'), 'target_id');

  // Show OoO messages for related profiles.
  $ooo_helper->showOutOfOfficeStatusMessages($members_uids);
}

/**
 * Implements hook_FORM_ID_form_alter().
 */
function social_out_of_office_form_profile_profile_edit_form_alter(array &$form): void {
  // Add Out of office message validation.
  $form['#validate'][] = 'social_out_of_office_data_validate';
  // Attach custom library.
  $form['#attached']['library'][] = 'social_out_of_office/admin';
}

/**
 * Validator for OoO data.
 */
function social_out_of_office_data_validate(array &$form, FormStateInterface $form_state): void {
  $start_date = $form_state->getValue('field_profile_ooo_start_date')[0]['value'] ?? NULL;
  $end_date = $form_state->getValue('field_profile_ooo_end_date')[0]['value'] ?? NULL;

  // Make sure that both dates are filled and not only one.
  if (
    ($start_date !== NULL && $end_date === NULL) ||
    ($start_date === NULL && $end_date !== NULL)
  ) {
    $form_state->setErrorByName($start_date ? 'field_profile_ooo_start_date' : 'field_profile_ooo_end_date', t('Both start and end date should be filled.'));
  }

  // Make sure user is not able to set start date later that end date.
  if (
    $start_date !== NULL &&
    $end_date !== NULL &&
    ($form_state->getValue('field_profile_ooo_start_date')[0]['value'] > $form_state->getValue('field_profile_ooo_end_date')[0]['value'])
  ) {
    $form_state->setErrorByName('field_profile_ooo_start_date', t('Start date cannot be later than end date.'));
  }

  // Show error if message has more characters than 240.
  $message = $form_state->getValue('field_profile_ooo_message');
  $message = strip_tags($message[0]['value'] ?? '');
  if (strlen($message) > SocialOutOfOfficeHelperInterface::MESSAGE_MAX_LENGTH) {
    $form_state->setErrorByName('field_profile_ooo_message', t('The maximum length for the out of office message is @max_length characters.', [
      '@max_length' => SocialOutOfOfficeHelperInterface::MESSAGE_MAX_LENGTH,
    ]));
  }

  // If user filled Message or Alternative contact person we should require fill
  // dated as well.
  if (
    (!empty($message) || !empty($form_state->getValue('field_profile_ooo_alt_contact')[0]['value'])) &&
    $start_date === NULL &&
    $end_date === NULL
  ) {
    $form_state->setErrorByName('field_profile_ooo_start_date', t('Start and end dates should also be filled.'));
  }

  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\profile\Entity\Profile $profile */
  $profile = $form_object->getEntity();

  // Invalidate OoO cache tage.
  Cache::invalidateTags(['ooo_dates:uid:' . $profile->getOwnerId()]);
}
