core.entity_view_display.user.user.default:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.user.user.full:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }
