views.view.user_admin_people:
  expected_config: { }
  update_actions:
    change:
      display:
        default:
          display_options:
            filters:
              id:
                expose:
                  label: Hubs
