views.view.user_admin_people:
  expected_config:
    display:
      default:
        display_options:
          filters:
            created:
              expose:
                operator_limit_selection: true
                operator_list:
                  '<': '<'
                  '>': '>'
                  between: between
                remember_roles:
                  verified: '0'
            login:
              expose:
                operator_limit_selection: true
                operator_list:
                  '<': '<'
                  '>': '>'
                  between: between
                remember_roles:
                  verified: '0'
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              created:
                expose:
                  operator_list:
                    '<': '<'
                    '>': '>'
                    between: between
                  remember_roles:
                    verified: '0'
              login:
                expose:
                  operator_list:
                    '<': '<'
                    '>': '>'
                    between: between
                  remember_roles:
                    verified: '0'
    change:
      display:
        default:
          display_options:
            filters:
              created:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              login:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
