__global_actions:
  import_configs:
    - media.type.video_recording_link
    - field.storage.media.field_media_links
    - field.field.media.video_recording_link.field_media_links
    - core.entity_form_display.media.video_recording_link.default
    - core.entity_view_display.media.video_recording_link.default
