__global_actions:
  import_configs:
    - field.field.group.course_advanced.field_grequest_form_required
    - field.field.group.course_advanced.field_grequest_form_description
    - field.field.group.course_advanced.field_grequest_form_default
