<?php

/**
 * @file
 * Install, update and uninstall functions for the social_image_copyright module.
 */

/**
 * Implements hook_install().
 *
 * Perform actions on install related to the image copyright fields.
 */
function social_image_copyright_install() {

}


/**
 * Implements hook_uninstall().
 *
 * Perform actions on uninstall related to the image copyright fields.
 */
function social_image_copyright_uninstall() {

}
