<?php

/**
 * @file
 * Module file for activity_viewer.
 */

/**
 * Implements hook_views_data().
 */
function activity_viewer_views_data() {
  $data['activity']['activity_filter_personalised_homepage_filter'] = [
    'title' => t('Filter on activities for the personalised homepage.'),
    'filter' => [
      'title' => t('Filter activities for personalised homepage'),
      'help' => t('Filter on activities for personalised homepage.'),
      'field' => 'field_visibility',
      'id' => 'activity_filter_personalised_homepage',
    ],
  ];
  $data['activity']['activity_explore_visibility_access_filter'] = [
    'title' => t('Filter on activities for the Explore page.'),
    'filter' => [
      'title' => t('Filter activities for Explore page'),
      'help' => t('The explore page shows content not directly related to you, 
      so placed in a groups you are not a member of.'),
      'field' => 'field_visibility',
      'id' => 'activity_explore_visibility_access',
    ],
  ];
  return $data;
}
