views.view.search_all_autocomplete:
  expected_config:
    display:
      default:
        display_options:
          fields:
            id:
              alter:
                alter_text: false
                text: ''
              fallback_options:
                prefix: group/
            nid:
              alter:
                alter_text: false
                text: ''
              fallback_options:
                prefix: node/
            uid:
              alter:
                alter_text: false
                text: ''
              fallback_options:
                prefix: user/
  update_actions:
    change:
      display:
        default:
          display_options:
            fields:
              id:
                alter:
                  alter_text: true
                  text: 'group/{{ id }}'
                fallback_options:
                  prefix: ''
              nid:
                alter:
                  alter_text: true
                  text: 'node/{{ nid }}'
                fallback_options:
                  prefix: ''
              uid:
                alter:
                  alter_text: true
                  text: 'user/{{ uid }}'
                fallback_options:
                  prefix: ''
