core.entity_view_display.node.topic.small_teaser:
  expected_config:
    content:
      flag_follow_content: { }
  update_actions:
    add:
      hidden:
        flag_follow_content: true
    delete:
      content:
        flag_follow_content: { }
