views.view.following:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
