<?php

namespace Drupal\activity_send_email\Plugin\EmailFrequency;

use Drupal\activity_send_email\EmailFrequencyBase;

/**
 * Define a concrete class for a immediate emails.
 *
 * @EmailFrequency(
 *   id = "immediately",
 *   name = @Translation("Send e-mails immediately"),
 *   interval = 0
 * )
 */
class Immediately extends EmailFrequencyBase {

  public function getInterval() {
    return parent::getInterval(); // TODO: Change the autogenerated stub
  }
}
