field.widget.settings.social_tag_split:
  type: field.widget.settings.options_select
  label: 'Tag Split Widget'
  mapping:
    display_title:
      type: bool
      label: 'Display title'

field.formatter.settings.social_tag_split:
  type: field.formatter.settings.entity_reference_label
