<?php

/**
 * @file
 * The Social topic module.
 */

/**
* Prepares variables for node templates.
*
* Default template: node.html.twig.
*
* Most themes use their own copy of node.html.twig. The default is located
* inside "/core/modules/node/templates/node.html.twig". Look in there for the
* full list of variables.
*
* @param array $variables
*   An associative array containing:
*   - elements: An array of elements to display in view mode.
*   - node: The node object.
*   - view_mode: View mode; e.g., 'full', 'teaser', etc.
*/
function social_topic_preprocess_node(&$variables) {
  if ($variables['view_mode'] === 'teaser') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = $variables['node'];
    if ($node->getType() === 'topic') {
      $topic_type = $node->get('field_topic_type');
      $topic_type_entities = $topic_type->referencedEntities();
      if (count($topic_type_entities) === 1) {
        foreach ($topic_type_entities as $topic) {
          $variables['metadata'] = t('in @topic', array('@topic' => $topic->link()));
        }
      }
      else {
        $variables['metadata'] = NULL;
      }
    }
  }
}

/**
 * Implements hook_form_form_ID_alter().
 *
 * Enhance the exposed filter form of the topic overview.
 */
function social_topic_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-topics-page-1') {
    $form['type']['#options']['All'] = t('All types');

    $account_uid = \Drupal::routeMatch()->getParameter('user');
    $current_uid = \Drupal::currentUser()->id();

    if ($account_uid !== $current_uid) {
      $form['status']['#access'] = FALSE;
    }
    else {
      $form['status']['#options']['All'] = t('Published or not published');
      $form['status']['#options']['1'] = t('Published');
      $form['status']['#options']['0'] = t('Not published');
    }

    // @todo move the sort form elements to a different block.
    $form['sort_by']['#access'] = FALSE;
    $form['sort_order']['#title'] = t('Sorted by publish date');

    // Enable the reset button.
    // @todo make sure the block content refreshes on submit as well (AJAX).
    $form['actions']['reset']['#access'] = TRUE;
  }
}

/**
 * Implements hook_block_view_alter().
 *
 * Add a title to the exposed filter block on the topics overview.
 */
function social_topic_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // @todo check out why this happens, is this is a views bug?
  if ($build['#plugin_id'] === 'views_exposed_filter_block:topics-page_1') {
    $build['#configuration']['label'] = $build['#configuration']['views_label'];
  }

}
