# Schema for the configuration files of the Social EDA (Experimental) module.
social_eda.settings:
  type: config_object
  label: 'Social EDA (Experimental) settings'
  mapping:
    example:
      type: string
      label: 'Example'
