# Schema for the configuration files of the Social EDA module.
social_eda.settings:
  type: config_object
  label: 'Social EDA settings'
  mapping:
    example:
      type: string
      label: 'Example'
