<?php

/**
 * @file
 * Install, update and uninstall functions for the social_lets_connect module.
 */

/**
 * Rebuild the `menu_tree` storage.
 */
function social_lets_connect_update_11801(): void {
  // Rebuilding the menu tree storage ensures the db table `menu_tree` is
  // updated, which should ensure social_lets_connect now falls under the
  // social_core.dashboard menu.
  \Drupal::service('plugin.manager.menu.link')->rebuild();
}
