social_comment.comment_settings:
  type: config_object
  label: 'Social Comment Settings'
  mapping:
    redirect_comment_to_entity:
      type: boolean
      label: 'Redirect a comment view to its parent entity'
