views.view.event_manage_enrollment_invites:
  expected_config: { }
  update_actions:
    delete:
      display:
        default:
          display_options:
            style:
              options:
                columns:
                  field_profile_organization: ~
                info:
                  field_profile_organization: ~
