views.view.event_manage_enrollment_invites:
  expected_config: { }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              langcode: { }
