social_event_invite.settings:
  expected_config: {  }
  update_actions:
    change:
      invite_message: "<p>Hi</p>\r\n<p>I would like to invite you to join my event <strong>[node:title]</strong> on <strong>[site:name]</strong>.</p>\r\n<p>Kind regards,<br/>[user:display-name]</p>\r\n<table class=\"btn-wrap\">\r\n<tbody>\r\n<tr>\r\n<td class=\"align-center\">\r\n<a class=\"btn-link btn-link-bg btn-link-one\" href=\"[social_event_invite:register_link]\">View event</a>\r\n</td>\r\n<td class=\"align-center\">\r\n<a class=\"btn-link btn-link-bg btn-link-one\" href=\"[site:url]\">About [site:name]</a>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>"
