views.view.user_event_invites:
  expected_config:
    display:
      default:
        display_options:
          access:
            type: none
  update_actions:
    delete:
      display:
        default:
          display_options:
            access: { }
    add:
      display:
        default:
          display_options:
            access:
              type: social_profile_pages_access
              options: { }
