social_event_invite.settings:
  expected_config: {  }
  update_actions:
    add:
      invite_helper: '<p>The message above is edited by the community managers. Please contact them for questions and ideas</p>'
