social_event_invite.settings:
  expected_config: {  }
  update_actions:
    delete:
      invite_group_types:
        open_group: {  }
        public_group: {  }
        closed_group: {  }
        secret_group: {  }
