views.view.user_event_invites:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              langcode: ~
            relationships:
              field_event: ~
