dependencies:
  module:
    - taxonomy_access_fix
items:
  user.role.sitemanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view social_tagging'
          - 'view terms in social_tagging'
          - 'select terms in social_tagging'
          - 'view term names in social_tagging'
          - 'create terms in social_tagging'
          - 'edit terms in social_tagging'
          - 'delete terms in social_tagging'
  user.role.contentmanager:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view social_tagging'
          - 'view terms in social_tagging'
          - 'select terms in social_tagging'
          - 'view term names in social_tagging'
          - 'create terms in social_tagging'
          - 'edit terms in social_tagging'
          - 'delete terms in social_tagging'
  user.role.verified:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view social_tagging'
          - 'view terms in social_tagging'
          - 'select terms in social_tagging'
          - 'view term names in social_tagging'
  user.role.authenticated:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view social_tagging'
          - 'view terms in social_tagging'
          - 'select terms in social_tagging'
          - 'view term names in social_tagging'
  user.role.anonymous:
    expected_config:
      permissions: { }
    update_actions:
      add:
        permissions:
          - 'view social_tagging'
