dependencies:
  config:
    - facets.facet.social_tagging_users
items:
  views.view.search_users:
    expected_config:
      display:
        default:
          display_options: { }
    update_actions:
      add:
        dependencies:
          module:
            - facets
        display:
          default:
            display_options:
              filters:
                facets:
                  id: facets
                  table: search_api_index_social_all
                  field: facets
                  relationship: none
                  group_type: group
                  admin_label: ''
                  plugin_id: facets_filter
                  operator: '='
                  value: ''
                  group: 1
                  exposed: true
                  expose:
                    operator_id: ''
                    label: ''
                    description: ''
                    use_operator: false
                    operator: ''
                    operator_limit_selection: false
                    operator_list: { }
                    identifier: facet_y7wzdJtr
                    required: false
                    remember: false
                    multiple: false
                    remember_roles:
                      authenticated: authenticated
                  is_grouped: false
                  group_info:
                    label: ''
                    description: ''
                    identifier: ''
                    optional: true
                    widget: select
                    multiple: false
                    remember: false
                    default_group: All
                    default_group_multiple: { }
                    group_items: { }
                  facets:
                    social_tagging_users: social_tagging_users
                  label_display: visible
