<?php

/**
 * @file
 * Contains social_graphql_oauth2.module.
 */

use Drupal\social_graphql_oauth2\Entity\Server;

/**
 * Implements hook_entity_type_build().
 */
function social_graphql_oauth2_entity_type_build(array &$entity_types): void {
  if (array_key_exists('graphql_server', $entity_types)) {
    /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
    $entity_types['graphql_server']->setClass(Server::class);
  }
}
