extend input CreateTopicInput {
  """
  The organization this topic should belong to if any.
  May optionally be posted to additional organizations.
  """
  organizations: ContentInOrganizationInput
}

extend input UpdateTopicInput {
  """
  The organization this topic should belong to if any.
  May optionally be posted to additional organizations.
  If omitted, organizations remain unchanged.
  To remove the topic from all organizations, set: organizations: null.
  """
  organizations: ContentInOrganizationInput
}
