<?php

/**
 * @file
 * Contains activity_basics.module..
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\activity_creator\ActivityInterface;
use Drupal\activity_send_email\Plugin\ActivityDestination\EmailActivityDestination;

/**
 * Implements hook_form_FORM_ID_alter() for user_form().
 */
function activity_send_email_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $account = \Drupal::routeMatch()->getParameter('user');
  if (is_object($account)) {
    $form['email_notifications'] = [
      '#type' => 'fieldset',
      '#title' => t('Email notifications'),
      '#tree' => TRUE,
    ];

    $email_message_templates = EmailActivityDestination::getSendEmailMessageTemplates();
    $user_email_settings = EmailActivityDestination::getSendEmailUserSettings($account);

    $all_email_message_keys = array_keys($email_message_templates);
    $all_email_message_values = array_values($email_message_templates);

    $message_to_me = [
      $all_email_message_keys[7] => $all_email_message_values[7],
      $all_email_message_keys[5] => $all_email_message_values[5],
      $all_email_message_keys[6] => $all_email_message_values[6],
      $all_email_message_keys[4] => $all_email_message_values[4],
      $all_email_message_keys[3] => $all_email_message_values[3],
      $all_email_message_keys[2] => $all_email_message_values[2],
    ];
    $what_manage = [
      $all_email_message_keys[0] => $all_email_message_values[0],
    ];
    $what_follow = [
      $all_email_message_keys[1] => $all_email_message_values[1],
    ];

    $notification_options = [
      0 => t('- None -'),
      1 => t('Immediately'),
      2 => t('Daily'),
      3 => t('Weekly'),
    ];

    // The email notification settings for Message to me.
    $form['email_notifications']['message_to_me'] = [
      '#type' => 'details',
      '#title' => t('<h5>Message to me</h5>'),
      '#attributes' => [
        'class' => ['form-group'],
      ],
    ];
    // Build the message to me section.
    foreach ($message_to_me as $key => $title) {
      $form['email_notifications']['message_to_me'][$key] = [
        '#type' => 'select',
        '#title' => $title,
        '#options' => $notification_options,
        '#default_value' => isset($user_email_settings[$key]) ? $user_email_settings[$key] : 1,
        '#attributes' => [
          'class' => ['form-group-inline'],
        ],
      ];
    }
    // The email notification settings for What I manage.
    $form['email_notifications']['what_manage'] = [
      '#type' => 'details',
      '#title' => t('<h5>What I manage</h5>'),
      '#attributes' => [
        'class' => ['form-group'],
      ],
    ];
    // Build the what I manage section.
    foreach ($what_manage as $key => $title) {
      $form['email_notifications']['what_manage'][$key] = [
        '#type' => 'select',
        '#title' => $title,
        '#options' => $notification_options,
        '#default_value' => isset($user_email_settings[$key]) ? $user_email_settings[$key] : 1,
        '#attributes' => [
          'class' => ['form-group-inline'],
        ],
      ];
    }

    // The email notification settings for What I follow.
    $form['email_notifications']['what_follow'] = [
      '#type' => 'details',
      '#title' => t('<h5>What I follow</h5>'),
      '#attributes' => [
        'class' => ['form-group'],
      ],
    ];
    // Build the what I follow section.
    foreach ($what_follow as $key => $title) {
      $form['email_notifications']['what_follow'][$key] = [
        '#type' => 'select',
        '#title' => $title,
        '#options' => $notification_options,
        '#default_value' => isset($user_email_settings[$key]) ? $user_email_settings[$key] : 1,
        '#attributes' => [
          'class' => ['form-group-inline'],
        ],
      ];
    }

    // Submit function to save send email settings.
    $form['actions']['submit']['#submit'][] = '_activity_send_email_form_user_form_submit';
  }
}

/**
 * Form submit for user_form.
 *
 * @param array $form
 *   Commnent on a post form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state interface.
 */
function _activity_send_email_form_user_form_submit(array $form, FormStateInterface $form_state) {
  $account = \Drupal::routeMatch()->getParameter('user');
  $values = $form_state->getValue('email_notifications');

  $values = array_merge(
    $values['message_to_me'],
    $values['what_manage'],
    $values['what_follow']
  );

  if (is_object($account) && !empty($values)) {
    EmailActivityDestination::setSendEmailUserSettings($account, $values);
  }

}

/**
 * Implements hook_mail().
 */
function activity_send_email_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  $variables = [
    '%site_name' => \Drupal::config('system.site')->get('name'),
  ];

  switch ($key) {
    case 'activity_send_email':
      // Mail subject.
      $message['subject'] = t('Notification from %site_name', $variables, $options);
      // Mail body.
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function activity_send_email_activity_insert(ActivityInterface $activity) {

  $destinations = $activity->getDestinations();
  if (in_array('email', $destinations)) {
    /* @var $activity_send_factory Drupal\activity_send\Plugin\ActivitySendManager */
    $activity_send_factory = \Drupal::service('plugin.manager.activity_send.processor');
    // Trigger the create action for entities.
    /* @var $create_action Drupal\activity_send\Plugin\ActivitySend\CreateActivitySend */
    $create_action = $activity_send_factory->createInstance('email_activity_send');
    $create_action->create($activity);
  }

}
