group.role.course_advanced-member:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        social_group:
          hubs_filter: true
          full_label: 'Advanced Course member'
group.role.course_advanced-group_manager:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        social_group:
          hubs_filter: true
          full_label: 'Advanced Course leader'
