views.view.group_per_type:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - group.type.course_advanced
      display:
        course_group:
          display_options:
            filters:
              type:
                value:
                  course_basic: course_advanced
              type_1:
                value:
                  course_basic: course_advanced
