dependencies:
  modules:
    - metatag
items:
  metatag.metatag_defaults.group:
    expected_config: { }
    update_actions:
      change:
        tags:
          description: '[group:field_group_description]'
          title: '[group:title]'
          og_country_name: '[group:field_group_address:country_name]'
          og_description: '[group:field_group_description]'
          og_image: '[group:field_group_image:entity:url]'
          og_locality: '[group:field_group_address:locality]'
          og_postal_code: '[group:field_group_address:postal_code]'
          og_site_name: '[site:name]'
          og_street_address: '[group:field_group_address:address_line1]'
          og_title: '[group:title]'
          og_url: '[group:url]'
          twitter_cards_description: '[group:field_group_description]'
          twitter_cards_image: '[group:field_group_image:entity:url]'
          twitter_cards_title: '[group:title]'
          twitter_cards_type: summary_large_image
