<?php

/**
 * @file
 * Contains social_devel.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_devel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the Social Devel module.
    case 'help.page.social_devel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Social development modules.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_default_route_group_tabs_alter().
 */
function social_devel_social_group_default_route_tabs_alter(&$tabs) {
  // Unset the 'Devel' option as default group tab.
  unset($tabs['devel.entities:group.devel_tab']);
}

/**
 * Implements hook_social_path_manager_group_tabs_alter().
 */
function social_devel_social_path_manager_group_tabs_alter(array &$tabs) {
  // Unset the 'Devel' option as default group tab.
  unset($tabs['devel.entities:group.devel_tab']);
}
