<?php

/**
 * @file
 * The Social comment module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Enhance the comment form.
 */
function social_comment_form_comment_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Change value of 'Save' button.
  $form['actions']['submit']['#value'] = t('Comment');
}

/**
 * Implements hook_comment_links_alter().
 *
 * Alter the links of a comment.
 */
function social_comment_comment_links_alter(array &$links, $entity, array &$context) {
  // Remove reply links for comments deeper than 1.
  if (!empty($entity->getParentComment())) {
    unset($links['comment']['#links']['comment-reply']);
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function social_comment_query_comment_filter_alter(Drupal\Core\Database\Query\AlterableInterface &$query) {
  // Change sorting to newest reply shown on top.
  $expressions = &$query->getExpressions();
  if (isset($expressions['torder'])) {
    unset($expressions['torder']);
    $order = &$query->getOrderBy();
    unset($order['torder']);
    $query->orderBy('c.thread', 'DESC');
  }
}

/**
 * Implements hook_preprocess_comment().
 */
function social_comment_preprocess_comment(&$variables) {
  $comment = $variables['elements']['#comment'];
  // Display comment created date in format 'time ago'.
  $created_time_ago = \Drupal::service('date.formatter')
    ->formatTimeDiffSince($comment->getCreatedTime(), array('granularity' => 2));
  $variables['submitted'] = t('%time ago', array('%time' => $created_time_ago));
}

