field.field.block_content.custom_content_list.field_link:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.block_content.custom_content_list.field_subtitle:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
