core.entity_form_display.block_content.custom_content_list.default:
  expected_config:
    content:
      field_link:
        weight: 3
      field_plugin_field:
        weight: 1
      field_plugin_id:
        weight: 0
    third_party_settings:
      field_group:
        group_display_options:
          weight: 2
        group_filter_options:
          weight: 1
  update_actions:
    change:
      content:
        field_link:
          weight: 12
        field_plugin_field:
          weight: 5
        field_plugin_id:
          weight: 4
      third_party_settings:
        field_group:
          group_display_options:
            weight: 9
          group_filter_options:
            weight: 3
core.entity_view_display.block_content.custom_content_list.default:
  expected_config:
    content: {  }
  update_actions:
    change:
      content:
        entities:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 0
