core.entity_form_display.block_content.custom_content_list.default:
  expected_config:
    content:
      field_sorting:
        type: options_select
  update_actions:
    change:
      content:
        field_sorting:
          type: content_block_sorting
