core.entity_form_display.block_content.custom_content_list.default:
  expected_config:
    content:
      field_item_amount:
        weight: 11
      field_link:
        weight: 12
      field_sorting:
        weight: 10
    third_party_settings:
      field_group:
        group_display_options:
          children:
            - field_sorting
            - field_item_amount
          weight: 9
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_filter_options:
            children:
              - field_item_amount
    change:
      content:
        field_item_amount:
          weight: 10
        field_link:
          weight: 13
        field_sorting:
          weight: 12
      third_party_settings:
        field_group:
          group_display_options:
            children:
              - field_sorting
            weight: 11
