social_activity_filter.settings:
  type: config_object
  label: 'Social Activity Filter settings'
  mapping:
    vocabulary:
      type: array
      label: 'Taxonomy vocabularies'
    taxonomy_fields:
      type: array
      label: 'Taxonomy fields'
    blocks:
      type: array
      label: 'Views blocks'
