field.storage.taxonomy_term.field_topic_type_icon:
  langcode: en
  status: true
  dependencies:
    module:
      - options
      - taxonomy
  id: taxonomy_term.field_topic_type_icon
  field_name: field_topic_type_icon
  entity_type: taxonomy_term
  type: list_string
  settings:
    allowed_values: {  }
    allowed_values_function: 'social_topic_allowed_values_function'
  module: options
  locked: false
  cardinality: 1
  translatable: true
  indexes: {  }
  persist_with_no_fields: false
  custom_storage: false
field.field.taxonomy_term.topic_types.field_topic_type_icon:
  langcode: en
  status: true
  dependencies:
    config:
      - field.storage.taxonomy_term.field_topic_type_icon
      - taxonomy.vocabulary.topic_types
    module:
      - options
  id: taxonomy_term.topic_types.field_topic_type_icon
  field_name: field_topic_type_icon
  entity_type: taxonomy_term
  bundle: topic_types
  label: Icon
  description: ''
  required: true
  translatable: false
  default_value: {  }
  default_value_callback: 'social_topic_default_value_function'
  settings: {  }
  field_type: list_string
core.entity_form_display.taxonomy_term.topic_types.default:
  langcode: en
  status: true
  dependencies:
    config:
      - field.field.taxonomy_term.topic_types.field_topic_type_icon
      - taxonomy.vocabulary.topic_types
    module:
      - path
      - text
  id: taxonomy_term.topic_types.default
  targetEntityType: taxonomy_term
  bundle: topic_types
  mode: default
  content:
    description:
      type: text_textfield
      weight: 0
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    field_topic_type_icon:
      weight: 31
      settings: {  }
      third_party_settings: {  }
      type: options_select
      region: content
    name:
      type: string_textfield
      weight: -5
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    path:
      type: path
      weight: 30
      region: content
      settings: {  }
      third_party_settings: {  }
  hidden: {  }

