<?php

/**
 * @file
 * The Social Footer module.
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function social_footer_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  // Main module help for the social_footer module.
  if ($route_name === 'help.page.social_footer') {
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provides block based on the "Powered by Drupal" block from Drupal core.') . '</p>';
  }

  return $output;
}

/**
 * Function to set default footer block.
 */
function _social_footer_set_default_footer_logo_for_socialblue() {
  // Only when socialblue is default we continue.
  $config_factory = \Drupal::configFactory();
  if ($config_factory->get('system.theme')->get('default') === 'socialblue') {
    // Add default image.
    $block_config = $config_factory->getEditable('block.block.socialblue_footer_powered');
    $file_path = drupal_get_path('module', 'social_footer') . DIRECTORY_SEPARATOR . 'open_social_logo.png';
    $file_system = \Drupal::service('file_system');
    $uri = $file_system->copy($file_path, 'public://open_social_logo.png', FileSystemInterface::EXISTS_REPLACE);
    $media = File::create([
      'uri' => $uri,
    ]);
    $media->setPermanent();
    $media->save();
    // We just save the file id.
    $settings = $block_config->get('settings');
    $settings['logo'] = $media->id();
    $block_config->set('settings', $settings)->save();
  }
}
