<?php

/**
 * @file
 * Improved theme settings module install file.
 */

/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of improved_theme_settings.
 */
function improved_theme_settings_install() {
  // Set weight.
  module_set_weight('improved_theme_settings', 50);
}

/**
 * Implements hook_update_last_removed().
 */
function improved_theme_settings_update_last_removed() : int {
  return 11001;
}
