views.view.group_books:
  expected_config:
    display:
      default:
        display_options:
          sorts:
            created:
              exposed: true
  update_actions:
    add:
      display:
        default:
          display_options:
            sorts:
              created:
                expose:
                  field_identifier: created
