views.view.group_books:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            access:
              options:
                group_permission: 'view group_node:book relationship'
