views.view.group_books:
  expected_config: {  }
  update_actions:
    change:
      base_table: group_relationship_field_data
      display:
        default:
          display_options:
            fields:
              label:
                table: group_relationship_field_data
            filters:
              type:
                table: group_relationship_field_data
            relationships:
              gc__node:
                table: group_relationship_field_data
            arguments:
              gid:
                table: group_relationship_field_data
