core.entity_form_display.group.flexible_group.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_flexible_group_visibility:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_buttons
          weight: 100
    change:
      content:
        field_group_allowed_join_method:
          weight: 102
        field_group_allowed_visibility:
          weight: 101
        field_group_description:
          weight: 102
        field_group_image:
          weight: 103
        label:
          weight: 101
core.entity_view_display.group.flexible_group.default:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_flexible_group_visibility: true
core.entity_view_display.group.flexible_group.hero:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_flexible_group_visibility: true
core.entity_view_display.group.flexible_group.small_teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_flexible_group_visibility: true
        search_api_excerpt: true
core.entity_view_display.group.flexible_group.stream:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_flexible_group_visibility: true
core.entity_view_display.group.flexible_group.teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_flexible_group_visibility: true