field.storage.group.field_group_allowed_join_method:
  expected_config: {  }
  update_actions:
    change:
      settings:
        allowed_values: {  }
        allowed_values_function: '_social_group_allowed_values_callback'
