field.storage.taxonomy_term.field_group_type_icon:
  langcode: en
  status: true
  dependencies:
    module:
      - options
      - taxonomy
  id: taxonomy_term.field_group_type_icon
  field_name: field_group_type_icon
  entity_type: taxonomy_term
  type: list_string
  settings:
    allowed_values: {  }
    allowed_values_function: 'social_group_flexible_group_type_allowed_values_function'
  module: options
  locked: false
  cardinality: 1
  translatable: true
  indexes: {  }
  persist_with_no_fields: false
  custom_storage: false
field.field.taxonomy_term.group_type.field_group_type_icon:
  langcode: en
  status: true
  dependencies:
    config:
      - field.storage.taxonomy_term.field_group_type_icon
      - taxonomy.vocabulary.group_type
    module:
      - options
  id: taxonomy_term.group_type.field_group_type_icon
  field_name: field_group_type_icon
  entity_type: taxonomy_term
  bundle: group_type
  label: Icon
  description: ''
  required: true
  translatable: false
  default_value: {  }
  default_value_callback: 'social_group_flexible_group_type_default_value_function'
  settings: {  }
  field_type: list_string
core.entity_form_display.taxonomy_term.group_type.default:
  langcode: en
  status: true
  dependencies:
    config:
      - field.field.taxonomy_term.group_type.field_group_type_icon
      - taxonomy.vocabulary.group_type
    module:
      - path
      - text
  id: taxonomy_term.group_type.default
  targetEntityType: taxonomy_term
  bundle: group_type
  mode: default
  content:
    description:
      type: text_textarea
      weight: 1
      region: content
      settings:
        placeholder: ''
        rows: 5
      third_party_settings: {  }
    field_group_type_icon:
      weight: 3
      settings: {  }
      third_party_settings: {  }
      type: options_select
      region: content
    name:
      type: string_textfield
      weight: 0
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    path:
      type: path
      weight: 2
      region: content
      settings: {  }
      third_party_settings: {  }
  hidden: {  }
