core.entity_form_display.group.flexible_group.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_group_type:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: categorized_options_buttons
          weight: 100
      third_party_settings:
        field_group:
          group_content:
            children:
              - field_group_type
core.entity_view_display.group.flexible_group.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        field_group_type:
          label: above
          region: content
          settings:
            link: true
          third_party_settings: {  }
          type: entity_reference_label
          weight: 3
core.entity_view_display.group.flexible_group.hero:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_group_type: true
core.entity_view_display.group.flexible_group.small_teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_group_type: true
        search_api_excerpt: true
core.entity_view_display.group.flexible_group.stream:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_group_type: true
core.entity_view_display.group.flexible_group.teaser:
  expected_config: {  }
  update_actions:
    add:
      hidden:
        field_group_type: true
