core.entity_form_display.group.flexible_group.default:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_additional_details:
            children: {  }
            format_settings:
              classes: social-collapsible-fieldset
              description: ''
              id: ''
              open: false
              required_fields: true
            format_type: details
            label: 'Additional information'
            parent_name: ''
            region: content
            weight: 3
    change:
      third_party_settings:
        field_group:
          group_settings:
            weight: 4
