views.view.group_per_type:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - group.type.flexible_group
      display:
        flexible_group:
          id: flexible_group
          display_title: 'Flexible Group'
          display_plugin: page
          position: 2
          display_options:
            filters:
              label:
                id: label
                table: groups_field_data
                field: label
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: label
                plugin_id: string
                operator: contains
                value: ''
                group: 1
                exposed: true
                expose:
                  operator_id: label_op
                  label: Title
                  description: ''
                  use_operator: false
                  operator: label_op
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: label
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                    anonymous: '0'
                    administrator: '0'
                    contentmanager: '0'
                    verified: '0'
                    sitemanager: '0'
                  placeholder: ''
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
              status:
                id: status
                table: groups_field_data
                field: status
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: status
                plugin_id: boolean
                operator: '='
                value: '1'
                group: 1
                exposed: true
                expose:
                  operator_id: ''
                  label: Published
                  description: null
                  use_operator: false
                  operator: status_op
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: status
                  required: true
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: true
                group_info:
                  label: Status
                  description: ''
                  identifier: status
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items:
                    1:
                      title: Published
                      operator: '='
                      value: '1'
                    2:
                      title: Unpublished
                      operator: '='
                      value: '0'
              type:
                id: type
                table: groups_field_data
                field: type
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: group
                entity_field: type
                plugin_id: bundle
                operator: in
                value:
                  flexible_group: flexible_group
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
            filter_groups:
              operator: AND
              groups:
                1: AND
            defaults:
              filters: false
              filter_groups: false
            display_description: ''
            display_extenders:
              views_ef_fieldset: {  }
            path: admin/hub/flexible-group
          cache_metadata:
            max-age: -1
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - url
              - url.query_args
              - user.permissions
              - user.social_group_membership
            tags: {  }
