__global_actions:
  import_configs:
    - group.role.flexible_group-verified

social_group.settings:
  expected_config: { }
  update_actions:
    add:
      redirection:
        group_bundles:
          - 'flexible_group'
