group.type.flexible_group:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        module:
          - social_profile
      third_party_settings:
        social_profile:
          affiliation_candidate: true
          affiliation_enabled: false
