core.entity_view_display.group.flexible_group.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        flag_mute_group_notifications:
          weight: 10
          region: content
          settings: { }
          third_party_settings: { }
core.entity_view_display.group.flexible_group.hero:
  expected_config: {  }
  update_actions:
    add:
      content:
        flag_mute_group_notifications:
          weight: 10
          region: content
          settings: { }
          third_party_settings: { }
core.entity_view_display.group.flexible_group.small_teaser:
  expected_config: { }
  update_actions:
    add:
      hidden:
        flag_mute_group_notifications: true
core.entity_view_display.group.flexible_group.stream:
  expected_config: { }
  update_actions:
    add:
      hidden:
        flag_mute_group_notifications: true
core.entity_view_display.group.flexible_group.teaser:
  expected_config: { }
  update_actions:
    add:
      hidden:
        flag_mute_group_notifications: true
