field.storage.group.field_flexible_group_visibility:
  langcode: en
  status: true
  dependencies:
    module:
      - group
      - options
  id: group.field_flexible_group_visibility
  field_name: field_flexible_group_visibility
  entity_type: group
  type: list_string
  settings:
    allowed_values:
      -
        value: public
        label: Public
      -
        value: community
        label: Community
      -
        value: members
        label: 'Group members only (secret)'
    allowed_values_function: ''
  module: options
  locked: false
  cardinality: 1
  translatable: true
  indexes: {  }
  persist_with_no_fields: false
  custom_storage: false
field.field.group.flexible_group.field_flexible_group_visibility:
  langcode: en
  status: true
  dependencies:
    config:
      - field.storage.group.field_flexible_group_visibility
      - group.type.flexible_group
    module:
      - options
  id: group.flexible_group.field_flexible_group_visibility
  field_name: field_flexible_group_visibility
  entity_type: group
  bundle: flexible_group
  label: 'Group visibility'
  description: 'Who can see the group'
  required: true
  translatable: false
  default_value: {  }
  default_value_callback: ''
  settings: {  }
  field_type: list_string
