group.role.flexible_group-member:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        social_group:
          hubs_filter: true
          full_label: 'Group member'
group.role.flexible_group-group_manager:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        social_group:
          hubs_filter: true
          full_label: 'Group manager'
