field.field.group.flexible_group.field_group_description:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.group.flexible_group.field_group_location:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.group.flexible_group.field_group_address:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE
field.field.group.flexible_group.field_group_image:
  expected_config: {  }
  update_actions:
    change:
      translatable: TRUE

views.view.group_information:
  expected_config: {  }
  update_actions:
    add:
      display:
        page_group_about:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
