<?php

/**
 * @file
 * Configuration Update Base module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function config_update_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.config_update':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Configuration Update Base module provides functionality that other modules can use, related to updating and computing differences between configuration versions. This module does not provide any end-user functionality itself.') . '</p>';
      return $output;
  }
}
