views.view.latest_topics:
  expected_config: { }
  update_actions:
    add:
      display:
        group_topics_block:
          display_options:
            arguments:
              gid:
                table: group_relationship_field_data