field.field.node.topic.field_files:
  expected_config:
    translatable: false
  update_actions:
    change:
      translatable: true
field.field.node.topic.field_topic_image:
  expected_config:
    translatable: false
  update_actions:
    change:
      third_party_settings:
        content_translation:
          translation_sync:
            alt: alt
            file: '0'
            title: title
      translatable: true
field.field.node.topic.body:
  expected_config:
    translatable: false
  update_actions:
    change:
      translatable: true
views.view.latest_topics:
  expected_config: {  }
  update_actions:
    add:
      display:
        block_latest_topics:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        default:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
        group_topics_block:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
        page_latest_topics:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
views.view.topics:
  expected_config: {  }
  update_actions:
    add:
      display:
        block_user_topics:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
            rendering_language: '***LANGUAGE_language_interface***'
        default:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
        page_profile:
          display_options:
            rendering_language: '***LANGUAGE_language_interface***'
