core.entity_view_display.node.topic.activity:
  expected_config:
    content:
      field_topic_comments:
        settings:
          always_show_all_comments: '1'
  update_actions:
    change:
      content:
        field_topic_comments:
          settings:
            always_show_all_comments: true
field.field.node.topic.field_content_visibility:
  expected_config:
    default_value: null
  update_actions:
    change:
      default_value: {  }
