core.entity_view_display.node.topic.activity:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.topic.activity_comment:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.topic.default:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.topic.hero:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.topic.search_index:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

core.entity_view_display.node.topic.teaser:
  expected_config: {  }
  update_actions:
    delete:
      hidden:
        groups_type_closed_group: {  }
        groups_type_open_group: {  }
        groups_type_public_group: {  }

block.block.socialblue_views_block__latest_topics_group_topics_block:
  expected_config: {  }
  update_actions:
    delete:
      visibility:
        group_type:
          group_types:
            open_group: {  }
            closed_group: {  }
            public_group: {  }
            secret_group: {  }
