field.field.node.topic.field_files:
  expected_config:
    translatable: true
  update_actions:
    change:
      translatable: false
field.field.node.topic.field_topic_image:
  expected_config:
    translatable: false
  update_actions:
    change:
      third_party_settings:
        content_translation:
          translation_sync:
            alt: alt
            file: '0'
            title: title
      translatable: true
field.field.node.topic.body:
  expected_config:
    translatable: false
  update_actions:
    change:
      translatable: true
language.content_settings.node.topic:
  expected_config: { }
  update_actions:
    change:
      langcode: en
      status: true
      dependencies:
        config:
          - node.type.topic
        module:
          - content_translation
      third_party_settings:
        content_translation:
          enabled: true
          bundle_settings:
            untranslatable_fields_hide: '0'
      id: node.topic
      target_entity_type_id: node
      target_bundle: topic
      default_langcode: site_default
      language_alterable: false
core.base_field_override.node.topic.title:
  expected_config: { }
  update_actions:
    change:
      translatable: true
core.base_field_override.node.topic.path:
  expected_config: { }
  update_actions:
    change:
      translatable: true
core.base_field_override.node.topic.menu_link:
  expected_config: { }
  update_actions:
    change:
      translatable: true
core.base_field_override.node.topic.uid:
  expected_config: { }
  update_actions:
    change:
      translatable: true
core.base_field_override.node.topic.status:
  expected_config: { }
  update_actions:
    change:
      translatable: true
views.view.latest_topics:
  expected_config: {  }
  update_actions:
    add:
      display:
        default:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
        page_latest_topics:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
views.view.topics:
  expected_config: {  }
  update_actions:
    add:
      display:
        block_user_topics:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
        default:
          display_options:
            filters:
              default_langcode:
                admin_label: ''
                entity_field: default_langcode
                entity_type: node
                expose:
                  description: ''
                  identifier: ''
                  label: ''
                  multiple: false
                  operator: ''
                  operator_id: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  remember: false
                  remember_roles:
                    authenticated: authenticated
                  required: false
                  use_operator: false
                exposed: false
                field: default_langcode
                group: 1
                group_info:
                  default_group: All
                  default_group_multiple: {  }
                  description: ''
                  group_items: {  }
                  identifier: ''
                  label: ''
                  multiple: false
                  optional: true
                  remember: false
                  widget: select
                group_type: group
                id: default_langcode
                is_grouped: false
                operator: '='
                plugin_id: boolean
                relationship: none
                table: node_field_data
                value: '1'
