views.view.latest_topics:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              nid: {  }
        page_latest_topics:
          display_options:
            filters:
              nid: {  }
views.view.topics:
  expected_config: {  }
  update_actions:
    delete:
      display:
        default:
          display_options:
            filters:
              nid: {  }
        block_user_topics:
          display_options:
            filters:
              nid: {  }
