views.view.topics:
  expected_config:
    display:
      default:
        display_options:
          access:
            type: perm
            options:
              perm: 'access user profiles'
  update_actions:
    delete:
      display:
        default:
          display_options:
            access: { }
    change:
      display:
        default:
          display_options:
            access:
              type: social_profile_pages_access
              options: { }
