social_group_request.settings:
  type: config_object
  label: 'Hubs request to join settings'
  mapping:
    status:
      type: boolean
      label: 'Enable group request'
    allow_customize:
      type: mapping
      label: 'Allow customization per group type'
      mapping:
        '[key]':
          type: boolean
