name: Coding Standards

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request: { }

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "phpstan"
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0' ]
    steps:
      - name: Set default PHP${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP Stan
        run: vendor/bin/phpstan analyse -c phpstan.neon

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0' ]
    steps:
      - name: Set default PHP${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPCS
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
          enable_warnings: true
