name: Drupal coding standards

on: [pull_request]

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install composer dependencies so we have drupal/coder which adds our codesniffer, the bin/phpcs file
      # and dealerdirect/phpcodesniffer-composer-installer which changes the installer_path configuring all sniffs.
      - name: Install dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
