name: PHP Actions
on:
  push:
    branches:
      - master
  pull_request:

# Create
jobs:
  composer:
    name: Install Composer & PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP and composer install
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: mbstring
          version: '2'
          args: --ignore-platform-reqs

      - name: Archive build
        run: mkdir /tmp/github-actions && tar -cvf /tmp/github-actions/build-${{ matrix.php-versions }}.tar ./

      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

  phpunit:
    runs-on: ubuntu-latest
    needs: [composer]
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build-${{ matrix.php-versions }}.tar ./

      - name: Run PHPUnit
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-versions }}
          php_extensions: mbstring

  phpstan:
    runs-on: ubuntu-latest
    needs: [composer]
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build-${{ matrix.php-versions }}.tar ./

      - name: PHP Static Analysis
        uses: php-actions/phpstan@v2
        with:
          configuration: phpstan.neon
          path: ['src', 'modules/custom', 'modules/social_features']

  phpcs:
    runs-on: ubuntu-latest
    needs: [composer]
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build-${{ matrix.php-versions }}.tar ./

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'

