name: PHP Actions
on:
  push:
    branches:
      - master
  pull_request:

# Create
jobs:
  testing:
    name: PHP Actions for PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP and composer install
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.php-versions }}
          composer_version: '2'

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run PHPUnit
        uses: php-actions/phpunit@v2
        with:
          configuration: ./tests/phpunit/phpunit.xml
          php_version: ${{ matrix.php-versions }}
          php_extensions: mbstring

      - name: PHP Static Analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
