name: PHPUnit PHPStan PHPCS
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  testing:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - name: Do a checkout of the updated code
        uses: actions/checkout@v2
      # https://github.com/php-actions/composer#caching-dependencies-for-faster-builds
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP and composer install
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: mbstring
          version: '2'
          args: --ignore-platform-reqs
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit -c ./phpunit.xml.dist
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'


